In [1]:
#PREPROCESS 1
from alpaca.data.requests import StockBarsRequest
from alpaca.data.requests import CryptoBarsRequest
from alpaca.data.timeframe import TimeFrame
from alpaca.data.timeframe import TimeFrameUnit
from datetime import datetime

import pandas as pd
import numpy as np
global min_date
global max_date
import pandas as pd
import alpaca.data.historical as alp
import os
from dotenv import load_dotenv
load_dotenv()

API_KEY = os.getenv("ALPACA_API_KEY")
SECRET_KEY = os.getenv("ALPACA_SECRET_KEY")

client = alp.StockHistoricalDataClient(api_key=API_KEY, secret_key=SECRET_KEY)

min_date=datetime.now().date()+pd.Timedelta(days=-720)
max_date=datetime.now().date()+pd.Timedelta(days=-1)
def getMinuteLevel(asset):
    global min_date
    global max_date
    request_params = StockBarsRequest(
      symbol_or_symbols=[asset],
      timeframe=TimeFrame(1, TimeFrameUnit.Minute),
      #timeframe=TimeFrame(59, TimeFrameUnit.Minute),
      start=min_date,#dt(2024,1,1,0,0,0),
      end=max_date#dt(2024,11,1,0,0,0)
    )
    btc_bars = client.get_stock_bars(request_params)
    #print('done with call')
    # Convert to dataframe
    bars_df=btc_bars.df
    #print(bars_df)
    bars_df=bars_df.reset_index()
    bars_df['date']=[str(stamp)[:10] for stamp in bars_df.timestamp]
    bars_df['hour']=[int(str(stamp)[11:13]) for stamp in bars_df.timestamp]
    bars_df['minute']=[int(str(stamp)[14:16]) for stamp in bars_df.timestamp]
    bars_df['hour_mins']=[60*hr for hr in bars_df.hour]
    
    bars_df['day_min']=[hr_mins+m for hr_mins,m in zip(list(bars_df.hour_mins),list(bars_df.minute))]
    #bars_df['sum_of_price']=[vol*vwap for vol,vwap in zip(list(bars_df.volume),list(bars_df.vwap))]
    #bars_df['price_set']=[[vwap]*int(vol) for vol,vwap in zip(list(bars_df.volume),list(bars_df.vwap))]
    bars_df=bars_df.drop(columns=['hour','minute','hour_mins'])
    #bars_df['timestamp']=pd.to_datetime(bars_df['timestamp'], errors='coerce')
    return bars_df

getMinuteLevel('PBPB')

,symbol,timestamp,open,high,low,close,volume,trade_count,vwap,date,day_min
0,PBPB,2024-06-07 13:30:00+00:00,8.1400,8.1400,8.1350,8.1350,2441.0,4.0,8.139205,2024-06-07,810
1,PBPB,2024-06-07 13:32:00+00:00,8.1191,8.1191,8.1191,8.1191,200.0,2.0,8.119100,2024-06-07,812
2,PBPB,2024-06-07 13:37:00+00:00,8.1000,8.1000,8.0700,8.0700,4211.0,9.0,8.098537,2024-06-07,817
3,PBPB,2024-06-07 13:39:00+00:00,8.1200,8.1200,8.1200,8.1200,206.0,5.0,8.120000,2024-06-07,819
4,PBPB,2024-06-07 13:40:00+00:00,8.1200,8.1200,8.1200,8.1200,1479.0,1.0,8.120000,2024-06-07,820
...,...,...,...,...,...,...,...,...,...,...,...
62692,PBPB,2025-10-22 20:06:00+00:00,17.1300,17.1300,17.1300,17.1300,2489.0,12.0,17.130000,2025-10-22,1206
62693,PBPB,2025-10-22 20:10:00+00:00,17.1400,17.1400,17.1400,17.1400,5604.0,12.0,17.140000,2025-10-22,1210
62694,PBPB,2025-10-22 20:11:00+00:00,17.1500,17.1500,17.1500,17.1500,4802.0,8.0,17.150000,2025-10-22,1211
62695,PBPB,2025-10-22 21:41:00+00:00,17.1500,17.1500,17.1500,17.1500,1000.0,1.0,17.150000,2025-10-22,1301
62696,PBPB,2025-10-22 23:49:00+00:00,17.1500,17.1500,17.1500,17.1500,500.0,1.0,17.150000,2025-10-22,1429

In [2]:
4+9

13

In [3]:
#PREPROCESS 2: 
from holidays import US
import pandas as pd
import numpy as np
import yfinance as yf # Uncommented this so the code runs
from itertools import combinations

global verbose
verbose = False

# --- RSI FUNCTION DEFINITION ---
def calculate_rsi(series, window, min_lag):
    """Calculates the Relative Strength Index (RSI)."""
    delta = series.diff()
    gain = delta.where(delta > 0, 0)
    loss = -delta.where(delta < 0, 0)
    
    # Use min_periods=1 to maximize data availability, span=window for smoothing
    avg_gain = gain.ewm(span=window, min_periods=min_lag).mean()
    avg_loss = loss.ewm(span=window, min_periods=min_lag).mean()
    
    # Handle division by zero
    rs = np.divide(avg_gain, avg_loss, out=np.zeros_like(avg_gain), where=avg_loss!=0)
    rsi = 100 - (100 / (1 + rs))
    return rsi

# --- AGGREGATION FUNCTION ---
def getAggPizza(s, level):
    pza = getMinuteLevel(s)
    print('got minute-level')
   
    pza['current_vwap'] = pza['vwap'].ffill()
    pza['vwap_volume'] = pza['current_vwap'] * pza['volume']
   
    # Filter Holidays and Market Hours
    us_holidays = US(years=range(2023, 2026))
    pza['date'] = pza['timestamp'].dt.date
    pza['is_weekday'] = pza['timestamp'].dt.weekday < 5
    pza['is_not_holiday'] = ~pza['date'].isin([d for d in us_holidays])
   
    # Convert to ET for accurate local market hours (handles DST automatically)
    pza['timestamp_et'] = pza['timestamp'].dt.tz_convert('America/New_York')
    pza['time_et'] = pza['timestamp_et'].dt.time  # Separate column for time comparison
   
    market_hours = (pza['time_et'] >= pd.to_datetime('09:30').time()) & \
                   (pza['time_et'] < pd.to_datetime('16:00').time())
   
    pza = pza[pza['is_weekday'] & pza['is_not_holiday'] & market_hours].drop(
        columns=['date', 'is_weekday', 'is_not_holiday', 'time_et']
    ).reset_index(drop=True)  # Keep timestamp_et for flooring
   
    print('after weekends')
   
    # Floor the full datetime (in ET) to create the aggregation level
    pza['timestamp_level'] = pza['timestamp_et'].dt.floor(f'{level}min')
   
    pza_agg = pza.groupby('timestamp_level').agg({
        'vwap_volume': 'sum',
        'volume': 'sum'
    }).reset_index()
   
    pza_agg['mean_vwap'] = pza_agg['vwap_volume'] / pza_agg['volume']
    pza_agg['mean_vwap'] = pza_agg['mean_vwap'].ffill()
    pza_agg = pza_agg.rename(columns={'mean_vwap': f'mean_vwap_{level}'}).drop(columns=['vwap_volume'])
   
    # Extract hour/minute/day_of_week from the floored ET timestamp
    pza_agg['hour'] = pza_agg['timestamp_level'].dt.hour
    pza_agg['minute'] = pza_agg['timestamp_level'].dt.minute
    pza_agg['day_of_week'] = pza_agg['timestamp_level'].dt.dayofweek
   
    # minutes_since_open: 9:30 ET = 0
    pza_agg['minutes_since_open'] = (pza_agg['hour'] - 9) * 60 + (pza_agg['minute'] - 30)
    pza_agg['session_progress'] = pza_agg['minutes_since_open'] / 390.0
   
    # Optional: drop the helper if not needed downstream
    # pza_agg = pza_agg.drop(columns=['timestamp_et'])  # if you don't need it later
   
    print(level)
    return pza_agg

# --- MAIN FEATURE FUNCTION ---
def getGalledPrices(s, level, leads, lags):
    pza_agg = getAggPizza(s, level)
    
    # Merge with SPY
    spy_agg = getAggPizza('SPY', level)[['timestamp_level', 'mean_vwap_'+str(level)]].rename(
        columns={'timestamp_level': 'timestamp_level_SPY', 'mean_vwap_'+str(level): 'mean_vwap_'+str(level)+'_SPY'}
    )
    
    pza_agg = pd.merge(pza_agg, spy_agg, left_on='timestamp_level', right_on='timestamp_level_SPY', how='right')
    pza_agg['timestamp_level'] = pza_agg['timestamp_level_SPY']
    
    # Calculate Relative Price (Stock / SPY)
    pza_agg['mean_vwap_'+str(level)] = pza_agg['mean_vwap_'+str(level)] / pza_agg['mean_vwap_'+str(level)+'_SPY']
    pza_agg['mean_vwap_'+str(level)] = pza_agg['mean_vwap_'+str(level)].ffill()
    pza_agg['volume'] = pza_agg['volume'].fillna(0)
    pza_agg['pct_change'] = pza_agg['mean_vwap_'+str(level)].pct_change()
    
    lag_ptiles = range(10, 100, 20)
    lead_ptiles = [15, 85]
    
    print(len(pza_agg))
    print('before loop')
    max_lag=max(lags)
    max_lag_rows = max_lag* (6.5 * 60) / level
    if max_lag_rows > len(pza_agg):
        print('not enough past prices')
        return None
        
    min_lag = min(lags)
    
    # --- MAIN LAG LOOP ---
    for lag in lags:
        lag_rows = int(lag * (6.5 * 60 / level))
        
        # Percentiles
        for p in lag_ptiles:
            pza_agg[f'{p}th_ptile_lag_{lag}days'] = (
                pza_agg['mean_vwap_15'].shift(1)
                .rolling(window=lag_rows, min_periods=min_lag)
                .quantile(p/100)
            )
            pza_agg['change_lag_'+str(lag)+str(p)+'th_ptile'] = (
                pza_agg['mean_vwap_'+str(level)] - pza_agg[f'{p}th_ptile_lag_{lag}days']
            ) / pza_agg[f'{p}th_ptile_lag_{lag}days']
            
        # Volatility & Momentum
        pza_agg['rolling_avg_vol_'+str(lag)] = pza_agg['volume'].shift(1).rolling(window=lag_rows, min_periods=min_lag).mean()
        pza_agg['relative_volume_'+str(lag)] = pza_agg['volume'] / pza_agg['rolling_avg_vol_'+str(lag)]
        
        pza_agg['volatility_'+str(lag)] = pza_agg['pct_change'].shift(1).rolling(window=lag_rows, min_periods=min_lag).std()
        
        rolling_mean = pza_agg['mean_vwap_'+str(level)].shift(1).rolling(window=lag_rows, min_periods=min_lag).mean()
        rolling_std = pza_agg['mean_vwap_'+str(level)].shift(1).rolling(window=lag_rows, min_periods=min_lag).std()
        pza_agg[f'rolling_mean_{lag}'] = rolling_mean
        pza_agg[f'rolling_std_{lag}'] = rolling_std
        
        pza_agg[f'z_score_{lag}'] = (pza_agg['mean_vwap_'+str(level)] - rolling_mean) / rolling_std.replace(0, np.nan)
        pza_agg['bb_width_'+str(lag)] = (rolling_std * 2) / rolling_mean
        
        # Efficiency Ratio
        net_change = pza_agg['mean_vwap_15'].shift(1).rolling(lag_rows, min_periods=min_lag).apply(lambda x: abs(x.iloc[-1] - x.iloc[0]) if len(x) > 1 else np.nan)
        sum_of_changes = pza_agg['mean_vwap_' + str(level)].diff().abs().shift(1).rolling(window=lag_rows, min_periods=min_lag).sum()
        pza_agg[f'efficiency_ratio_{lag}'] = net_change / sum_of_changes.replace(0, np.nan)
        
        # Skewness
        pza_agg[f'skew_{lag}'] = pza_agg['pct_change'].shift(1).rolling(window=lag_rows, min_periods=min_lag).skew()
        
        # Volume Force
        pza_agg[f'volume_force_{lag}'] = pza_agg['pct_change'] * pza_agg[f'relative_volume_{lag}']
        
        # RSI
        pza_agg['rsi_'+str(lag)] = calculate_rsi(pza_agg['mean_vwap_'+str(level)], window=lag_rows, min_lag=min_lag)
        pza_agg[f'rsi_divergence_{lag}'] = np.sign(pza_agg[f'rsi_{lag}'].pct_change()) * np.sign(pza_agg['pct_change'])
        
        # Adjustments
        session_adjust = 1 - np.abs(2 * pza_agg['session_progress'] - 1) + 0.5
        pza_agg[f'session_adj_rel_volume_{lag}'] = pza_agg[f'relative_volume_{lag}'] * session_adjust
        
        weekday_avg_vol = pza_agg.groupby('day_of_week')[f'volatility_{lag}'].transform('mean')
        pza_agg[f'weekday_adj_vol_{lag}'] = pza_agg[f'volatility_{lag}'] / weekday_avg_vol.replace(0, np.nan)
        pza_agg[f'weekday_adj_vol_{lag}'] = pza_agg[f'weekday_adj_vol_{lag}'].fillna(1)

    # Momentum Diff (MM Diff)
    for lag1, lag2 in combinations(lags, 2):
        s_lag, l_lag = sorted((lag1, lag2))
        col_short = f'50th_ptile_lag_{s_lag}days'
        col_long = f'50th_ptile_lag_{l_lag}days'
        
        pza_agg[f'mm_diff_{s_lag}_{l_lag}'] = (pza_agg[col_short] - pza_agg[col_long]) / pza_agg[col_long]
        
        mom_col = f'mm_diff_{s_lag}_{l_lag}'
        vol_col = f'volatility_{l_lag}'
        pza_agg[f'risk_adj_{mom_col}'] = pza_agg[mom_col] / pza_agg[vol_col].replace(0, np.nan)
        pza_agg[f'risk_adj_{mom_col}'] = pza_agg[f'risk_adj_{mom_col}'].fillna(0)


    # Lead (Target) Calculation
    min_lead = min(leads)
    for lead in leads:
        lead_rows = int(lead * (6.5 * 60 / level))
        for p in lead_ptiles:
            pza_agg[f'{p}th_ptile_lead_{lead}days'] = (
                pza_agg['mean_vwap_15']
                .iloc[::-1].shift(1)
                .rolling(window=lead_rows, min_periods=min_lead)
                .quantile(p/100)
                .iloc[::-1]
                .values
            )
            pza_agg['change_lead_'+str(lead)+'_'+str(p)+'th_ptile'] = (
                pza_agg[f'{p}th_ptile_lead_{lead}days'] - pza_agg['mean_vwap_'+str(level)]
            ) / pza_agg['mean_vwap_'+str(level)]

    # --- EARNINGS DATE CALCULATION (OPTIMIZED) ---
    t = yf.Ticker(s)
    earnings_df = pd.DataFrame(t.earnings_dates).reset_index()
    
    # Check if we have data
    if 'Earnings Date' in earnings_df.columns:
        earnings_df = earnings_df.rename(columns={'Earnings Date': 'earning_date'})
    
    # Ensure Timestamp compatibility
   # pza_agg['timestamp_level'] = pd.to_datetime(pza_agg['timestamp_level'], utc=True)
    
    has_earnings = False
    if not earnings_df.empty and 'earning_date' in earnings_df.columns:
        try:
            # Convert earnings dates to Eastern Time to match timestamp_level
            earnings_df['earning_date'] = pd.to_datetime(earnings_df['earning_date']).dt.tz_convert('America/New_York')
            earnings_df = earnings_df.sort_values('earning_date').dropna(subset=['earning_date'])
            pza_agg = pza_agg.sort_values('timestamp_level')
            has_earnings = True
        except Exception as e:
            print(f"Earnings date conversion failed: {e}")
    if has_earnings:
        # Backward Search (Days Since)
        pza_agg = pd.merge_asof(
            pza_agg,
            earnings_df[['earning_date']],
            left_on='timestamp_level',
            right_on='earning_date',
            direction='backward'
        ).rename(columns={'earning_date': 'last_earnings_date'})

        # Forward Search (Days Before)
        pza_agg = pd.merge_asof(
            pza_agg,
            earnings_df[['earning_date']],
            left_on='timestamp_level',
            right_on='earning_date',
            direction='forward'
        ).rename(columns={'earning_date': 'next_earnings_date'})

        pza_agg['days_since_earnings'] = ((pza_agg['timestamp_level'] - pza_agg['last_earnings_date']).dt.total_seconds() / 86400).fillna(90.0)
        pza_agg['days_before_earnings'] = ((pza_agg['next_earnings_date'] - pza_agg['timestamp_level']).dt.total_seconds() / 86400).fillna(90.0)
        
        pza_agg = pza_agg.drop(columns=['last_earnings_date', 'next_earnings_date'])
    else:
        print('No earnings data found or processing failed.')
        pza_agg['days_since_earnings'] = 90.0
        pza_agg['days_before_earnings'] = 90.0


    # --- INTERACTIVE FEATURES SECTION ---
    
    # 1. Earnings Interaction
    target_lag = lags[0]
    
    if 'days_before_earnings' in pza_agg.columns:
        days_to_earn = pza_agg['days_before_earnings'].clip(lower=0)
        earnings_proximity = 1 / (days_to_earn + 1)
        
        base_metrics = ['volatility', 'relative_volume', 'z_score', 'bb_width', 'efficiency_ratio', 'rsi']
        
        for metric in base_metrics:
            col_name = f'{metric}_{target_lag}'
            if col_name in pza_agg.columns:
                pza_agg[f'{metric}_{target_lag}_x_earn_prox'] = (
                    pza_agg[col_name] * earnings_proximity
                )

        pct_col_name = f'change_lag_{target_lag}50th_ptile' 
        if pct_col_name in pza_agg.columns:
            pza_agg[f'change_lag_{target_lag}_50th_ptile_x_earn_prox'] = (
                pza_agg[pct_col_name] * earnings_proximity
            )

        # 2. Day of Week Interactions
        # Add the pct change column to the list for this loop
        loop_metrics = base_metrics + [pct_col_name] if pct_col_name in pza_agg.columns else base_metrics

        for metric in loop_metrics:
            if metric == pct_col_name:
                col_name = metric
                short_name = 'pct_chg_50th'
            else:
                col_name = f'{metric}_{target_lag}'
                short_name = metric

            if col_name in pza_agg.columns:
                # Mon = 0, Fri = 4
                pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
                pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)

        # 3. Time of Day Interactions
        pza_agg['is_open_30m'] = (pza_agg['minutes_since_open'] <= 30).astype(int)
        pza_agg['is_close_30m'] = (pza_agg['minutes_since_open'] >= 360).astype(int)
        pza_agg['is_mid_day'] = ((pza_agg['minutes_since_open'] > 30) & (pza_agg['minutes_since_open'] < 360)).astype(int)

        for metric in loop_metrics:
            if metric == pct_col_name:
                col_name = metric
                short_name = 'pct_chg_50th'
            else:
                col_name = f'{metric}_{target_lag}'
                short_name = metric

            if col_name in pza_agg.columns:
                pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
                pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
                pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']

    # At the end of getGalledPrices, just before return pza_agg
    pza_agg['timestamp_level'] = pza_agg['timestamp_level'].dt.tz_localize(None)  # or .dt.tz_convert(None)
    return pza_agg


s='PZA'
# Assuming yf is available, we run the function to test

ggp=getGalledPrices(s,15,[15],[10,25,50,75]) 
#ggp.columns = [col + '_' + str(s) for col in ggp.columns]
#ggp

got minute-level
after weekends
15
got minute-level
after weekends
15
12740
before loop

C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:161: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'weekday_adj_vol_{lag}'] = pza_agg[f'volatility_{lag}'] / weekday_avg_vol.replace(0, np.nan)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'mm_diff_{s_lag}_{l_lag}'] = (pza_agg[col_short] - pza_agg[col_long]) / pza_agg[col_long]
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:174: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'risk_adj_{mom_col}'] = pza_agg[mom_col] / pza_agg[vol_col].replace(0, np.nan)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'mm_diff_{s_lag}_{l_lag}'] = (pza_agg[col_short] - pza_agg[col_long]) / pza_agg[col_long]
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:174: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'risk_adj_{mom_col}'] = pza_agg[mom_col] / pza_agg[vol_col].replace(0, np.nan)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'mm_diff_{s_lag}_{l_lag}'] = (pza_agg[col_short] - pza_agg[col_long]) / pza_agg[col_long]
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:174: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'risk_adj_{mom_col}'] = pza_agg[mom_col] / pza_agg[vol_col].replace(0, np.nan)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'mm_diff_{s_lag}_{l_lag}'] = (pza_agg[col_short] - pza_agg[col_long]) / pza_agg[col_long]
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:174: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'risk_adj_{mom_col}'] = pza_agg[mom_col] / pza_agg[vol_col].replace(0, np.nan)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'mm_diff_{s_lag}_{l_lag}'] = (pza_agg[col_short] - pza_agg[col_long]) / pza_agg[col_long]
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:174: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'risk_adj_{mom_col}'] = pza_agg[mom_col] / pza_agg[vol_col].replace(0, np.nan)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:170: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'mm_diff_{s_lag}_{l_lag}'] = (pza_agg[col_short] - pza_agg[col_long]) / pza_agg[col_long]
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:174: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'risk_adj_{mom_col}'] = pza_agg[mom_col] / pza_agg[vol_col].replace(0, np.nan)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{p}th_ptile_lead_{lead}days'] = (
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:191: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['change_lead_'+str(lead)+'_'+str(p)+'th_ptile'] = (
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:183: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{p}th_ptile_lead_{lead}days'] = (
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:191: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['change_lead_'+str(lead)+'_'+str(p)+'th_ptile'] = (
PZA: $PZA: possibly delisted; no earnings dates found

No earnings data found or processing failed.

C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:241: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['days_since_earnings'] = 90.0
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:242: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['days_before_earnings'] = 90.0
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:259: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{metric}_{target_lag}_x_earn_prox'] = (
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:259: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{metric}_{target_lag}_x_earn_prox'] = (
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:259: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{metric}_{target_lag}_x_earn_prox'] = (
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:259: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{metric}_{target_lag}_x_earn_prox'] = (
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:259: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{metric}_{target_lag}_x_earn_prox'] = (
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:259: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{metric}_{target_lag}_x_earn_prox'] = (
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:265: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'change_lag_{target_lag}_50th_ptile_x_earn_prox'] = (
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:287: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_open_30m'] = (pza_agg['minutes_since_open'] <= 30).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:288: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_close_30m'] = (pza_agg['minutes_since_open'] >= 360).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:289: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_mid_day'] = ((pza_agg['minutes_since_open'] > 30) & (pza_agg['minutes_since_open'] < 360)).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']

In [4]:
industry='restaurants'
all=pd.read_excel('all_stocks_class.xlsx')
swa_stocks=all[all['inds']==industry.capitalize()].drop_duplicates()

In [4]:
#swa_stocks

In [28]:
#PREPROCESS 3: get ggp table for each stock
import time
start_time = time.time()
global level
level=15

for s in swa_stocks.stocks:
    #print(s)
    #print(type(s))
    print(s=='nan')
    start_time_loop = time.time()
    try:
        s=s.replace('-', '.')
    except:
        continue
    if isinstance(s, float):
        continue
    try:
        pd.read_csv('ggp_rel_tables/'+industry+'/ggp_'+s+'.csv')
        #buudfoon
        continue
    except:
        print(s)
        ggp=getGalledPrices(s,15,[15],[10,25,50])
        try:
            ggp.columns = [col + '_' + str(s) for col in ggp.columns]
            ggp.to_csv('ggp_rel_tables/'+industry+'/ggp_'+s+'.csv')
        except:
            continue
    end_time_loop = time.time()
    elapsed_time = end_time_loop - start_time_loop
    print(f"Elapsed time: {elapsed_time:.2f} seconds")
end_time = time.time()
elapsed_time = end_time - start_time
print(f"Elapsed time: {elapsed_time:.2f} seconds")

False
CHSN
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop

CHSN: $CHSN: possibly delisted; no earnings dates found
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:287: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_open_30m'] = (pza_agg['minutes_since_open'] <= 30).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:288: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_close_30m'] = (pza_agg['minutes_since_open'] >= 360).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:289: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_mid_day'] = ((pza_agg['minutes_since_open'] > 30) & (pza_agg['minutes_since_open'] < 360)).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']

No earnings data found or processing failed.
Elapsed time: 38.01 seconds
False
BH
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 31.77 seconds
False
BH.A
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop

BH.A: $BH.A: possibly delisted; no earnings dates found
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:287: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_open_30m'] = (pza_agg['minutes_since_open'] <= 30).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:288: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_close_30m'] = (pza_agg['minutes_since_open'] >= 360).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:289: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_mid_day'] = ((pza_agg['minutes_since_open'] > 30) & (pza_agg['minutes_since_open'] < 360)).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']

No earnings data found or processing failed.
Elapsed time: 29.26 seconds
False
BH.A
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop

BH.A: $BH.A: possibly delisted; no earnings dates found
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:287: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_open_30m'] = (pza_agg['minutes_since_open'] <= 30).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:288: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_close_30m'] = (pza_agg['minutes_since_open'] >= 360).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:289: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_mid_day'] = ((pza_agg['minutes_since_open'] > 30) & (pza_agg['minutes_since_open'] < 360)).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']

No earnings data found or processing failed.
Elapsed time: 29.10 seconds
False
TWNP
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop

TWNP: $TWNP: possibly delisted; no earnings dates found
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:287: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_open_30m'] = (pza_agg['minutes_since_open'] <= 30).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:288: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_close_30m'] = (pza_agg['minutes_since_open'] >= 360).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:289: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_mid_day'] = ((pza_agg['minutes_since_open'] > 30) & (pza_agg['minutes_since_open'] < 360)).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']

No earnings data found or processing failed.
Elapsed time: 27.04 seconds
False
YOSH
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop

YOSH: $YOSH: possibly delisted; no earnings dates found
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:287: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_open_30m'] = (pza_agg['minutes_since_open'] <= 30).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:288: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_close_30m'] = (pza_agg['minutes_since_open'] >= 360).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:289: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_mid_day'] = ((pza_agg['minutes_since_open'] > 30) & (pza_agg['minutes_since_open'] < 360)).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']

No earnings data found or processing failed.
Elapsed time: 27.11 seconds
False
HDL
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop

HDL: $HDL: possibly delisted; no earnings dates found
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:287: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_open_30m'] = (pza_agg['minutes_since_open'] <= 30).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:288: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_close_30m'] = (pza_agg['minutes_since_open'] >= 360).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:289: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_mid_day'] = ((pza_agg['minutes_since_open'] > 30) & (pza_agg['minutes_since_open'] < 360)).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']

No earnings data found or processing failed.
Elapsed time: 28.66 seconds
False
ARKR
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop

C:\Users\allth\anaconda3\Lib\site-packages\yfinance\base.py:765: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Earnings Date'] = pd.to_datetime(df['Event Start Date'])

Elapsed time: 27.54 seconds
False
GTIM
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 30.55 seconds
False
NDLS
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 32.30 seconds
False
CNNE
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 34.94 seconds
False
THCH
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 27.85 seconds
False
FWRG
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 37.77 seconds
False
SG
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 41.40 seconds
False
ARCO
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 37.87 seconds
False
BJRI
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 34.91 seconds
False
BLMN
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 38.39 seconds
False
BROS
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 41.70 seconds
False
CAKE
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 42.17 seconds
False
CAVA
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 41.55 seconds
False
CBRL
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 40.20 seconds
False
CMG
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 43.45 seconds
False
FATBW
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop

FATBW: $FATBW: possibly delisted; no earnings dates found
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:287: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_open_30m'] = (pza_agg['minutes_since_open'] <= 30).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:288: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_close_30m'] = (pza_agg['minutes_since_open'] >= 360).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:289: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_mid_day'] = ((pza_agg['minutes_since_open'] > 30) & (pza_agg['minutes_since_open'] < 360)).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']

No earnings data found or processing failed.
Elapsed time: 27.60 seconds
False
FATBP
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop

FATBP: $FATBP: possibly delisted; no earnings dates found
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:287: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_open_30m'] = (pza_agg['minutes_since_open'] <= 30).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:288: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_close_30m'] = (pza_agg['minutes_since_open'] >= 360).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:289: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_mid_day'] = ((pza_agg['minutes_since_open'] > 30) & (pza_agg['minutes_since_open'] < 360)).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']

No earnings data found or processing failed.
Elapsed time: 30.60 seconds
False
FATBB
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop

FATBB: $FATBB: possibly delisted; no earnings dates found
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:287: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_open_30m'] = (pza_agg['minutes_since_open'] <= 30).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:288: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_close_30m'] = (pza_agg['minutes_since_open'] >= 360).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:289: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_mid_day'] = ((pza_agg['minutes_since_open'] > 30) & (pza_agg['minutes_since_open'] < 360)).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']

No earnings data found or processing failed.
Elapsed time: 29.43 seconds
False
FAT
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 32.97 seconds
False
DENN
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 38.31 seconds
False
REBN
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 32.41 seconds
False
DIN
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 36.77 seconds
False
DPZ
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 37.65 seconds
False
DRI
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 39.53 seconds
False
EAT
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 39.71 seconds
False
GENK
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 30.12 seconds
False
JACK
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 39.82 seconds
False
KRUS
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 34.18 seconds
False
LOCO
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 34.29 seconds
False
NATH
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 28.64 seconds
False
PBPB
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 34.11 seconds
False
PTLO
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 41.06 seconds
False
PZZA
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 38.02 seconds
False
QSR
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 39.95 seconds
False
RICK
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 31.42 seconds
False
RRGB
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 36.93 seconds
False
SHAK
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 40.09 seconds
False
STKS
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 30.97 seconds
False
TXRH
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 38.96 seconds
False
WEN
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 41.15 seconds
False
WING
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 37.73 seconds
False
BTBD
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop

BTBD: $BTBD: possibly delisted; no earnings dates found
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:287: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_open_30m'] = (pza_agg['minutes_since_open'] <= 30).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:288: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_close_30m'] = (pza_agg['minutes_since_open'] >= 360).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:289: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_mid_day'] = ((pza_agg['minutes_since_open'] > 30) & (pza_agg['minutes_since_open'] < 360)).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']

No earnings data found or processing failed.
Elapsed time: 29.88 seconds
False
YUM
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 41.26 seconds
False
YUMC
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 42.38 seconds
False
SBUX
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 43.63 seconds
False
MCD
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 41.57 seconds
False
PETZ
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop

PETZ: $PETZ: possibly delisted; no earnings dates found
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:287: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_open_30m'] = (pza_agg['minutes_since_open'] <= 30).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:288: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_close_30m'] = (pza_agg['minutes_since_open'] >= 360).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:289: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_mid_day'] = ((pza_agg['minutes_since_open'] > 30) & (pza_agg['minutes_since_open'] < 360)).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_26892\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']

No earnings data found or processing failed.
Elapsed time: 29.74 seconds
False
RAVE
got minute-level
after weekends
15
got minute-level
after weekends
15
12766
before loop
Elapsed time: 29.39 seconds
Elapsed time: 1943.84 seconds

In [5]:

# PREPROCESS 4: get join_df based on ggp tables

import glob
import pandas as pd
import os


def getFeaturePres(industry, folder_path, daily_folder=None):
    # Get all CSV files in the folder
    csv_files = glob.glob(os.path.join(folder_path, "*.csv"))
    
    if not csv_files:
        raise FileNotFoundError(f"No CSV files found in {folder_path}")
    
    print(f"Found {len(csv_files)} files: {[os.path.basename(f) for f in csv_files]}")
    
    # Load the first file as the base
    base_file = csv_files[0]
    base_stock = os.path.basename(base_file).replace('ggp_', '').replace('.csv', '')
    base_df = pd.read_csv(base_file).drop(columns=['Unnamed: 0'], errors='ignore')
    print(f"Base stock: {base_stock}")
    
    # Identify and convert timestamp column
    timestamp_col_base = f'timestamp_level_{base_stock}'
    if timestamp_col_base not in base_df.columns:
        raise KeyError(f"Timestamp column {timestamp_col_base} not found in {base_file}")
    
    # --- ADDED: Convert to consistent datetime format ---
    base_df[timestamp_col_base] = pd.to_datetime(base_df[timestamp_col_base])
    
    # Set index (drop=False keeps the column available for your coalesce logic later)
    join_df = base_df.set_index(timestamp_col_base, drop=False)
    
    timestamp_cols = [timestamp_col_base]
    cutoff_date= pd.Timestamp('2026-03-01')
    # Loop over the remaining files and outer-join them
    for file_path in csv_files[1:]:
        stock = os.path.basename(file_path).replace('ggp_', '').replace('.csv', '')
        print(f"Joining {stock}...")
    
        df = pd.read_csv(file_path).drop(columns=['Unnamed: 0'], errors='ignore')
    
        timestamp_col = f'timestamp_level_{stock}'
        if timestamp_col not in df.columns:
            print(f"Warning: Timestamp column {timestamp_col} missing in {file_path}, skipping")
            continue
        
        # --- ADDED: Convert to consistent datetime format ---
        df[timestamp_col] = pd.to_datetime(df[timestamp_col])

        latest_data_point = df[df[f'hour_{stock}'].notna() & (df[f'hour_{stock}'] != '')][timestamp_col].max()
        print(latest_data_point)
        # If the stock doesn't have data past the cutoff, ignore it
        if latest_data_point < cutoff_date:
            print(f"Skipping {stock}: Data is stale (Last seen: {latest_data_point.date()})")
            continue
        # Set index and align name
        df = df.set_index(timestamp_col, drop=False)
        df.index.name = join_df.index.name 
    
        # Outer join on the datetime index
        join_df = join_df.join(df.drop(columns=[timestamp_col]), how='outer')
    
        timestamp_cols.append(timestamp_col)
    
    # Sort chronologically
    join_df = join_df.sort_index()
    
    # Re-add the individual timestamp columns if they were dropped during join 
    # (Note: Since we joined on index, we use the index to fill the final timestamp)
    join_df['timestamp'] = join_df.index
    
    # Clean up: If you want to drop the specific 'timestamp_level_XXX' columns now:
    cols_to_drop = [c for c in join_df.columns if 'timestamp_level_' in c]
    join_df = join_df.drop(columns=cols_to_drop)
    
    print(f"\nFinal joined DataFrame shape: {join_df.shape}")
    
    save_path = 'feature_presentation_' + industry + '.csv'
    if daily_folder:
        save_path = os.path.join(daily_folder, save_path)
        
    join_df.to_csv(save_path)
    return join_df

# Run the function

#getFeaturePres(industry,'ggp_rel_tables/'+industry)

In [35]:
df2=pd.read_csv('ggp_rel_tables/'+industry+'/ggp_TSM.csv')
[c for c in jino.columns if 'PBPB' in c]

['rolling_mean_10_TSM', 'rolling_mean_25_TSM', 'rolling_mean_50_TSM']

In [41]:
file_path='ggp_rel_tables/'+industry+'/ggp_PBPB.csv'
pd.read_csv(file_path).drop(columns=['Unnamed: 0'], errors='ignore')

,timestamp_level_PBPB,volume_PBPB,mean_vwap_15_PBPB,hour_PBPB,minute_PBPB,day_of_week_PBPB,minutes_since_open_PBPB,session_progress_PBPB,timestamp_level_SPY_PBPB,mean_vwap_15_SPY_PBPB,...,bb_width_MidDay_PBPB,efficiency_ratio_Open30m_PBPB,efficiency_ratio_Close30m_PBPB,efficiency_ratio_MidDay_PBPB,rsi_Open30m_PBPB,rsi_Close30m_PBPB,rsi_MidDay_PBPB,pct_chg_50th_Open30m_PBPB,pct_chg_50th_Close30m_PBPB,pct_chg_50th_MidDay_PBPB
0,2024-04-22 09:30:00,6932.0,0.021144,9.0,30.0,0.0,0.0,0.000000,2024-04-22 09:30:00-04:00,497.427265,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-04-22 09:45:00,6321.0,0.021233,9.0,45.0,0.0,15.0,0.038462,2024-04-22 09:45:00-04:00,497.740282,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-04-22 10:00:00,4362.0,0.021240,10.0,0.0,0.0,30.0,0.076923,2024-04-22 10:00:00-04:00,497.846743,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-04-22 10:15:00,6485.0,0.021162,10.0,15.0,0.0,45.0,0.115385,2024-04-22 10:15:00-04:00,496.861084,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-04-22 10:30:00,2560.0,0.021072,10.0,30.0,0.0,60.0,0.153846,2024-04-22 10:30:00-04:00,496.748037,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12761,2026-04-09 14:45:00,0.0,0.025653,NaN,NaN,NaN,NaN,NaN,2026-04-09 14:45:00-04:00,679.065363,...,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0
12762,2026-04-09 15:00:00,0.0,0.025653,NaN,NaN,NaN,NaN,NaN,2026-04-09 15:00:00-04:00,679.779000,...,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0
12763,2026-04-09 15:15:00,0.0,0.025653,NaN,NaN,NaN,NaN,NaN,2026-04-09 15:15:00-04:00,679.852446,...,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0
12764,2026-04-09 15:30:00,0.0,0.025653,NaN,NaN,NaN,NaN,NaN,2026-04-09 15:30:00-04:00,680.349354,...,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0
12765,2026-04-09 15:45:00,0.0,0.025653,NaN,NaN,NaN,NaN,NaN,2026-04-09 15:45:00-04:00,680.215675,...,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
jino = pd.read_csv('feature_presentation_' + industry + '.csv')
jino
[c for c in jino.columns if 'PBPB' in c]

[]

In [7]:
#PREPROCESS 5: get jino and identify featrues/targets
import pandas as pd
import joblib

def get_features(s):
    lags = [10, 25, 50]  # lag days
    ptiles = [10, 30, 50, 70, 90]  # percentiles
    other_lag_metrics = [
        'rolling_avg_vol', 'relative_volume', 'volatility', 'z_score',
        'bb_width', 'efficiency_ratio', 'skew', 'volume_force',
        'rsi', 'rsi_divergence', 'session_adj_rel_volume', 'weekday_adj_vol'
    ]

    lag_features = []

    # 1. Change-from-percentile features: 5 per lag × 4 lags = 20
    for lag in lags:
        for p in ptiles:
            lag_features.append(f'change_lag_{lag}{p}th_ptile_{s}')

    # 2. Other lag metrics: 12 per lag × 4 lags = 48
    for lag in lags:
        for metric in other_lag_metrics:
            lag_features.append(f'{metric}_{lag}_{s}')

    # Total lag features: 20 + 48 = 68
    # (We removed the 20 raw ptile_lag columns as they are time-correlated)

    # Add timestamp column
    #lag_features.append(f'timestamp_level_{s}')

    print(f"Total features generated: {len(lag_features)}")  # Should be 69

    return lag_features

#GET FEATURES AND TARGETS
import pandas as pd
jino_cols=jino.columns

stocks=pd.read_excel('all_stocks_class.xlsx').drop_duplicates()
ind_stocks = list(set(c.split('_')[-1] for c in jino.columns if c != 'timestamp' and '_' in c))
get_rats=jino[[c for c in jino.columns if 'change_lead' in c]].columns
#get_rats
features_giant=[]
for s in ind_stocks:
    s=s.replace('-', '.')
    #features = joblib.load('features_giant_list_'+industry+'.pkl')
    print(s)
    features_giant+=get_features(s)

features_giant = list(set([col for col in features_giant if 'nan' not in col]))
joblib.dump(features_giant, 'features_giant_list_'+industry+'.pkl')

BLMN
Total features generated: 51
HDL
Total features generated: 51
REBN
Total features generated: 51
QSR
Total features generated: 51
CHSN
Total features generated: 51
TXRH
Total features generated: 51
BROS
Total features generated: 51
FWRG
Total features generated: 51
RAVE
Total features generated: 51
NATH
Total features generated: 51
BJRI
Total features generated: 51
CNNE
Total features generated: 51
SHAK
Total features generated: 51
WEN
Total features generated: 51
RRGB
Total features generated: 51
MCD
Total features generated: 51
ARKR
Total features generated: 51
YUM
Total features generated: 51
BH.A
Total features generated: 51
STKS
Total features generated: 51
ARCO
Total features generated: 51
KRUS
Total features generated: 51
BTBD
Total features generated: 51
CBRL
Total features generated: 51
BH
Total features generated: 51
CMG
Total features generated: 51
JACK
Total features generated: 51
EAT
Total features generated: 51
CAKE
Total features generated: 51
LOCO
Total features generated: 51
PZZA
Total features generated: 51
GTIM
Total features generated: 51
SBUX
Total features generated: 51
THCH
Total features generated: 51
PTLO
Total features generated: 51
RICK
Total features generated: 51
DPZ
Total features generated: 51
CAVA
Total features generated: 51
WING
Total features generated: 51
PETZ
Total features generated: 51
GENK
Total features generated: 51
NDLS
Total features generated: 51
DIN
Total features generated: 51
SG
Total features generated: 51
DRI
Total features generated: 51
YUMC
Total features generated: 51

['features_giant_list_restaurants.pkl']

In [55]:
'rolling_avg_vol_50_timestamp' in features_giant

False

In [7]:
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import mutual_info_classif
import pandas as pd
import numpy as np
import joblib
import random

def get_ghost_baseline(df, target_col, stride=26, n_neighbors=20):
    # 'target_col' is ignored here, we assume 'target_class' exists
    features = joblib.load('features_giant_list_'+industry+'.pkl')
    features_sample = random.sample(features, min(500, len(features)))
    
    offset = random.randint(0, stride - 1)
    
    # 1. FIX: Replace Infinity with NaN BEFORE dropping
    sampled_df = df.iloc[offset::stride].replace([np.inf, -np.inf], np.nan)
    sampled_df = sampled_df.dropna(subset=['target_class']).copy()
    
    # 2. THE GHOST MOVE: Shuffle the target
    sampled_df['target_class'] = sampled_df['target_class'].sample(frac=1).values
    
    print(f"Calculating Noise Floor on {len(sampled_df)} rows...")
    
    ghost_results = []
    scaler = StandardScaler()
    
    # 3. Pairwise MI on the Shuffled Target
    for col in features_sample: 
        valid_df = sampled_df[[col, 'target_class']].dropna()
        if len(valid_df) > n_neighbors:
            X_scaled = scaler.fit_transform(valid_df[[col]])
            mi_score = mutual_info_classif(X_scaled, valid_df['target_class'], 
                                          discrete_features=False, n_neighbors=n_neighbors)[0]
            ghost_results.append({'Feature': col, 'shuffle_drop': mi_score})
            
    # 4. Create DataFrame
    ghost_df = pd.DataFrame(ghost_results).set_index('Feature')
    return ghost_df


def get_true_mi_scores(df_input, target_col, stride=26, n_neighbors=20,cutoff=.03):
    # Protect the original dataframe
    df = df_input.copy()
    
    # 1. FIX: Globally replace Infinity with NaN 
    df = df.replace([np.inf, -np.inf], np.nan)

    # 2. Dynamically grab 'p' and Binarize the target
    p = target_col.split('_')[3][:2]
    if p == '85':
        df['target_class'] = (df[target_col] > cutoff).astype(int) 
    else:
        df['target_class'] = (df[target_col] < 0-cutoff).astype(int)
        
    features = joblib.load('features_giant_list_'+industry+'.pkl')
    
    # 3. Subsample to break autocorrelation
    offset = random.randint(0, stride - 1)
    sampled_df = df.iloc[offset::stride].dropna(subset=['target_class', target_col]).copy()
    
    total_sampled_rows = len(sampled_df)
    print(f"Original rows: {len(df)} | Subsampled Base Rows (Max possible): {total_sampled_rows}")
    
    results = []
    scaler = StandardScaler()
    
    # 4. Iterate feature-by-feature
    for col in features:
        if col not in sampled_df.columns:
            continue
            
        valid_df = sampled_df[[col, 'target_class']].dropna()
        valid_rows = len(valid_df)
        null_count = total_sampled_rows - valid_rows
        
        if valid_rows <= n_neighbors:
            mi_score = 0.0
        else:
            X = valid_df[[col]]
            y = valid_df['target_class']
            
            X_scaled = scaler.fit_transform(X)
            mi_score = mutual_info_classif(X_scaled, y, discrete_features=False, n_neighbors=n_neighbors)[0]
            
        results.append({
            'Feature': col,
            'MI_Score': mi_score,
            'Valid_Rows': valid_rows,
            'Null_Count': null_count
        })
        
    # 5. Format output
    true_mi_df = pd.DataFrame(results)#.set_index('Feature')

    # 6. Apply Ghost Baseline
    # We pass 'df' (which now has Infs removed and target_class built) to the ghost function
    ghost_effects = get_ghost_baseline(df, 'target_class', stride=stride, n_neighbors=n_neighbors)
    
    mean_ghost_effect = ghost_effects['shuffle_drop'].mean()
    true_mi_df['net_alpha'] = true_mi_df['MI_Score'] - mean_ghost_effect
    
    # Filter out features that don't beat the max 'lucky' ghost score
    max_ghost = ghost_effects['shuffle_drop'].max()
    valid_features = true_mi_df[true_mi_df['net_alpha'] > max_ghost]
    if len(valid_features)>243:
        valid_features=valid_features.head(243)
    valid_features=valid_features.sort_values(by='net_alpha', ascending=False)#.reset_index()
    return valid_features

def greedyGreta(df,target_col,n=40,t=.8,cutoff=.03):
    # t: Max correlation threshold
    # n: Max features to accept
    # 1. Get the list of features in order of importance
    valid_features=get_true_mi_scores(df,target_col,cutoff=cutoff)
    feature_list = valid_features.sort_values(by='net_alpha', ascending=False)['Feature'].tolist()
    print(feature_list[:5])
    # 2. Calculate the Spearman correlation matrix once
    print("Calculating correlation matrix...")
    corr_matrix = df[feature_list].corr(method='spearman').abs() # Note the .abs() !
    
    accepted_features = []
    remaining_features = feature_list.copy()
    
    print(f"Starting greedy reduction with t={t}, n={n}...")
    
    # 3. The Greedy Loop
    while remaining_features and len(accepted_features) < n:
        # Accept the highest net_alpha feature currently available
        top_var = remaining_features.pop(0)
        accepted_features.append(top_var)
        
        # Find correlations of this accepted feature with all others
        corrs = corr_matrix[top_var]
        #print(corrs)
        # Keep only features in the remaining pool that are below the threshold 't'
        remaining_features = [f for f in remaining_features if corrs[f] <= t]
    
    print(f"\nOptimization Complete!")
    print(f"Started with: {len(feature_list)} features")
    print(f"Accepted: {len(accepted_features)} features")
    return accepted_features

#jino = pd.read_csv('feature_presentation_' + industry + '.csv')
greedyGreta(jino,'change_lead_15_85th_ptile_YUMC')

Original rows: 12766 | Subsampled Base Rows (Max possible): 490
Calculating Noise Floor on 491 rows...
['skew_50_STKS', 'skew_50_BROS', 'volatility_50_SG', 'skew_25_TXRH', 'rolling_avg_vol_25_WEN']
Calculating correlation matrix...
Starting greedy reduction with t=0.8, n=40...

Optimization Complete!
Started with: 243 features
Accepted: 40 features

['skew_50_STKS',
 'skew_50_BROS',
 'volatility_50_SG',
 'skew_25_TXRH',
 'rolling_avg_vol_25_WEN',
 'volatility_50_EAT',
 'skew_50_SG',
 'volatility_50_SHAK',
 'skew_50_QSR',
 'rolling_avg_vol_50_STKS',
 'volatility_50_REBN',
 'volatility_50_HDL',
 'rolling_avg_vol_25_LOCO',
 'skew_50_THCH',
 'rolling_avg_vol_50_WING',
 'skew_50_BJRI',
 'skew_50_EAT',
 'skew_25_REBN',
 'rolling_avg_vol_50_YUMC',
 'volatility_50_RICK',
 'skew_50_RICK',
 'volatility_25_ARKR',
 'rolling_avg_vol_25_BH',
 'skew_25_BH',
 'skew_25_YUMC',
 'weekday_adj_vol_50_LOCO',
 'volatility_25_PETZ',
 'skew_50_SBUX',
 'bb_width_50_WING',
 'skew_50_GENK',
 'weekday_adj_vol_25_SHAK',
 'rolling_avg_vol_50_NDLS',
 'volatility_50_YUM',
 'weekday_adj_vol_50_CNNE',
 'change_lag_5050th_ptile_CHSN',
 'volatility_50_WING',
 'bb_width_50_THCH',
 'rolling_avg_vol_50_BTBD',
 'skew_25_ARKR',
 'skew_25_YUM']

In [50]:
print('rolling_avg_vol_50_timestamp' in jino.columns)

False

In [8]:
#MODEL TRAINING 1: DEFINE TIME METRICS FXN AND LOAD DATA TO SPLIT
import numpy as np
import pandas as pd

def get_temporal_metrics(y_true, y_pred, timestamps):
    """
    Calculates extended metrics including temporal variance of True Positives.
    timestamps: Must be a pandas Series of datetime objects corresponding to y_true/y_pred
    """
    # 1. Basic Counts
    total_rows = len(y_true)
    class_1_count = np.sum(y_true == 1)
    class_1_pct = (class_1_count / total_rows) * 100 if total_rows > 0 else 0
    
    # 2. Identify True Positives (TP)
    # Ensure inputs are aligned numpy arrays or pandas series
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    timestamps = np.array(timestamps)
    
    tp_mask = (y_true == 1) & (y_pred == 1)
    tp_timestamps = timestamps[tp_mask]
    
    # 3. Calculate Temporal Aggregates for TPs
    if len(tp_timestamps) > 1:
        # Convert to numeric (seconds) to calculate variance
        # Note: timestamps must be datetime64[ns]
        ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')
        
        # Variance (in Days Squared for readability)
        # 86400 seconds in a day
        var_seconds_sq = ts_numeric.var()
        var_days_sq = var_seconds_sq / (86400 ** 2)
        
        # Range (Duration between first and last TP)
        time_range = pd.to_datetime(tp_timestamps.max()) - pd.to_datetime(tp_timestamps.min())
        range_days = time_range.total_seconds() / 86400
        
        # Mean Time Distance (Average gap between consecutive TPs)
        # Sort first to measure gaps
        sorted_ts = np.sort(ts_numeric)
        avg_gap_hours = np.mean(np.diff(sorted_ts)) / 3600
        
    else:
        var_days_sq = 0
        range_days = 0
        avg_gap_hours = 0

    return {
        "total_test_rows": total_rows,
        "test_class1_pct": class_1_pct,
        "tp_var_days_sq": var_days_sq,
        "tp_range_days": range_days,
        "tp_avg_gap_hours": avg_gap_hours,
        "n_true_positives": len(tp_timestamps)
    }
# Load Data
try:
    df=pd.read_csv('feature_presentation_'+industry+'.csv')
except FileNotFoundError:
    #try:
        #df = pd.read_csv(f)
    #except FileNotFoundError:
    print(f"File not found for {s}. Skipping.")

In [9]:
import joblib
import os

# --- NEW: SAVE CHAMPION MODEL ---
# Create directory if it doesn't exist
MODEL_DIR = f"./models/{industry}/"
if not os.path.exists(MODEL_DIR):
    os.makedirs(MODEL_DIR)

In [9]:
[c for c in df.columns if '75' in c]
[c for c in jino.columns if 'change_lag' in c]

['change_lag_1010th_ptile_ARCO',
 'change_lag_1030th_ptile_ARCO',
 'change_lag_1050th_ptile_ARCO',
 'change_lag_1070th_ptile_ARCO',
 'change_lag_1090th_ptile_ARCO',
 'change_lag_2510th_ptile_ARCO',
 'change_lag_2530th_ptile_ARCO',
 'change_lag_2550th_ptile_ARCO',
 'change_lag_2570th_ptile_ARCO',
 'change_lag_2590th_ptile_ARCO',
 'change_lag_5010th_ptile_ARCO',
 'change_lag_5030th_ptile_ARCO',
 'change_lag_5050th_ptile_ARCO',
 'change_lag_5070th_ptile_ARCO',
 'change_lag_5090th_ptile_ARCO',
 'change_lag_10_50th_ptile_x_earn_prox_ARCO',
 'change_lag_1010th_ptile_ARKR',
 'change_lag_1030th_ptile_ARKR',
 'change_lag_1050th_ptile_ARKR',
 'change_lag_1070th_ptile_ARKR',
 'change_lag_1090th_ptile_ARKR',
 'change_lag_2510th_ptile_ARKR',
 'change_lag_2530th_ptile_ARKR',
 'change_lag_2550th_ptile_ARKR',
 'change_lag_2570th_ptile_ARKR',
 'change_lag_2590th_ptile_ARKR',
 'change_lag_5010th_ptile_ARKR',
 'change_lag_5030th_ptile_ARKR',
 'change_lag_5050th_ptile_ARKR',
 'change_lag_5070th_ptile_ARKR',
 'change_lag_5090th_ptile_ARKR',
 'change_lag_10_50th_ptile_x_earn_prox_ARKR',
 'change_lag_1010th_ptile_BH.A',
 'change_lag_1030th_ptile_BH.A',
 'change_lag_1050th_ptile_BH.A',
 'change_lag_1070th_ptile_BH.A',
 'change_lag_1090th_ptile_BH.A',
 'change_lag_2510th_ptile_BH.A',
 'change_lag_2530th_ptile_BH.A',
 'change_lag_2550th_ptile_BH.A',
 'change_lag_2570th_ptile_BH.A',
 'change_lag_2590th_ptile_BH.A',
 'change_lag_5010th_ptile_BH.A',
 'change_lag_5030th_ptile_BH.A',
 'change_lag_5050th_ptile_BH.A',
 'change_lag_5070th_ptile_BH.A',
 'change_lag_5090th_ptile_BH.A',
 'change_lag_10_50th_ptile_x_earn_prox_BH.A',
 'change_lag_1010th_ptile_BH',
 'change_lag_1030th_ptile_BH',
 'change_lag_1050th_ptile_BH',
 'change_lag_1070th_ptile_BH',
 'change_lag_1090th_ptile_BH',
 'change_lag_2510th_ptile_BH',
 'change_lag_2530th_ptile_BH',
 'change_lag_2550th_ptile_BH',
 'change_lag_2570th_ptile_BH',
 'change_lag_2590th_ptile_BH',
 'change_lag_5010th_ptile_BH',
 'change_lag_5030th_ptile_BH',
 'change_lag_5050th_ptile_BH',
 'change_lag_5070th_ptile_BH',
 'change_lag_5090th_ptile_BH',
 'change_lag_10_50th_ptile_x_earn_prox_BH',
 'change_lag_1010th_ptile_BJRI',
 'change_lag_1030th_ptile_BJRI',
 'change_lag_1050th_ptile_BJRI',
 'change_lag_1070th_ptile_BJRI',
 'change_lag_1090th_ptile_BJRI',
 'change_lag_2510th_ptile_BJRI',
 'change_lag_2530th_ptile_BJRI',
 'change_lag_2550th_ptile_BJRI',
 'change_lag_2570th_ptile_BJRI',
 'change_lag_2590th_ptile_BJRI',
 'change_lag_5010th_ptile_BJRI',
 'change_lag_5030th_ptile_BJRI',
 'change_lag_5050th_ptile_BJRI',
 'change_lag_5070th_ptile_BJRI',
 'change_lag_5090th_ptile_BJRI',
 'change_lag_10_50th_ptile_x_earn_prox_BJRI',
 'change_lag_1010th_ptile_BLMN',
 'change_lag_1030th_ptile_BLMN',
 'change_lag_1050th_ptile_BLMN',
 'change_lag_1070th_ptile_BLMN',
 'change_lag_1090th_ptile_BLMN',
 'change_lag_2510th_ptile_BLMN',
 'change_lag_2530th_ptile_BLMN',
 'change_lag_2550th_ptile_BLMN',
 'change_lag_2570th_ptile_BLMN',
 'change_lag_2590th_ptile_BLMN',
 'change_lag_5010th_ptile_BLMN',
 'change_lag_5030th_ptile_BLMN',
 'change_lag_5050th_ptile_BLMN',
 'change_lag_5070th_ptile_BLMN',
 'change_lag_5090th_ptile_BLMN',
 'change_lag_10_50th_ptile_x_earn_prox_BLMN',
 'change_lag_1010th_ptile_BROS',
 'change_lag_1030th_ptile_BROS',
 'change_lag_1050th_ptile_BROS',
 'change_lag_1070th_ptile_BROS',
 'change_lag_1090th_ptile_BROS',
 'change_lag_2510th_ptile_BROS',
 'change_lag_2530th_ptile_BROS',
 'change_lag_2550th_ptile_BROS',
 'change_lag_2570th_ptile_BROS',
 'change_lag_2590th_ptile_BROS',
 'change_lag_5010th_ptile_BROS',
 'change_lag_5030th_ptile_BROS',
 'change_lag_5050th_ptile_BROS',
 'change_lag_5070th_ptile_BROS',
 'change_lag_5090th_ptile_BROS',
 'change_lag_10_50th_ptile_x_earn_prox_BROS',
 'change_lag_1010th_ptile_BTBD',
 'change_lag_1030th_ptile_BTBD',
 'change_lag_1050th_ptile_BTBD',
 'change_lag_1070th_ptile_BTBD',
 'change_lag_1090th_ptile_BTBD',
 'change_lag_2510th_ptile_BTBD',
 'change_lag_2530th_ptile_BTBD',
 'change_lag_2550th_ptile_BTBD',
 'change_lag_2570th_ptile_BTBD',
 'change_lag_2590th_ptile_BTBD',
 'change_lag_5010th_ptile_BTBD',
 'change_lag_5030th_ptile_BTBD',
 'change_lag_5050th_ptile_BTBD',
 'change_lag_5070th_ptile_BTBD',
 'change_lag_5090th_ptile_BTBD',
 'change_lag_10_50th_ptile_x_earn_prox_BTBD',
 'change_lag_1010th_ptile_CAKE',
 'change_lag_1030th_ptile_CAKE',
 'change_lag_1050th_ptile_CAKE',
 'change_lag_1070th_ptile_CAKE',
 'change_lag_1090th_ptile_CAKE',
 'change_lag_2510th_ptile_CAKE',
 'change_lag_2530th_ptile_CAKE',
 'change_lag_2550th_ptile_CAKE',
 'change_lag_2570th_ptile_CAKE',
 'change_lag_2590th_ptile_CAKE',
 'change_lag_5010th_ptile_CAKE',
 'change_lag_5030th_ptile_CAKE',
 'change_lag_5050th_ptile_CAKE',
 'change_lag_5070th_ptile_CAKE',
 'change_lag_5090th_ptile_CAKE',
 'change_lag_10_50th_ptile_x_earn_prox_CAKE',
 'change_lag_1010th_ptile_CAVA',
 'change_lag_1030th_ptile_CAVA',
 'change_lag_1050th_ptile_CAVA',
 'change_lag_1070th_ptile_CAVA',
 'change_lag_1090th_ptile_CAVA',
 'change_lag_2510th_ptile_CAVA',
 'change_lag_2530th_ptile_CAVA',
 'change_lag_2550th_ptile_CAVA',
 'change_lag_2570th_ptile_CAVA',
 'change_lag_2590th_ptile_CAVA',
 'change_lag_5010th_ptile_CAVA',
 'change_lag_5030th_ptile_CAVA',
 'change_lag_5050th_ptile_CAVA',
 'change_lag_5070th_ptile_CAVA',
 'change_lag_5090th_ptile_CAVA',
 'change_lag_10_50th_ptile_x_earn_prox_CAVA',
 'change_lag_1010th_ptile_CBRL',
 'change_lag_1030th_ptile_CBRL',
 'change_lag_1050th_ptile_CBRL',
 'change_lag_1070th_ptile_CBRL',
 'change_lag_1090th_ptile_CBRL',
 'change_lag_2510th_ptile_CBRL',
 'change_lag_2530th_ptile_CBRL',
 'change_lag_2550th_ptile_CBRL',
 'change_lag_2570th_ptile_CBRL',
 'change_lag_2590th_ptile_CBRL',
 'change_lag_5010th_ptile_CBRL',
 'change_lag_5030th_ptile_CBRL',
 'change_lag_5050th_ptile_CBRL',
 'change_lag_5070th_ptile_CBRL',
 'change_lag_5090th_ptile_CBRL',
 'change_lag_10_50th_ptile_x_earn_prox_CBRL',
 'change_lag_1010th_ptile_CHSN',
 'change_lag_1030th_ptile_CHSN',
 'change_lag_1050th_ptile_CHSN',
 'change_lag_1070th_ptile_CHSN',
 'change_lag_1090th_ptile_CHSN',
 'change_lag_2510th_ptile_CHSN',
 'change_lag_2530th_ptile_CHSN',
 'change_lag_2550th_ptile_CHSN',
 'change_lag_2570th_ptile_CHSN',
 'change_lag_2590th_ptile_CHSN',
 'change_lag_5010th_ptile_CHSN',
 'change_lag_5030th_ptile_CHSN',
 'change_lag_5050th_ptile_CHSN',
 'change_lag_5070th_ptile_CHSN',
 'change_lag_5090th_ptile_CHSN',
 'change_lag_10_50th_ptile_x_earn_prox_CHSN',
 'change_lag_1010th_ptile_CMG',
 'change_lag_1030th_ptile_CMG',
 'change_lag_1050th_ptile_CMG',
 'change_lag_1070th_ptile_CMG',
 'change_lag_1090th_ptile_CMG',
 'change_lag_2510th_ptile_CMG',
 'change_lag_2530th_ptile_CMG',
 'change_lag_2550th_ptile_CMG',
 'change_lag_2570th_ptile_CMG',
 'change_lag_2590th_ptile_CMG',
 'change_lag_5010th_ptile_CMG',
 'change_lag_5030th_ptile_CMG',
 'change_lag_5050th_ptile_CMG',
 'change_lag_5070th_ptile_CMG',
 'change_lag_5090th_ptile_CMG',
 'change_lag_10_50th_ptile_x_earn_prox_CMG',
 'change_lag_1010th_ptile_CNNE',
 'change_lag_1030th_ptile_CNNE',
 'change_lag_1050th_ptile_CNNE',
 'change_lag_1070th_ptile_CNNE',
 'change_lag_1090th_ptile_CNNE',
 'change_lag_2510th_ptile_CNNE',
 'change_lag_2530th_ptile_CNNE',
 'change_lag_2550th_ptile_CNNE',
 'change_lag_2570th_ptile_CNNE',
 'change_lag_2590th_ptile_CNNE',
 'change_lag_5010th_ptile_CNNE',
 'change_lag_5030th_ptile_CNNE',
 'change_lag_5050th_ptile_CNNE',
 'change_lag_5070th_ptile_CNNE',
 'change_lag_5090th_ptile_CNNE',
 'change_lag_10_50th_ptile_x_earn_prox_CNNE',
 'change_lag_1010th_ptile_DENN',
 'change_lag_1030th_ptile_DENN',
 'change_lag_1050th_ptile_DENN',
 'change_lag_1070th_ptile_DENN',
 'change_lag_1090th_ptile_DENN',
 'change_lag_2510th_ptile_DENN',
 'change_lag_2530th_ptile_DENN',
 'change_lag_2550th_ptile_DENN',
 'change_lag_2570th_ptile_DENN',
 'change_lag_2590th_ptile_DENN',
 'change_lag_5010th_ptile_DENN',
 'change_lag_5030th_ptile_DENN',
 'change_lag_5050th_ptile_DENN',
 'change_lag_5070th_ptile_DENN',
 'change_lag_5090th_ptile_DENN',
 'change_lag_10_50th_ptile_x_earn_prox_DENN',
 'change_lag_1010th_ptile_DIN',
 'change_lag_1030th_ptile_DIN',
 'change_lag_1050th_ptile_DIN',
 'change_lag_1070th_ptile_DIN',
 'change_lag_1090th_ptile_DIN',
 'change_lag_2510th_ptile_DIN',
 'change_lag_2530th_ptile_DIN',
 'change_lag_2550th_ptile_DIN',
 'change_lag_2570th_ptile_DIN',
 'change_lag_2590th_ptile_DIN',
 'change_lag_5010th_ptile_DIN',
 'change_lag_5030th_ptile_DIN',
 'change_lag_5050th_ptile_DIN',
 'change_lag_5070th_ptile_DIN',
 'change_lag_5090th_ptile_DIN',
 'change_lag_10_50th_ptile_x_earn_prox_DIN',
 'change_lag_1010th_ptile_DPZ',
 'change_lag_1030th_ptile_DPZ',
 'change_lag_1050th_ptile_DPZ',
 'change_lag_1070th_ptile_DPZ',
 'change_lag_1090th_ptile_DPZ',
 'change_lag_2510th_ptile_DPZ',
 'change_lag_2530th_ptile_DPZ',
 'change_lag_2550th_ptile_DPZ',
 'change_lag_2570th_ptile_DPZ',
 'change_lag_2590th_ptile_DPZ',
 'change_lag_5010th_ptile_DPZ',
 'change_lag_5030th_ptile_DPZ',
 'change_lag_5050th_ptile_DPZ',
 'change_lag_5070th_ptile_DPZ',
 'change_lag_5090th_ptile_DPZ',
 'change_lag_10_50th_ptile_x_earn_prox_DPZ',
 'change_lag_1010th_ptile_DRI',
 'change_lag_1030th_ptile_DRI',
 'change_lag_1050th_ptile_DRI',
 'change_lag_1070th_ptile_DRI',
 'change_lag_1090th_ptile_DRI',
 'change_lag_2510th_ptile_DRI',
 'change_lag_2530th_ptile_DRI',
 'change_lag_2550th_ptile_DRI',
 'change_lag_2570th_ptile_DRI',
 'change_lag_2590th_ptile_DRI',
 'change_lag_5010th_ptile_DRI',
 'change_lag_5030th_ptile_DRI',
 'change_lag_5050th_ptile_DRI',
 'change_lag_5070th_ptile_DRI',
 'change_lag_5090th_ptile_DRI',
 'change_lag_10_50th_ptile_x_earn_prox_DRI',
 'change_lag_1010th_ptile_EAT',
 'change_lag_1030th_ptile_EAT',
 'change_lag_1050th_ptile_EAT',
 'change_lag_1070th_ptile_EAT',
 'change_lag_1090th_ptile_EAT',
 'change_lag_2510th_ptile_EAT',
 'change_lag_2530th_ptile_EAT',
 'change_lag_2550th_ptile_EAT',
 'change_lag_2570th_ptile_EAT',
 'change_lag_2590th_ptile_EAT',
 'change_lag_5010th_ptile_EAT',
 'change_lag_5030th_ptile_EAT',
 'change_lag_5050th_ptile_EAT',
 'change_lag_5070th_ptile_EAT',
 'change_lag_5090th_ptile_EAT',
 'change_lag_10_50th_ptile_x_earn_prox_EAT',
 'change_lag_1010th_ptile_FAT',
 'change_lag_1030th_ptile_FAT',
 'change_lag_1050th_ptile_FAT',
 'change_lag_1070th_ptile_FAT',
 'change_lag_1090th_ptile_FAT',
 'change_lag_2510th_ptile_FAT',
 'change_lag_2530th_ptile_FAT',
 'change_lag_2550th_ptile_FAT',
 'change_lag_2570th_ptile_FAT',
 'change_lag_2590th_ptile_FAT',
 'change_lag_5010th_ptile_FAT',
 'change_lag_5030th_ptile_FAT',
 'change_lag_5050th_ptile_FAT',
 'change_lag_5070th_ptile_FAT',
 'change_lag_5090th_ptile_FAT',
 'change_lag_10_50th_ptile_x_earn_prox_FAT',
 'change_lag_1010th_ptile_FATBB',
 'change_lag_1030th_ptile_FATBB',
 'change_lag_1050th_ptile_FATBB',
 'change_lag_1070th_ptile_FATBB',
 'change_lag_1090th_ptile_FATBB',
 'change_lag_2510th_ptile_FATBB',
 'change_lag_2530th_ptile_FATBB',
 'change_lag_2550th_ptile_FATBB',
 'change_lag_2570th_ptile_FATBB',
 'change_lag_2590th_ptile_FATBB',
 'change_lag_5010th_ptile_FATBB',
 'change_lag_5030th_ptile_FATBB',
 'change_lag_5050th_ptile_FATBB',
 'change_lag_5070th_ptile_FATBB',
 'change_lag_5090th_ptile_FATBB',
 'change_lag_10_50th_ptile_x_earn_prox_FATBB',
 'change_lag_1010th_ptile_FATBP',
 'change_lag_1030th_ptile_FATBP',
 'change_lag_1050th_ptile_FATBP',
 'change_lag_1070th_ptile_FATBP',
 'change_lag_1090th_ptile_FATBP',
 'change_lag_2510th_ptile_FATBP',
 'change_lag_2530th_ptile_FATBP',
 'change_lag_2550th_ptile_FATBP',
 'change_lag_2570th_ptile_FATBP',
 'change_lag_2590th_ptile_FATBP',
 'change_lag_5010th_ptile_FATBP',
 'change_lag_5030th_ptile_FATBP',
 'change_lag_5050th_ptile_FATBP',
 'change_lag_5070th_ptile_FATBP',
 'change_lag_5090th_ptile_FATBP',
 'change_lag_10_50th_ptile_x_earn_prox_FATBP',
 'change_lag_1010th_ptile_FATBW',
 'change_lag_1030th_ptile_FATBW',
 'change_lag_1050th_ptile_FATBW',
 'change_lag_1070th_ptile_FATBW',
 'change_lag_1090th_ptile_FATBW',
 'change_lag_2510th_ptile_FATBW',
 'change_lag_2530th_ptile_FATBW',
 'change_lag_2550th_ptile_FATBW',
 'change_lag_2570th_ptile_FATBW',
 'change_lag_2590th_ptile_FATBW',
 'change_lag_5010th_ptile_FATBW',
 'change_lag_5030th_ptile_FATBW',
 'change_lag_5050th_ptile_FATBW',
 'change_lag_5070th_ptile_FATBW',
 'change_lag_5090th_ptile_FATBW',
 'change_lag_10_50th_ptile_x_earn_prox_FATBW',
 'change_lag_1010th_ptile_FWRG',
 'change_lag_1030th_ptile_FWRG',
 'change_lag_1050th_ptile_FWRG',
 'change_lag_1070th_ptile_FWRG',
 'change_lag_1090th_ptile_FWRG',
 'change_lag_2510th_ptile_FWRG',
 'change_lag_2530th_ptile_FWRG',
 'change_lag_2550th_ptile_FWRG',
 'change_lag_2570th_ptile_FWRG',
 'change_lag_2590th_ptile_FWRG',
 'change_lag_5010th_ptile_FWRG',
 'change_lag_5030th_ptile_FWRG',
 'change_lag_5050th_ptile_FWRG',
 'change_lag_5070th_ptile_FWRG',
 'change_lag_5090th_ptile_FWRG',
 'change_lag_10_50th_ptile_x_earn_prox_FWRG',
 'change_lag_1010th_ptile_GENK',
 'change_lag_1030th_ptile_GENK',
 'change_lag_1050th_ptile_GENK',
 'change_lag_1070th_ptile_GENK',
 'change_lag_1090th_ptile_GENK',
 'change_lag_2510th_ptile_GENK',
 'change_lag_2530th_ptile_GENK',
 'change_lag_2550th_ptile_GENK',
 'change_lag_2570th_ptile_GENK',
 'change_lag_2590th_ptile_GENK',
 'change_lag_5010th_ptile_GENK',
 'change_lag_5030th_ptile_GENK',
 'change_lag_5050th_ptile_GENK',
 'change_lag_5070th_ptile_GENK',
 'change_lag_5090th_ptile_GENK',
 'change_lag_10_50th_ptile_x_earn_prox_GENK',
 'change_lag_1010th_ptile_GTIM',
 'change_lag_1030th_ptile_GTIM',
 'change_lag_1050th_ptile_GTIM',
 'change_lag_1070th_ptile_GTIM',
 'change_lag_1090th_ptile_GTIM',
 'change_lag_2510th_ptile_GTIM',
 'change_lag_2530th_ptile_GTIM',
 'change_lag_2550th_ptile_GTIM',
 'change_lag_2570th_ptile_GTIM',
 'change_lag_2590th_ptile_GTIM',
 'change_lag_5010th_ptile_GTIM',
 'change_lag_5030th_ptile_GTIM',
 'change_lag_5050th_ptile_GTIM',
 'change_lag_5070th_ptile_GTIM',
 'change_lag_5090th_ptile_GTIM',
 'change_lag_10_50th_ptile_x_earn_prox_GTIM',
 'change_lag_1010th_ptile_HDL',
 'change_lag_1030th_ptile_HDL',
 'change_lag_1050th_ptile_HDL',
 'change_lag_1070th_ptile_HDL',
 'change_lag_1090th_ptile_HDL',
 'change_lag_2510th_ptile_HDL',
 'change_lag_2530th_ptile_HDL',
 'change_lag_2550th_ptile_HDL',
 'change_lag_2570th_ptile_HDL',
 'change_lag_2590th_ptile_HDL',
 'change_lag_5010th_ptile_HDL',
 'change_lag_5030th_ptile_HDL',
 'change_lag_5050th_ptile_HDL',
 'change_lag_5070th_ptile_HDL',
 'change_lag_5090th_ptile_HDL',
 'change_lag_10_50th_ptile_x_earn_prox_HDL',
 'change_lag_1010th_ptile_JACK',
 'change_lag_1030th_ptile_JACK',
 'change_lag_1050th_ptile_JACK',
 'change_lag_1070th_ptile_JACK',
 'change_lag_1090th_ptile_JACK',
 'change_lag_2510th_ptile_JACK',
 'change_lag_2530th_ptile_JACK',
 'change_lag_2550th_ptile_JACK',
 'change_lag_2570th_ptile_JACK',
 'change_lag_2590th_ptile_JACK',
 'change_lag_5010th_ptile_JACK',
 'change_lag_5030th_ptile_JACK',
 'change_lag_5050th_ptile_JACK',
 'change_lag_5070th_ptile_JACK',
 'change_lag_5090th_ptile_JACK',
 'change_lag_10_50th_ptile_x_earn_prox_JACK',
 'change_lag_1010th_ptile_KRUS',
 'change_lag_1030th_ptile_KRUS',
 'change_lag_1050th_ptile_KRUS',
 'change_lag_1070th_ptile_KRUS',
 'change_lag_1090th_ptile_KRUS',
 'change_lag_2510th_ptile_KRUS',
 'change_lag_2530th_ptile_KRUS',
 'change_lag_2550th_ptile_KRUS',
 'change_lag_2570th_ptile_KRUS',
 'change_lag_2590th_ptile_KRUS',
 'change_lag_5010th_ptile_KRUS',
 'change_lag_5030th_ptile_KRUS',
 'change_lag_5050th_ptile_KRUS',
 'change_lag_5070th_ptile_KRUS',
 'change_lag_5090th_ptile_KRUS',
 'change_lag_10_50th_ptile_x_earn_prox_KRUS',
 'change_lag_1010th_ptile_LOCO',
 'change_lag_1030th_ptile_LOCO',
 'change_lag_1050th_ptile_LOCO',
 'change_lag_1070th_ptile_LOCO',
 'change_lag_1090th_ptile_LOCO',
 'change_lag_2510th_ptile_LOCO',
 'change_lag_2530th_ptile_LOCO',
 'change_lag_2550th_ptile_LOCO',
 'change_lag_2570th_ptile_LOCO',
 'change_lag_2590th_ptile_LOCO',
 'change_lag_5010th_ptile_LOCO',
 'change_lag_5030th_ptile_LOCO',
 'change_lag_5050th_ptile_LOCO',
 'change_lag_5070th_ptile_LOCO',
 'change_lag_5090th_ptile_LOCO',
 'change_lag_10_50th_ptile_x_earn_prox_LOCO',
 'change_lag_1010th_ptile_MCD',
 'change_lag_1030th_ptile_MCD',
 'change_lag_1050th_ptile_MCD',
 'change_lag_1070th_ptile_MCD',
 'change_lag_1090th_ptile_MCD',
 'change_lag_2510th_ptile_MCD',
 'change_lag_2530th_ptile_MCD',
 'change_lag_2550th_ptile_MCD',
 'change_lag_2570th_ptile_MCD',
 'change_lag_2590th_ptile_MCD',
 'change_lag_5010th_ptile_MCD',
 'change_lag_5030th_ptile_MCD',
 'change_lag_5050th_ptile_MCD',
 'change_lag_5070th_ptile_MCD',
 'change_lag_5090th_ptile_MCD',
 'change_lag_10_50th_ptile_x_earn_prox_MCD',
 'change_lag_1010th_ptile_NATH',
 'change_lag_1030th_ptile_NATH',
 'change_lag_1050th_ptile_NATH',
 'change_lag_1070th_ptile_NATH',
 'change_lag_1090th_ptile_NATH',
 'change_lag_2510th_ptile_NATH',
 'change_lag_2530th_ptile_NATH',
 'change_lag_2550th_ptile_NATH',
 'change_lag_2570th_ptile_NATH',
 'change_lag_2590th_ptile_NATH',
 'change_lag_5010th_ptile_NATH',
 'change_lag_5030th_ptile_NATH',
 'change_lag_5050th_ptile_NATH',
 'change_lag_5070th_ptile_NATH',
 'change_lag_5090th_ptile_NATH',
 'change_lag_10_50th_ptile_x_earn_prox_NATH',
 'change_lag_1010th_ptile_NDLS',
 'change_lag_1030th_ptile_NDLS',
 'change_lag_1050th_ptile_NDLS',
 'change_lag_1070th_ptile_NDLS',
 'change_lag_1090th_ptile_NDLS',
 'change_lag_2510th_ptile_NDLS',
 'change_lag_2530th_ptile_NDLS',
 'change_lag_2550th_ptile_NDLS',
 'change_lag_2570th_ptile_NDLS',
 'change_lag_2590th_ptile_NDLS',
 'change_lag_5010th_ptile_NDLS',
 'change_lag_5030th_ptile_NDLS',
 'change_lag_5050th_ptile_NDLS',
 'change_lag_5070th_ptile_NDLS',
 'change_lag_5090th_ptile_NDLS',
 'change_lag_10_50th_ptile_x_earn_prox_NDLS',
 'change_lag_1010th_ptile_PBPB',
 'change_lag_1030th_ptile_PBPB',
 'change_lag_1050th_ptile_PBPB',
 'change_lag_1070th_ptile_PBPB',
 'change_lag_1090th_ptile_PBPB',
 'change_lag_2510th_ptile_PBPB',
 'change_lag_2530th_ptile_PBPB',
 'change_lag_2550th_ptile_PBPB',
 'change_lag_2570th_ptile_PBPB',
 'change_lag_2590th_ptile_PBPB',
 'change_lag_5010th_ptile_PBPB',
 'change_lag_5030th_ptile_PBPB',
 'change_lag_5050th_ptile_PBPB',
 'change_lag_5070th_ptile_PBPB',
 'change_lag_5090th_ptile_PBPB',
 'change_lag_10_50th_ptile_x_earn_prox_PBPB',
 'change_lag_1010th_ptile_PETZ',
 'change_lag_1030th_ptile_PETZ',
 'change_lag_1050th_ptile_PETZ',
 'change_lag_1070th_ptile_PETZ',
 'change_lag_1090th_ptile_PETZ',
 'change_lag_2510th_ptile_PETZ',
 'change_lag_2530th_ptile_PETZ',
 'change_lag_2550th_ptile_PETZ',
 'change_lag_2570th_ptile_PETZ',
 'change_lag_2590th_ptile_PETZ',
 'change_lag_5010th_ptile_PETZ',
 'change_lag_5030th_ptile_PETZ',
 'change_lag_5050th_ptile_PETZ',
 'change_lag_5070th_ptile_PETZ',
 'change_lag_5090th_ptile_PETZ',
 'change_lag_10_50th_ptile_x_earn_prox_PETZ',
 'change_lag_1010th_ptile_PTLO',
 'change_lag_1030th_ptile_PTLO',
 'change_lag_1050th_ptile_PTLO',
 'change_lag_1070th_ptile_PTLO',
 'change_lag_1090th_ptile_PTLO',
 'change_lag_2510th_ptile_PTLO',
 'change_lag_2530th_ptile_PTLO',
 'change_lag_2550th_ptile_PTLO',
 'change_lag_2570th_ptile_PTLO',
 'change_lag_2590th_ptile_PTLO',
 'change_lag_5010th_ptile_PTLO',
 'change_lag_5030th_ptile_PTLO',
 'change_lag_5050th_ptile_PTLO',
 'change_lag_5070th_ptile_PTLO',
 'change_lag_5090th_ptile_PTLO',
 'change_lag_10_50th_ptile_x_earn_prox_PTLO',
 'change_lag_1010th_ptile_PZZA',
 'change_lag_1030th_ptile_PZZA',
 'change_lag_1050th_ptile_PZZA',
 'change_lag_1070th_ptile_PZZA',
 'change_lag_1090th_ptile_PZZA',
 'change_lag_2510th_ptile_PZZA',
 'change_lag_2530th_ptile_PZZA',
 'change_lag_2550th_ptile_PZZA',
 'change_lag_2570th_ptile_PZZA',
 'change_lag_2590th_ptile_PZZA',
 'change_lag_5010th_ptile_PZZA',
 'change_lag_5030th_ptile_PZZA',
 'change_lag_5050th_ptile_PZZA',
 'change_lag_5070th_ptile_PZZA',
 'change_lag_5090th_ptile_PZZA',
 'change_lag_10_50th_ptile_x_earn_prox_PZZA',
 'change_lag_1010th_ptile_QSR',
 'change_lag_1030th_ptile_QSR',

In [16]:
#MODEL TRAINING 2: THOMAS AND HIS FIENDS
# CLASS GRID GIANT PRUNING
import pandas as pd
import numpy as np
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report, precision_score, precision_recall_fscore_support,f1_score,fbeta_score
from itertools import product
import matplotlib.pyplot as plt
import seaborn as sns
import time
import os
import joblib

# Set style
plt.style.use('ggplot')

# -----------------------------------
all_results = []
num = 0
IMPORTANCE_THRESHOLD = 0.025 # Define the pruning threshold
mi_cutoff=.02

# 5. Define Parameter Grid
param_grid_values = {
    'n_estimators': [1000],
    'learning_rate': [0.01, 0.005],
    'max_depth': [3,2],         # Shallower trees often better for noisy finance data
    'min_samples_leaf': [75,50],       # Keep this high to avoid fitting to noise
    'subsample': [.75,1.0]         # 0.8 reduces variance (like Dropout in Neural Nets)
}
print('czech')
timestamp_col = 'timestamp'
df = df.sort_values(timestamp_col).reset_index(drop=True)
stocks=set([c.split('_')[-1] for c in df.columns if 'change_lead' in c])
train_count=0
symbols = [
    "BTBD", "TXRH", "BLMN", "PZZA", "GENK", 
    "PTLO", "WEN", "STKS", "DPZ", "QSR", 
    "BJRI", "NDLS", "SHAK", "DIN", "ARCO"
]
for s in symbols:
    if train_count>=28:
        break
    print(s)
    
    for p in ['15','85']:
        print(p)
        
        #if train_count>=15:
            #break
        save_path= f"{MODEL_DIR}champion_model_{s}_{p}.pkl"
        if os.path.exists(save_path):
            file_mtime = os.path.getmtime(save_path)
            current_time = time.time()
            age_in_seconds = current_time - file_mtime
            age_in_days = age_in_seconds / (24 * 3600)
            if age_in_days < 7:
                print(f"Existing model is only {age_in_days:.1f} days old. Skipping save.")
                continue
        train_count+=1
        start_time = time.time()
        skip = False
   
        if '.' in s or not s:
            continue
        
        print(f"\n================ Starting analysis for symbol: {s} ================")
        
        
        # NEW CODE (Uses the master timestamp)
         
        
        # Quick check to handle cases where it might be the index
        if timestamp_col not in df.columns and df.index.name == 'timestamp':
             df = df.reset_index()
             
        if timestamp_col not in df.columns:
            print(f"Master 'timestamp' column not found. Skipping {s}.")
            continue
        

        if not pd.api.types.is_datetime64_any_dtype(df[timestamp_col]):
            print(f"Converting {timestamp_col} to datetime...")
            df[timestamp_col] = pd.to_datetime(df[timestamp_col], utc=True)
        
        
        # 2. Set up Features and Targets
        # Wrapped in parentheses to allow multi-line list addition
        target_col_name = f'change_lead_15_{p}th_ptile_{s}'
        
        if target_col_name not in df.columns:
            print(f"Target column {target_col_name} not found. Skipping {s}.")
            continue
        
        # 3. Create Binary Target and Clean NaNs
        # model_df contains all features + timestamp + target, only non-NaN rows
        #model_df = df[feature_cols_all + [target_col_name]].copy()
        #model_df[feature_cols_all] = model_df[feature_cols_all].ffill() # Fill features
            
        base_df = df.dropna(subset=[target_col_name]).copy()
        # Calculate baseline boundaries
        total_base = len(base_df)
        rows_per_day = 26  
        max_lead_days = 15  
        buffer_rows = max_lead_days * rows_per_day
        
        test_size_base = int(total_base * 0.2)
        val_size_base = int(total_base * 0.2)
        
        idx_test_start_base = total_base - test_size_base - buffer_rows
        idx_val_end_base = idx_test_start_base - buffer_rows
        idx_val_start_base = idx_val_end_base - val_size_base
        idx_train_end_base = idx_val_start_base - buffer_rows

        # 🔥 NEW: Freeze the exact boundary DATES
        train_end_date = base_df.iloc[idx_train_end_base][timestamp_col]
        val_start_date = base_df.iloc[idx_val_start_base][timestamp_col]
        val_end_date = base_df.iloc[idx_val_end_base][timestamp_col]
        test_start_date = base_df.iloc[idx_test_start_base][timestamp_col]

        print(f"Train End Date:   {train_end_date}")
        print(f"Val Start Date:   {val_start_date}")
        print(f"Val End Date:     {val_end_date}")
        print(f"Test Start Date:  {test_start_date}")
        
        # ==========================================
        # PASS 2: FEATURE SELECTION ON TRAIN ONLY
        # ==========================================
        # Slice the data up to the train boundary. Greta NEVER sees val/test data.
        train_pool_df = base_df[base_df[timestamp_col] <= train_end_date].copy()
        
        print(f"Running Greta on strictly historical training slice: {len(train_pool_df)} rows...")
        initial_features = greedyGreta(train_pool_df, target_col_name,cutoff=mi_cutoff)
        if len(initial_features) == 0:
            print(f"Greta found 0 features above noise floor. Skipping {s}_{p}.")
            continue
        feature_cols_all = initial_features + [timestamp_col]
    
        # ==========================================
        # PASS 3: ASSEMBLE AND CLEAN
        # ==========================================
        # Now we bring in the full timeline, but ONLY with the selected features
        model_df = df[feature_cols_all + [target_col_name]].copy()
    
        # 🔥 THE FIX: Convert all infinities to NaNs so our gauntlet can catch them
        model_df.replace([np.inf, -np.inf], np.nan, inplace=True)
        # You can set this to an absolute number (e.g., 1000) or a percentage of total df
        MIN_REQUIRED_ROWS = int(len(df) * 0.4) # Example: demand 60% of original timeline survives
        
        print(f"Starting NaN pruning. Target minimum rows: {MIN_REQUIRED_ROWS}")
        
        while True:
            # Check what happens if we drop NaNs right now
            temp_clean_df = model_df.dropna()
            surviving_rows = len(temp_clean_df)
            
            if surviving_rows >= MIN_REQUIRED_ROWS:
                # We have enough data! Lock it in.
                model_df = temp_clean_df
                initial_len = len(df) # for your print statements
                final_len = surviving_rows
                print(f"Data Points: {initial_len} -> {final_len} (Adequate rows secured!)")
                break
                
            # If we drop down to too few features, this symbol is a lost cause
            if len(initial_features) < 5:  # Set your absolute minimum feature count
                print(f"❌ Pruned down to <5 features trying to fix NaNs. Abandoning {s}_{p}.")
                skip = True
                break
                
            # Find the worst offender: Which remaining feature has the most NaNs?
            nan_counts = model_df[initial_features].isna().sum()
            worst_feature = nan_counts.idxmax()
            worst_feature_nans = nan_counts.max()
            
            print(f"  -> Only {surviving_rows} rows survived. Dropping worst NaN contributor: '{worst_feature}' ({worst_feature_nans} NaNs)")
            
            # Remove the worst feature from our tracking lists and the dataframe
            initial_features.remove(worst_feature)
            feature_cols_all.remove(worst_feature)
            model_df = model_df.drop(columns=[worst_feature])

        # If the gauntlet caused us to skip, break out to the next loop iteration
        if skip:
            continue
        # Binarize the final target
        if p == '85':
            model_df['target_class'] = (model_df[target_col_name] > mi_cutoff).astype(int) 
        else:
            model_df['target_class'] = (model_df[target_col_name] < 0-mi_cutoff).astype(int)

        initial_len = len(model_df)
        # Drop rows where ANY of our top 40 features (or target) are NaN
        model_df = model_df.dropna()
        final_len = len(model_df)
        
        print(f"Data Points: {initial_len} -> {final_len} (Dropped {initial_len - final_len} rows due to NaN features)")
        
        if final_len < 1000:
            print(f"Not enough data points ({final_len}) after cleanup. Skipping {s}.")
            continue
        model_df[feature_cols_all] = model_df[feature_cols_all].ffill() 
          
        # Check Class Balance
        pos_count = model_df['target_class'].sum()
        if pos_count < 50:
            print(f"❌ Insufficient positive targets ({pos_count}). Skipping {s}.")
            continue
        # ==========================================
        # PASS 4: THE FINAL SPLIT
        # ==========================================
        # Because we dropped NaNs (mostly at the very beginning of the dataset 
        # due to rolling windows), we must recalculate the exact row indices.
        total_rows = len(model_df)
        test_size = int(total_rows * 0.2)
        val_size = int(total_rows * 0.2)
        
        
        # Now you can safely slice your final training sets!
        train_df = model_df[model_df[timestamp_col] <= train_end_date]
        val_df = model_df[(model_df[timestamp_col] >= val_start_date) & 
                          (model_df[timestamp_col] <= val_end_date)]               
        test_df = model_df[model_df[timestamp_col] >= test_start_date]

        print('train rows: ',len(train_df))
        print('val rows: ',len(val_df))
        print('test rows: ',len(test_df))
        # Initial X/y split (still contains ALL possible features + timestamp)
        X_pool = model_df[feature_cols_all]
        y_pool = model_df['target_class']
        
        # ---------------------------------------------------------
        # === RECURSIVE FEATURE PRUNING LOOP ===
        # ---------------------------------------------------------
        #print('after splitting')

        current_features = initial_features.copy()
        temp_clf = None 
        best_params = {}
        
        # --- NEW: Track the "Champion" (Best Parsimonious) Set ---
        champion_features = current_features.copy()
        champion_params = {}
        champion_score = -1.0   # The score of the current champion
        global_max_score = -1.0 # The absolute best score seen (to calculate the 0.01 drop)
        # --------------------------------------------------------
        
        iteration = 0
        print('before while true')
        while True:
            iteration += 1
            
            # 4b. Slice data based on CURRENT features
            current_cols = current_features + [timestamp_col]
            X = X_pool[current_cols]
            y = y_pool
            
            X_train = train_df[current_cols]
            y_train = train_df['target_class']
            X_val = val_df[current_cols]
            y_val = val_df['target_class']
            print(len(X_val))
            X_train_clean = X_train.drop(columns=[timestamp_col])
            X_val_clean = X_val.drop(columns=[timestamp_col])
            
            if len(X_train_clean) <= 0 or len(X_val_clean) <= 0 or len(X_train_clean.columns) <= 0:
                print('train clean: ',len(X_train_clean))
                print('val clean: ',len(X_val_clean))
                print('train clean cols: ',len(X_train_clean.columns))
                print('train cols: ',len(X_train.columns))
                print("ERROR: Training or Validation set is empty after slicing. Breaking.")
                skip = True
                break
            
            # 6. Grid Search (Re-run for current feature set)
            iter_best_score = -1
            iter_best_params = {}
            
            keys, values = zip(*param_grid_values.items())
            print('before val loop')
            for v in product(*values):
                params = dict(zip(keys, v))
                clf = GradientBoostingClassifier(random_state=42, **params)
                clf.fit(X_train_clean, y_train)
                #print('after clf fit')
                preds_val = clf.predict(X_val_clean)
                #print('after clf val predict')
                # Calculate score for this specific param combo
                current_score = fbeta_score(y_val, preds_val, beta=0.5, pos_label=1, zero_division=0)
               
                if current_score > iter_best_score:
                    iter_best_score = current_score
                    iter_best_params = params
            
            print(f"Iteration {iteration}: Features={len(current_features)} | Best Val Score={iter_best_score:.4f}")
            
            # --- NEW: Check if this feature set is the new "Champion" ---
            # Update the Global Max Score if this iteration beat everything before it
            if iter_best_score > global_max_score:
                global_max_score = iter_best_score
            
            # Parsimony Logic: 
            # We accept this new set if the score hasn't dropped by more than 0.01 compared 
            # to the absolute best score seen so far.
            if iter_best_score >= (global_max_score - 0.01):
                champion_features = current_features.copy()
                champion_params = iter_best_params
                champion_score = iter_best_score
                print(f"   >>> New Champion Selected! (Score: {iter_best_score:.4f} is within 0.01 of Max {global_max_score:.4f})")
            else:
                print(f"   >>> Score drop > 0.01 (Val: {iter_best_score:.4f} vs Max: {global_max_score:.4f}). Keeping previous Champion.")
            # ------------------------------------------------------------
            
            # 7. Train Model for Importance Check (using Train+Val)
            X_train_final = pd.concat([X_train_clean, X_val_clean])
            y_train_final = pd.concat([y_train, y_val])
            
            # We use the params found in THIS iteration to determine importances for pruning
            temp_clf = GradientBoostingClassifier(random_state=42, **iter_best_params)
            temp_clf.fit(X_train_final, y_train_final)
            
            # 8. Check and Prune Features
            importances = temp_clf.feature_importances_
            
            next_features = [
                feat for feat, imp in zip(current_features, importances)
                if imp >= IMPORTANCE_THRESHOLD
            ]
            
            # --- Convergence and Safeguard Checks ---
            if set(next_features) == set(current_features):
                print(f"Iteration {iteration}: Converged (No features dropped).")
                break
               
            if len(next_features) == 0:
                 print(f"Iteration {iteration}: All features below threshold. Breaking.")
                 break
                 
            if iteration > 5:
                print(f"Iteration {iteration}: Max iterations reached.")
                break
            
            print(f"Iteration {iteration}: Pruning {len(current_features) - len(next_features)} features.")
            current_features = next_features
            
        
        if skip == False:
        # ---------------------------------------------------------
        # === RESTORE CHAMPION SET ===
        # ---------------------------------------------------------
            print(f"\nPruning Complete. Reverting to Champion Feature Set (Size: {len(champion_features)}) with Score: {champion_score:.4f}")
            current_features = champion_features
            best_params = champion_params
        
            # Retrain Final Model on the Champion Features + Champion Params
            X_train_final_pool = pd.concat([train_df[current_features], val_df[current_features]])
            y_train_final_pool = pd.concat([train_df['target_class'], val_df['target_class']])
            
            # (No need to drop timestamp because you only selected current_features above!)
            final_clf = GradientBoostingClassifier(random_state=42, **best_params)
            final_clf.fit(X_train_final_pool, y_train_final_pool)
            
            print(f"\nGrid Search & Selection Complete. Best Parameters: {best_params}")
            
            # 8. Final Evaluation on Hold-out Test Set
            # Slice the test set using the FINAL 'current_features' (which is now the Champion set)
            X_test_clean = test_df[current_features]
            y_test = test_df['target_class']
            
            preds_test = final_clf.predict(X_test_clean)
            
            print(f"\n--- Final Test Set Evaluation for {s} ---")
            print(classification_report(y_test, preds_test, zero_division=0))
            
            # 9. Extract and Store Results
            prec, r, f1, support = precision_recall_fscore_support(y_test, preds_test, average=None, zero_division=0)
            f_beta_05=fbeta_score(y_test, preds_test, beta=0.5, pos_label=1, zero_division=0)
            try:
                class_1_precision = prec[1]
                class_1_recall = r[1]
                class_1_f1 = f1[1]
            except:
                class_1_precision = 0.0
                class_1_recall = 0.0
                class_1_f1 = 0.0
                print('no class 1')
                #continue
            
            # NOTE: Ensure get_temporal_metrics is defined in your environment
            try:
                timestamps = test_df[timestamp_col] 
                metrics = get_temporal_metrics(y_test, preds_test, timestamps)
            except NameError:
                metrics = {}
                print("Warning: get_temporal_metrics function not found.")
            
            # 10. Feature Importance (Using the final feature set and model)
            importance_df = pd.DataFrame({
                'Feature': current_features, 
                'Importance': final_clf.feature_importances_
            }).sort_values('Importance', ascending=False)
        
            top_importance_df = importance_df[importance_df['Importance'] > 0.05]
            top_importance_dict = top_importance_df.set_index('Feature')['Importance'].to_dict()
            
            print("\nTop 10 Feature Importances (Final Tuned Model):")
            print(importance_df.head(10).to_markdown(index=False))
            
            result_entry = {
                'Symbol': s,
                'ptile':p,
                'Final_Feature_Count': len(current_features),
                'Best_Params': str(best_params),
                'Test_Precision_Class1': class_1_precision,
                'Test_Recall_Class1': class_1_recall,
                'Test_F1_Class1': class_1_f1,
                'Test_Fbeta_0.5': f_beta_05,
                'Top_Feature_Importances': top_importance_dict
            }
            result_entry = {**result_entry, **metrics}
            
            all_results.append(result_entry)
    
            # Bundle the model and the specific features used
            model_data = {
                'model': final_clf,
                'features': current_features,  # These are the champion features
                'params': best_params,
                'symbol': s,
                'side': p,  # '15' for downside, '85' for upside
                'trained_at': pd.Timestamp.now().strftime('%Y-%m-%d %H:%M')
            }
            
            # Save the file
            if class_1_precision>0:
                print(f"No existing model found for {s}_{p}. Saving...")
                joblib.dump(model_data, save_path, compress=3)
                print(f"✅ Model saved to: {save_path}")
            else:
                print('precision_class_1=0. Skippity doo-dah')
        else:
            print(f"⏭️ Skipping final fit and save for {s}_{p} due to earlier errors.")

# --- LOOP END: CONSOLIDATE RESULTS ---
results_df = pd.DataFrame(all_results)
print("\n================== CONSOLIDATED RESULTS ==================")
print(results_df.to_markdown(index=False))

czech
BTBD
15

================ Starting analysis for symbol: BTBD ================
Train End Date:   2025-04-22 11:15:00+00:00
Val Start Date:   2025-05-13 11:15:00+00:00
Val End Date:     2025-10-02 11:45:00+00:00
Test Start Date:  2025-10-23 11:45:00+00:00
Running Greta on strictly historical training slice: 6482 rows...
Original rows: 6482 | Subsampled Base Rows (Max possible): 249
Calculating Noise Floor on 249 rows...
['volatility_50_PTLO', 'weekday_adj_vol_50_PTLO', 'change_lag_5070th_ptile_BH', 'rolling_avg_vol_25_SBUX', 'weekday_adj_vol_10_MCD']
Calculating correlation matrix...
Starting greedy reduction with t=0.8, n=40...

Optimization Complete!
Started with: 243 features
Accepted: 40 features
Starting NaN pruning. Target minimum rows: 5106
Data Points: 12766 -> 11451 (Adequate rows secured!)
Data Points: 11451 -> 11451 (Dropped 0 rows due to NaN features)
train rows:  5182
val rows:  2551
test rows:  2940
before while true
2551
before val loop
Iteration 1: Features=40 | Best Val Score=0.6654
   >>> New Champion Selected! (Score: 0.6654 is within 0.01 of Max 0.6654)
Iteration 1: Pruning 27 features.
2551
before val loop
Iteration 2: Features=13 | Best Val Score=0.6840
   >>> New Champion Selected! (Score: 0.6840 is within 0.01 of Max 0.6840)
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 13) with Score: 0.6840

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 3, 'min_samples_leaf': 75, 'subsample': 1.0}

--- Final Test Set Evaluation for BTBD ---
              precision    recall  f1-score   support

           0       0.39      0.53      0.45      1046
           1       0.67      0.53      0.59      1894

    accuracy                           0.53      2940
   macro avg       0.53      0.53      0.52      2940
weighted avg       0.57      0.53      0.54      2940


Top 10 Feature Importances (Final Tuned Model):
| Feature                      |   Importance |
|:-----------------------------|-------------:|
| change_lag_1090th_ptile_BTBD |    0.19602   |
| weekday_adj_vol_10_MCD       |    0.120004  |
| rolling_avg_vol_25_THCH      |    0.0971823 |
| skew_10_CMG                  |    0.0817743 |
| volatility_10_RICK           |    0.0779112 |
| volatility_50_PTLO           |    0.0736962 |
| rolling_avg_vol_25_SBUX      |    0.0694659 |
| volatility_25_KRUS           |    0.0612452 |
| weekday_adj_vol_10_CMG       |    0.0515256 |
| bb_width_25_DIN              |    0.0480573 |
No existing model found for BTBD_15. Saving...

C:\Users\allth\AppData\Local\Temp\ipykernel_56232\2445029629.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

✅ Model saved to: ./models/restaurants/champion_model_BTBD_15.pkl
85

================ Starting analysis for symbol: BTBD ================
Train End Date:   2025-04-22 11:15:00+00:00
Val Start Date:   2025-05-13 11:15:00+00:00
Val End Date:     2025-10-02 11:45:00+00:00
Test Start Date:  2025-10-23 11:45:00+00:00
Running Greta on strictly historical training slice: 6482 rows...
Original rows: 6482 | Subsampled Base Rows (Max possible): 249
Calculating Noise Floor on 249 rows...
['skew_50_BROS', 'volatility_25_BJRI', 'weekday_adj_vol_25_RICK', 'skew_50_YUM', 'skew_25_JACK']
Calculating correlation matrix...
Starting greedy reduction with t=0.8, n=40...

Optimization Complete!
Started with: 243 features
Accepted: 40 features
Starting NaN pruning. Target minimum rows: 5106
Data Points: 12766 -> 12241 (Adequate rows secured!)
Data Points: 12241 -> 12241 (Dropped 0 rows due to NaN features)
train rows:  5972
val rows:  2551
test rows:  2940
before while true
2551
before val loop
Iteration 1: Features=40 | Best Val Score=0.6150
   >>> New Champion Selected! (Score: 0.6150 is within 0.01 of Max 0.6150)
Iteration 1: Pruning 28 features.
2551
before val loop
Iteration 2: Features=12 | Best Val Score=0.6873
   >>> New Champion Selected! (Score: 0.6873 is within 0.01 of Max 0.6873)
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 12) with Score: 0.6873

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 3, 'min_samples_leaf': 50, 'subsample': 0.75}

--- Final Test Set Evaluation for BTBD ---
              precision    recall  f1-score   support

           0       0.29      0.66      0.40      1035
           1       0.38      0.11      0.17      1905

    accuracy                           0.31      2940
   macro avg       0.33      0.39      0.29      2940
weighted avg       0.35      0.31      0.25      2940


Top 10 Feature Importances (Final Tuned Model):
| Feature                 |   Importance |
|:------------------------|-------------:|
| volatility_25_MCD       |    0.16297   |
| skew_25_JACK            |    0.133864  |
| bb_width_50_BH          |    0.107616  |
| weekday_adj_vol_10_DPZ  |    0.0960074 |
| skew_50_YUM             |    0.0921542 |
| rolling_avg_vol_25_RICK |    0.0772932 |
| volatility_50_PZZA      |    0.0649326 |
| bb_width_25_CBRL        |    0.0584345 |
| rolling_avg_vol_25_BH   |    0.0549965 |
| rolling_avg_vol_25_SHAK |    0.0531816 |
No existing model found for BTBD_85. Saving...

C:\Users\allth\AppData\Local\Temp\ipykernel_56232\2445029629.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

✅ Model saved to: ./models/restaurants/champion_model_BTBD_85.pkl
TXRH
15

================ Starting analysis for symbol: TXRH ================
Train End Date:   2025-04-22 11:15:00+00:00
Val Start Date:   2025-05-13 11:15:00+00:00
Val End Date:     2025-10-02 11:45:00+00:00
Test Start Date:  2025-10-23 11:45:00+00:00
Running Greta on strictly historical training slice: 6482 rows...
Original rows: 6482 | Subsampled Base Rows (Max possible): 249
Calculating Noise Floor on 249 rows...
['skew_10_RRGB', 'bb_width_25_PETZ', 'volatility_10_RICK', 'skew_50_PETZ', 'weekday_adj_vol_10_RICK']
Calculating correlation matrix...
Starting greedy reduction with t=0.8, n=40...

Optimization Complete!
Started with: 243 features
Accepted: 40 features
Starting NaN pruning. Target minimum rows: 5106
Data Points: 12766 -> 12242 (Adequate rows secured!)
Data Points: 12242 -> 12242 (Dropped 0 rows due to NaN features)
train rows:  5973
val rows:  2551
test rows:  2940
before while true
2551
before val loop
Iteration 1: Features=40 | Best Val Score=0.7849
   >>> New Champion Selected! (Score: 0.7849 is within 0.01 of Max 0.7849)
Iteration 1: Pruning 30 features.
2551
before val loop
Iteration 2: Features=10 | Best Val Score=0.8756
   >>> New Champion Selected! (Score: 0.8756 is within 0.01 of Max 0.8756)
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 10) with Score: 0.8756

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 1000, 'learning_rate': 0.005, 'max_depth': 3, 'min_samples_leaf': 75, 'subsample': 1.0}

--- Final Test Set Evaluation for TXRH ---
              precision    recall  f1-score   support

           0       0.74      0.30      0.42      1263
           1       0.64      0.92      0.75      1677

    accuracy                           0.65      2940
   macro avg       0.69      0.61      0.59      2940
weighted avg       0.68      0.65      0.61      2940


Top 10 Feature Importances (Final Tuned Model):
| Feature                     |   Importance |
|:----------------------------|-------------:|
| bb_width_25_CNNE            |    0.219898  |
| volatility_10_RICK          |    0.204716  |
| bb_width_25_RAVE            |    0.099322  |
| weekday_adj_vol_25_CAVA     |    0.0889299 |
| change_lag_2590th_ptile_DRI |    0.0829804 |
| bb_width_50_CAVA            |    0.0823589 |
| skew_50_PETZ                |    0.0739311 |
| rolling_avg_vol_50_THCH     |    0.0712427 |
| volatility_50_BJRI          |    0.0396837 |
| bb_width_25_BH              |    0.0369371 |
No existing model found for TXRH_15. Saving...

C:\Users\allth\AppData\Local\Temp\ipykernel_56232\2445029629.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

✅ Model saved to: ./models/restaurants/champion_model_TXRH_15.pkl
85

================ Starting analysis for symbol: TXRH ================
Train End Date:   2025-04-22 11:15:00+00:00
Val Start Date:   2025-05-13 11:15:00+00:00
Val End Date:     2025-10-02 11:45:00+00:00
Test Start Date:  2025-10-23 11:45:00+00:00
Running Greta on strictly historical training slice: 6482 rows...
Original rows: 6482 | Subsampled Base Rows (Max possible): 249
Calculating Noise Floor on 249 rows...
['bb_width_50_BH', 'skew_50_GENK', 'bb_width_50_HDL', 'skew_50_HDL', 'bb_width_50_BH.A']
Calculating correlation matrix...
Starting greedy reduction with t=0.8, n=40...

Optimization Complete!
Started with: 243 features
Accepted: 40 features
Starting NaN pruning. Target minimum rows: 5106
Data Points: 12766 -> 12241 (Adequate rows secured!)
Data Points: 12241 -> 12241 (Dropped 0 rows due to NaN features)
train rows:  5972
val rows:  2551
test rows:  2940
before while true
2551
before val loop
Iteration 1: Features=40 | Best Val Score=0.3107
   >>> New Champion Selected! (Score: 0.3107 is within 0.01 of Max 0.3107)
Iteration 1: Pruning 32 features.
2551
before val loop
Iteration 2: Features=8 | Best Val Score=0.4687
   >>> New Champion Selected! (Score: 0.4687 is within 0.01 of Max 0.4687)
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 8) with Score: 0.4687

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 1000, 'learning_rate': 0.005, 'max_depth': 3, 'min_samples_leaf': 75, 'subsample': 1.0}

--- Final Test Set Evaluation for TXRH ---
              precision    recall  f1-score   support

           0       0.58      0.99      0.73      1611
           1       0.94      0.11      0.20      1329

    accuracy                           0.60      2940
   macro avg       0.76      0.55      0.47      2940
weighted avg       0.74      0.60      0.49      2940


Top 10 Feature Importances (Final Tuned Model):
| Feature                      |   Importance |
|:-----------------------------|-------------:|
| bb_width_50_PZZA             |    0.22204   |
| weekday_adj_vol_50_YUM       |    0.160519  |
| skew_25_MCD                  |    0.156965  |
| z_score_50_TXRH              |    0.156799  |
| change_lag_5090th_ptile_GENK |    0.101155  |
| weekday_adj_vol_25_WING      |    0.081178  |
| weekday_adj_vol_50_CBRL      |    0.0634159 |
| bb_width_25_CNNE             |    0.0579282 |
No existing model found for TXRH_85. Saving...

C:\Users\allth\AppData\Local\Temp\ipykernel_56232\2445029629.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

✅ Model saved to: ./models/restaurants/champion_model_TXRH_85.pkl
BLMN
15

================ Starting analysis for symbol: BLMN ================
Train End Date:   2025-04-22 11:15:00+00:00
Val Start Date:   2025-05-13 11:15:00+00:00
Val End Date:     2025-10-02 11:45:00+00:00
Test Start Date:  2025-10-23 11:45:00+00:00
Running Greta on strictly historical training slice: 6482 rows...
Original rows: 6482 | Subsampled Base Rows (Max possible): 250
Calculating Noise Floor on 249 rows...
['efficiency_ratio_50_BLMN', 'bb_width_50_EAT', 'rolling_avg_vol_50_CMG', 'bb_width_50_DPZ', 'change_lag_5030th_ptile_DIN']
Calculating correlation matrix...
Starting greedy reduction with t=0.8, n=40...

Optimization Complete!
Started with: 243 features
Accepted: 40 features
Starting NaN pruning. Target minimum rows: 5106
Data Points: 12766 -> 11451 (Adequate rows secured!)
Data Points: 11451 -> 11451 (Dropped 0 rows due to NaN features)
train rows:  5182
val rows:  2551
test rows:  2940
before while true
2551
before val loop
Iteration 1: Features=40 | Best Val Score=0.7099
   >>> New Champion Selected! (Score: 0.7099 is within 0.01 of Max 0.7099)
Iteration 1: Pruning 29 features.
2551
before val loop
Iteration 2: Features=11 | Best Val Score=0.6851
   >>> Score drop > 0.01 (Val: 0.6851 vs Max: 0.7099). Keeping previous Champion.
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 40) with Score: 0.7099

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 1000, 'learning_rate': 0.005, 'max_depth': 2, 'min_samples_leaf': 50, 'subsample': 0.75}

--- Final Test Set Evaluation for BLMN ---
              precision    recall  f1-score   support

           0       0.90      0.15      0.26       873
           1       0.73      0.99      0.84      2067

    accuracy                           0.74      2940
   macro avg       0.82      0.57      0.55      2940
weighted avg       0.78      0.74      0.67      2940


Top 10 Feature Importances (Final Tuned Model):
| Feature                      |   Importance |
|:-----------------------------|-------------:|
| efficiency_ratio_50_BLMN     |    0.243211  |
| bb_width_50_SG               |    0.179721  |
| weekday_adj_vol_50_PTLO      |    0.0997681 |
| change_lag_5030th_ptile_DIN  |    0.0910716 |
| change_lag_1090th_ptile_DIN  |    0.060579  |
| rolling_avg_vol_50_CMG       |    0.042951  |
| bb_width_50_EAT              |    0.0332175 |
| change_lag_2550th_ptile_RRGB |    0.0322938 |
| change_lag_5070th_ptile_JACK |    0.0299315 |
| skew_25_JACK                 |    0.028068  |
No existing model found for BLMN_15. Saving...

C:\Users\allth\AppData\Local\Temp\ipykernel_56232\2445029629.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

✅ Model saved to: ./models/restaurants/champion_model_BLMN_15.pkl
85

================ Starting analysis for symbol: BLMN ================
Train End Date:   2025-04-22 11:15:00+00:00
Val Start Date:   2025-05-13 11:15:00+00:00
Val End Date:     2025-10-02 11:45:00+00:00
Test Start Date:  2025-10-23 11:45:00+00:00
Running Greta on strictly historical training slice: 6482 rows...
Original rows: 6482 | Subsampled Base Rows (Max possible): 249
Calculating Noise Floor on 249 rows...
['efficiency_ratio_50_BLMN', 'rolling_avg_vol_50_CMG', 'skew_50_DPZ', 'rolling_avg_vol_25_NATH', 'bb_width_50_SG']
Calculating correlation matrix...
Starting greedy reduction with t=0.8, n=40...

Optimization Complete!
Started with: 243 features
Accepted: 40 features
Starting NaN pruning. Target minimum rows: 5106
Data Points: 12766 -> 11451 (Adequate rows secured!)
Data Points: 11451 -> 11451 (Dropped 0 rows due to NaN features)
train rows:  5182
val rows:  2551
test rows:  2940
before while true
2551
before val loop
Iteration 1: Features=40 | Best Val Score=0.5419
   >>> New Champion Selected! (Score: 0.5419 is within 0.01 of Max 0.5419)
Iteration 1: Pruning 28 features.
2551
before val loop
Iteration 2: Features=12 | Best Val Score=0.5563
   >>> New Champion Selected! (Score: 0.5563 is within 0.01 of Max 0.5563)
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 12) with Score: 0.5563

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 1000, 'learning_rate': 0.005, 'max_depth': 3, 'min_samples_leaf': 50, 'subsample': 0.75}

--- Final Test Set Evaluation for BLMN ---
              precision    recall  f1-score   support

           0       0.48      0.85      0.62      1150
           1       0.81      0.41      0.55      1790

    accuracy                           0.58      2940
   macro avg       0.65      0.63      0.58      2940
weighted avg       0.68      0.58      0.57      2940


Top 10 Feature Importances (Final Tuned Model):
| Feature                      |   Importance |
|:-----------------------------|-------------:|
| change_lag_5070th_ptile_BLMN |    0.187938  |
| efficiency_ratio_50_BLMN     |    0.179715  |
| rolling_avg_vol_25_DRI       |    0.0995786 |
| bb_width_25_BH               |    0.0942438 |
| skew_10_KRUS                 |    0.073562  |
| skew_25_PZZA                 |    0.0732663 |
| bb_width_50_SG               |    0.0658715 |
| bb_width_10_PETZ             |    0.0644929 |
| volatility_25_CHSN           |    0.0593771 |
| bb_width_25_DRI              |    0.0374429 |
No existing model found for BLMN_85. Saving...
✅ Model saved to: ./models/restaurants/champion_model_BLMN_85.pkl
PZZA
15

================ Starting analysis for symbol: PZZA ================

C:\Users\allth\AppData\Local\Temp\ipykernel_56232\2445029629.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

Train End Date:   2025-04-22 11:15:00+00:00
Val Start Date:   2025-05-13 11:15:00+00:00
Val End Date:     2025-10-02 11:45:00+00:00
Test Start Date:  2025-10-23 11:45:00+00:00
Running Greta on strictly historical training slice: 6482 rows...
Original rows: 6482 | Subsampled Base Rows (Max possible): 250
Calculating Noise Floor on 249 rows...
['volatility_25_THCH', 'skew_50_KRUS', 'skew_50_HDL', 'volatility_50_KRUS', 'rsi_50_WING']
Calculating correlation matrix...
Starting greedy reduction with t=0.8, n=40...

Optimization Complete!
Started with: 243 features
Accepted: 40 features
Starting NaN pruning. Target minimum rows: 5106
Data Points: 12766 -> 12241 (Adequate rows secured!)
Data Points: 12241 -> 12241 (Dropped 0 rows due to NaN features)
train rows:  5972
val rows:  2551
test rows:  2940
before while true
2551
before val loop
Iteration 1: Features=40 | Best Val Score=0.7093
   >>> New Champion Selected! (Score: 0.7093 is within 0.01 of Max 0.7093)
Iteration 1: Pruning 30 features.
2551
before val loop
Iteration 2: Features=10 | Best Val Score=0.7724
   >>> New Champion Selected! (Score: 0.7724 is within 0.01 of Max 0.7724)
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 10) with Score: 0.7724

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 3, 'min_samples_leaf': 50, 'subsample': 0.75}

--- Final Test Set Evaluation for PZZA ---
              precision    recall  f1-score   support

           0       0.58      0.10      0.16       688
           1       0.78      0.98      0.87      2252

    accuracy                           0.77      2940
   macro avg       0.68      0.54      0.52      2940
weighted avg       0.73      0.77      0.70      2940


Top 10 Feature Importances (Final Tuned Model):
| Feature                      |   Importance |
|:-----------------------------|-------------:|
| volatility_50_KRUS           |    0.222873  |
| skew_25_JACK                 |    0.157338  |
| change_lag_5070th_ptile_BJRI |    0.109563  |
| volatility_10_CHSN           |    0.0876438 |
| weekday_adj_vol_25_CBRL      |    0.0788054 |
| volatility_50_RICK           |    0.0779036 |
| rolling_avg_vol_50_BROS      |    0.0773208 |
| bb_width_50_PETZ             |    0.0717541 |
| volatility_25_BJRI           |    0.0673113 |
| change_lag_2510th_ptile_SBUX |    0.049487  |
No existing model found for PZZA_15. Saving...
✅ Model saved to: ./models/restaurants/champion_model_PZZA_15.pkl
85

================ Starting analysis for symbol: PZZA ================

C:\Users\allth\AppData\Local\Temp\ipykernel_56232\2445029629.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

Train End Date:   2025-04-22 11:15:00+00:00
Val Start Date:   2025-05-13 11:15:00+00:00
Val End Date:     2025-10-02 11:45:00+00:00
Test Start Date:  2025-10-23 11:45:00+00:00
Running Greta on strictly historical training slice: 6482 rows...
Original rows: 6482 | Subsampled Base Rows (Max possible): 250
Calculating Noise Floor on 249 rows...
['bb_width_50_WING', 'bb_width_50_PETZ', 'bb_width_50_THCH', 'rolling_avg_vol_50_NATH', 'skew_50_EAT']
Calculating correlation matrix...
Starting greedy reduction with t=0.8, n=40...

Optimization Complete!
Started with: 243 features
Accepted: 40 features
Starting NaN pruning. Target minimum rows: 5106
Data Points: 12766 -> 12736 (Adequate rows secured!)
Data Points: 12736 -> 12736 (Dropped 0 rows due to NaN features)
train rows:  6467
val rows:  2551
test rows:  2940
before while true
2551
before val loop
Iteration 1: Features=40 | Best Val Score=0.6238
   >>> New Champion Selected! (Score: 0.6238 is within 0.01 of Max 0.6238)
Iteration 1: Pruning 26 features.
2551
before val loop
Iteration 2: Features=14 | Best Val Score=0.6148
   >>> New Champion Selected! (Score: 0.6148 is within 0.01 of Max 0.6238)
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 14) with Score: 0.6148

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 1000, 'learning_rate': 0.005, 'max_depth': 3, 'min_samples_leaf': 50, 'subsample': 1.0}

--- Final Test Set Evaluation for PZZA ---
              precision    recall  f1-score   support

           0       0.79      0.54      0.64      1897
           1       0.47      0.73      0.57      1043

    accuracy                           0.61      2940
   macro avg       0.63      0.64      0.61      2940
weighted avg       0.67      0.61      0.62      2940


Top 10 Feature Importances (Final Tuned Model):
| Feature                 |   Importance |
|:------------------------|-------------:|
| skew_50_SBUX            |    0.163012  |
| volatility_50_RICK      |    0.155611  |
| bb_width_50_THCH        |    0.0883204 |
| weekday_adj_vol_25_CBRL |    0.0808682 |
| volatility_10_CHSN      |    0.0698154 |
| bb_width_50_YUMC        |    0.0650129 |
| skew_50_BJRI            |    0.0617785 |
| skew_50_YUM             |    0.0606945 |
| volatility_25_DPZ       |    0.0540529 |
| bb_width_50_WING        |    0.0522251 |
No existing model found for PZZA_85. Saving...
✅ Model saved to: ./models/restaurants/champion_model_PZZA_85.pkl
GENK
15

================ Starting analysis for symbol: GENK ================

C:\Users\allth\AppData\Local\Temp\ipykernel_56232\2445029629.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

Train End Date:   2025-04-22 11:15:00+00:00
Val Start Date:   2025-05-13 11:15:00+00:00
Val End Date:     2025-10-02 11:45:00+00:00
Test Start Date:  2025-10-23 11:45:00+00:00
Running Greta on strictly historical training slice: 6482 rows...
Original rows: 6482 | Subsampled Base Rows (Max possible): 249
Calculating Noise Floor on 249 rows...
['bb_width_50_LOCO', 'bb_width_50_SHAK', 'volatility_25_PZZA', 'weekday_adj_vol_25_PZZA', 'weekday_adj_vol_25_CBRL']
Calculating correlation matrix...
Starting greedy reduction with t=0.8, n=40...

Optimization Complete!
Started with: 243 features
Accepted: 40 features
Starting NaN pruning. Target minimum rows: 5106
Data Points: 12766 -> 11451 (Adequate rows secured!)
Data Points: 11451 -> 11451 (Dropped 0 rows due to NaN features)
train rows:  5182
val rows:  2551
test rows:  2940
before while true
2551
before val loop
Iteration 1: Features=40 | Best Val Score=0.8300
   >>> New Champion Selected! (Score: 0.8300 is within 0.01 of Max 0.8300)
Iteration 1: Pruning 30 features.
2551
before val loop
Iteration 2: Features=10 | Best Val Score=0.8300
   >>> New Champion Selected! (Score: 0.8300 is within 0.01 of Max 0.8300)
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 10) with Score: 0.8300

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 3, 'min_samples_leaf': 75, 'subsample': 0.75}

--- Final Test Set Evaluation for GENK ---
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       506
           1       0.83      1.00      0.91      2434

    accuracy                           0.83      2940
   macro avg       0.41      0.50      0.45      2940
weighted avg       0.69      0.83      0.75      2940


Top 10 Feature Importances (Final Tuned Model):
| Feature                      |   Importance |
|:-----------------------------|-------------:|
| bb_width_50_LOCO             |    0.197288  |
| skew_50_FWRG                 |    0.176282  |
| rolling_avg_vol_10_YUMC      |    0.140635  |
| bb_width_10_CMG              |    0.107813  |
| bb_width_50_BH.A             |    0.0871217 |
| rolling_avg_vol_25_YUM       |    0.0754342 |
| skew_25_GTIM                 |    0.06567   |
| weekday_adj_vol_25_CBRL      |    0.0548399 |
| change_lag_5070th_ptile_ARCO |    0.0495801 |
| weekday_adj_vol_25_YUM       |    0.0453359 |
No existing model found for GENK_15. Saving...
✅ Model saved to: ./models/restaurants/champion_model_GENK_15.pkl
85

================ Starting analysis for symbol: GENK ================

C:\Users\allth\AppData\Local\Temp\ipykernel_56232\2445029629.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

Train End Date:   2025-04-22 11:15:00+00:00
Val Start Date:   2025-05-13 11:15:00+00:00
Val End Date:     2025-10-02 11:45:00+00:00
Test Start Date:  2025-10-23 11:45:00+00:00
Running Greta on strictly historical training slice: 6482 rows...
Original rows: 6482 | Subsampled Base Rows (Max possible): 249
Calculating Noise Floor on 249 rows...
['weekday_adj_vol_50_ARCO', 'bb_width_10_CMG', 'bb_width_50_BH', 'rolling_avg_vol_10_NDLS', 'volatility_25_ARKR']
Calculating correlation matrix...
Starting greedy reduction with t=0.8, n=40...

Optimization Complete!
Started with: 243 features
Accepted: 40 features
Starting NaN pruning. Target minimum rows: 5106
Data Points: 12766 -> 12101 (Adequate rows secured!)
Data Points: 12101 -> 12101 (Dropped 0 rows due to NaN features)
train rows:  5832
val rows:  2551
test rows:  2940
before while true
2551
before val loop
Iteration 1: Features=40 | Best Val Score=0.3426
   >>> New Champion Selected! (Score: 0.3426 is within 0.01 of Max 0.3426)
Iteration 1: Pruning 28 features.
2551
before val loop
Iteration 2: Features=12 | Best Val Score=0.5145
   >>> New Champion Selected! (Score: 0.5145 is within 0.01 of Max 0.5145)
Iteration 2: Pruning 1 features.
2551
before val loop
Iteration 3: Features=11 | Best Val Score=0.6040
   >>> New Champion Selected! (Score: 0.6040 is within 0.01 of Max 0.6040)
Iteration 3: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 11) with Score: 0.6040

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 1000, 'learning_rate': 0.005, 'max_depth': 2, 'min_samples_leaf': 50, 'subsample': 1.0}

--- Final Test Set Evaluation for GENK ---
              precision    recall  f1-score   support

           0       0.58      0.92      0.71      1662
           1       0.57      0.13      0.21      1278

    accuracy                           0.58      2940
   macro avg       0.57      0.53      0.46      2940
weighted avg       0.57      0.58      0.50      2940


Top 10 Feature Importances (Final Tuned Model):
| Feature                 |   Importance |
|:------------------------|-------------:|
| rolling_avg_vol_50_WING |    0.141548  |
| bb_width_50_PTLO        |    0.124588  |
| bb_width_50_ARCO        |    0.116975  |
| rolling_avg_vol_25_YUM  |    0.111573  |
| volatility_25_BH.A      |    0.094271  |
| volatility_50_RRGB      |    0.0811884 |
| volatility_50_WING      |    0.0766913 |
| skew_50_GENK            |    0.0718109 |
| bb_width_25_DIN         |    0.0713244 |
| weekday_adj_vol_25_YUM  |    0.0682595 |
No existing model found for GENK_85. Saving...
✅ Model saved to: ./models/restaurants/champion_model_GENK_85.pkl
PTLO
15

================ Starting analysis for symbol: PTLO ================

C:\Users\allth\AppData\Local\Temp\ipykernel_56232\2445029629.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

Train End Date:   2025-04-22 11:15:00+00:00
Val Start Date:   2025-05-13 11:15:00+00:00
Val End Date:     2025-10-02 11:45:00+00:00
Test Start Date:  2025-10-23 11:45:00+00:00
Running Greta on strictly historical training slice: 6482 rows...
Original rows: 6482 | Subsampled Base Rows (Max possible): 249
Calculating Noise Floor on 249 rows...
['bb_width_50_JACK', 'volatility_50_REBN', 'rsi_50_CHSN', 'rolling_avg_vol_50_BLMN', 'volatility_25_REBN']
Calculating correlation matrix...
Starting greedy reduction with t=0.8, n=40...

Optimization Complete!
Started with: 243 features
Accepted: 40 features
Starting NaN pruning. Target minimum rows: 5106
Data Points: 12766 -> 12737 (Adequate rows secured!)
Data Points: 12737 -> 12737 (Dropped 0 rows due to NaN features)
train rows:  6468
val rows:  2551
test rows:  2940
before while true
2551
before val loop
Iteration 1: Features=40 | Best Val Score=0.9119
   >>> New Champion Selected! (Score: 0.9119 is within 0.01 of Max 0.9119)
Iteration 1: Pruning 28 features.
2551
before val loop
Iteration 2: Features=12 | Best Val Score=0.9119
   >>> New Champion Selected! (Score: 0.9119 is within 0.01 of Max 0.9119)
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 12) with Score: 0.9119

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 2, 'min_samples_leaf': 75, 'subsample': 0.75}

--- Final Test Set Evaluation for PTLO ---
              precision    recall  f1-score   support

           0       0.96      0.12      0.21      1145
           1       0.64      1.00      0.78      1795

    accuracy                           0.66      2940
   macro avg       0.80      0.56      0.50      2940
weighted avg       0.77      0.66      0.56      2940


Top 10 Feature Importances (Final Tuned Model):
| Feature                 |   Importance |
|:------------------------|-------------:|
| skew_50_RICK            |    0.162276  |
| volatility_50_KRUS      |    0.149202  |
| rolling_avg_vol_25_RICK |    0.126249  |
| rolling_avg_vol_50_YUMC |    0.114071  |
| rolling_avg_vol_25_CAKE |    0.0968383 |
| skew_50_SBUX            |    0.0691931 |
| weekday_adj_vol_25_DRI  |    0.0601106 |
| rolling_avg_vol_10_RAVE |    0.0501037 |
| skew_50_EAT             |    0.0472888 |
| skew_25_REBN            |    0.0456362 |
No existing model found for PTLO_15. Saving...
✅ Model saved to: ./models/restaurants/champion_model_PTLO_15.pkl
85

================ Starting analysis for symbol: PTLO ================

C:\Users\allth\AppData\Local\Temp\ipykernel_56232\2445029629.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

Train End Date:   2025-04-22 11:15:00+00:00
Val Start Date:   2025-05-13 11:15:00+00:00
Val End Date:     2025-10-02 11:45:00+00:00
Test Start Date:  2025-10-23 11:45:00+00:00
Running Greta on strictly historical training slice: 6482 rows...
Original rows: 6482 | Subsampled Base Rows (Max possible): 250
Calculating Noise Floor on 249 rows...
['skew_50_RICK', 'bb_width_50_DPZ', 'volatility_50_REBN', 'volatility_50_KRUS', 'bb_width_25_FWRG']
Calculating correlation matrix...
Starting greedy reduction with t=0.8, n=40...

Optimization Complete!
Started with: 243 features
Accepted: 40 features
Starting NaN pruning. Target minimum rows: 5106
Data Points: 12766 -> 12242 (Adequate rows secured!)
Data Points: 12242 -> 12242 (Dropped 0 rows due to NaN features)
train rows:  5973
val rows:  2551
test rows:  2940
before while true
2551
before val loop
Iteration 1: Features=40 | Best Val Score=0.2824
   >>> New Champion Selected! (Score: 0.2824 is within 0.01 of Max 0.2824)
Iteration 1: Pruning 26 features.
2551
before val loop
Iteration 2: Features=14 | Best Val Score=0.3304
   >>> New Champion Selected! (Score: 0.3304 is within 0.01 of Max 0.3304)
Iteration 2: Pruning 1 features.
2551
before val loop
Iteration 3: Features=13 | Best Val Score=0.3398
   >>> New Champion Selected! (Score: 0.3398 is within 0.01 of Max 0.3398)
Iteration 3: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 13) with Score: 0.3398

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 3, 'min_samples_leaf': 75, 'subsample': 1.0}

--- Final Test Set Evaluation for PTLO ---
              precision    recall  f1-score   support

           0       0.43      0.80      0.56      1258
           1       0.59      0.21      0.31      1682

    accuracy                           0.47      2940
   macro avg       0.51      0.51      0.44      2940
weighted avg       0.52      0.47      0.42      2940


Top 10 Feature Importances (Final Tuned Model):
| Feature                 |   Importance |
|:------------------------|-------------:|
| rolling_avg_vol_50_WING |    0.119987  |
| skew_50_RICK            |    0.116355  |
| rolling_avg_vol_25_EAT  |    0.113555  |
| skew_50_KRUS            |    0.108575  |
| rolling_avg_vol_10_NDLS |    0.1038    |
| bb_width_50_SG          |    0.0980664 |
| bb_width_25_PTLO        |    0.0791789 |
| rolling_avg_vol_50_DRI  |    0.0683912 |
| volatility_50_KRUS      |    0.0443169 |
| rolling_avg_vol_25_YUM  |    0.0438501 |
No existing model found for PTLO_85. Saving...

C:\Users\allth\AppData\Local\Temp\ipykernel_56232\2445029629.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

✅ Model saved to: ./models/restaurants/champion_model_PTLO_85.pkl
WEN
15

================ Starting analysis for symbol: WEN ================
Train End Date:   2025-04-22 11:15:00+00:00
Val Start Date:   2025-05-13 11:15:00+00:00
Val End Date:     2025-10-02 11:45:00+00:00
Test Start Date:  2025-10-23 11:45:00+00:00
Running Greta on strictly historical training slice: 6482 rows...
Original rows: 6482 | Subsampled Base Rows (Max possible): 250
Calculating Noise Floor on 250 rows...
['bb_width_50_WING', 'volatility_50_REBN', 'volatility_50_KRUS', 'skew_25_MCD', 'volatility_50_EAT']
Calculating correlation matrix...
Starting greedy reduction with t=0.8, n=40...

Optimization Complete!
Started with: 243 features
Accepted: 40 features
Starting NaN pruning. Target minimum rows: 5106
Data Points: 12766 -> 12723 (Adequate rows secured!)
Data Points: 12723 -> 12723 (Dropped 0 rows due to NaN features)
train rows:  6454
val rows:  2551
test rows:  2940
before while true
2551
before val loop
Iteration 1: Features=40 | Best Val Score=0.8510
   >>> New Champion Selected! (Score: 0.8510 is within 0.01 of Max 0.8510)
Iteration 1: Pruning 31 features.
2551
before val loop
Iteration 2: Features=9 | Best Val Score=0.8510
   >>> New Champion Selected! (Score: 0.8510 is within 0.01 of Max 0.8510)
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 9) with Score: 0.8510

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 3, 'min_samples_leaf': 75, 'subsample': 0.75}

--- Final Test Set Evaluation for WEN ---
              precision    recall  f1-score   support

           0       0.69      0.06      0.11       986
           1       0.67      0.99      0.80      1954

    accuracy                           0.68      2940
   macro avg       0.68      0.52      0.45      2940
weighted avg       0.68      0.68      0.57      2940


Top 10 Feature Importances (Final Tuned Model):
| Feature                      |   Importance |
|:-----------------------------|-------------:|
| skew_50_SBUX                 |    0.199489  |
| rolling_avg_vol_50_WING      |    0.158839  |
| volatility_50_RRGB           |    0.125022  |
| bb_width_50_THCH             |    0.117757  |
| skew_25_MCD                  |    0.104831  |
| rolling_avg_vol_50_SBUX      |    0.0817548 |
| volatility_50_REBN           |    0.0771503 |
| bb_width_50_PETZ             |    0.0728592 |
| change_lag_5090th_ptile_BH.A |    0.062297  |
No existing model found for WEN_15. Saving...
✅ Model saved to: ./models/restaurants/champion_model_WEN_15.pkl
85

================ Starting analysis for symbol: WEN ================

C:\Users\allth\AppData\Local\Temp\ipykernel_56232\2445029629.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

Train End Date:   2025-04-22 11:15:00+00:00
Val Start Date:   2025-05-13 11:15:00+00:00
Val End Date:     2025-10-02 11:45:00+00:00
Test Start Date:  2025-10-23 11:45:00+00:00
Running Greta on strictly historical training slice: 6482 rows...
Original rows: 6482 | Subsampled Base Rows (Max possible): 250
Calculating Noise Floor on 249 rows...
['volatility_50_KRUS', 'weekday_adj_vol_50_KRUS', 'skew_50_EAT', 'volatility_50_SHAK', 'volatility_50_EAT']
Calculating correlation matrix...
Starting greedy reduction with t=0.8, n=40...

Optimization Complete!
Started with: 243 features
Accepted: 40 features
Starting NaN pruning. Target minimum rows: 5106
Data Points: 12766 -> 12241 (Adequate rows secured!)
Data Points: 12241 -> 12241 (Dropped 0 rows due to NaN features)
train rows:  5972
val rows:  2551
test rows:  2940
before while true
2551
before val loop
Iteration 1: Features=40 | Best Val Score=0.4106
   >>> New Champion Selected! (Score: 0.4106 is within 0.01 of Max 0.4106)
Iteration 1: Pruning 27 features.
2551
before val loop
Iteration 2: Features=13 | Best Val Score=0.3856
   >>> Score drop > 0.01 (Val: 0.3856 vs Max: 0.4106). Keeping previous Champion.
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 40) with Score: 0.4106

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 1000, 'learning_rate': 0.005, 'max_depth': 2, 'min_samples_leaf': 75, 'subsample': 0.75}

--- Final Test Set Evaluation for WEN ---
              precision    recall  f1-score   support

           0       0.64      0.65      0.64      1938
           1       0.30      0.29      0.29      1002

    accuracy                           0.52      2940
   macro avg       0.47      0.47      0.47      2940
weighted avg       0.52      0.52      0.52      2940


Top 10 Feature Importances (Final Tuned Model):
| Feature                      |   Importance |
|:-----------------------------|-------------:|
| change_lag_5090th_ptile_BH.A |    0.184312  |
| skew_50_BLMN                 |    0.151921  |
| skew_50_MCD                  |    0.0844067 |
| volatility_50_CNNE           |    0.0692751 |
| weekday_adj_vol_50_CAKE      |    0.0563509 |
| bb_width_25_RAVE             |    0.0442914 |
| change_lag_5050th_ptile_CHSN |    0.0406299 |
| bb_width_50_PETZ             |    0.0351268 |
| rolling_avg_vol_25_STKS      |    0.0324694 |
| skew_25_GENK                 |    0.0309976 |
No existing model found for WEN_85. Saving...
✅ Model saved to: ./models/restaurants/champion_model_WEN_85.pkl
STKS
15

================ Starting analysis for symbol: STKS ================

C:\Users\allth\AppData\Local\Temp\ipykernel_56232\2445029629.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

Train End Date:   2025-04-22 11:15:00+00:00
Val Start Date:   2025-05-13 11:15:00+00:00
Val End Date:     2025-10-02 11:45:00+00:00
Test Start Date:  2025-10-23 11:45:00+00:00
Running Greta on strictly historical training slice: 6482 rows...
Original rows: 6482 | Subsampled Base Rows (Max possible): 250
Calculating Noise Floor on 249 rows...
['volatility_50_KRUS', 'weekday_adj_vol_50_KRUS', 'volatility_25_ARCO', 'weekday_adj_vol_25_ARCO', 'skew_25_BLMN']
Calculating correlation matrix...
Starting greedy reduction with t=0.8, n=40...

Optimization Complete!
Started with: 243 features
Accepted: 40 features
Starting NaN pruning. Target minimum rows: 5106
Data Points: 12766 -> 11451 (Adequate rows secured!)
Data Points: 11451 -> 11451 (Dropped 0 rows due to NaN features)
train rows:  5182
val rows:  2551
test rows:  2940
before while true
2551
before val loop
Iteration 1: Features=40 | Best Val Score=0.7743
   >>> New Champion Selected! (Score: 0.7743 is within 0.01 of Max 0.7743)
Iteration 1: Pruning 27 features.
2551
before val loop
Iteration 2: Features=13 | Best Val Score=0.7905
   >>> New Champion Selected! (Score: 0.7905 is within 0.01 of Max 0.7905)
Iteration 2: Pruning 2 features.
2551
before val loop
Iteration 3: Features=11 | Best Val Score=0.8316
   >>> New Champion Selected! (Score: 0.8316 is within 0.01 of Max 0.8316)
Iteration 3: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 11) with Score: 0.8316

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 3, 'min_samples_leaf': 50, 'subsample': 1.0}

--- Final Test Set Evaluation for STKS ---
              precision    recall  f1-score   support

           0       0.32      0.57      0.41       803
           1       0.77      0.54      0.63      2137

    accuracy                           0.55      2940
   macro avg       0.54      0.56      0.52      2940
weighted avg       0.65      0.55      0.57      2940


Top 10 Feature Importances (Final Tuned Model):
| Feature                      |   Importance |
|:-----------------------------|-------------:|
| change_lag_5050th_ptile_JACK |    0.189887  |
| change_lag_5070th_ptile_STKS |    0.189409  |
| rolling_avg_vol_50_BJRI      |    0.109754  |
| skew_25_BLMN                 |    0.0930924 |
| bb_width_50_CHSN             |    0.0824333 |
| skew_25_STKS                 |    0.0712686 |
| volatility_50_KRUS           |    0.0690826 |
| skew_50_KRUS                 |    0.0618626 |
| volatility_10_BH             |    0.0470259 |
| bb_width_50_PZZA             |    0.0467473 |
No existing model found for STKS_15. Saving...
✅ Model saved to: ./models/restaurants/champion_model_STKS_15.pkl
85

================ Starting analysis for symbol: STKS ================

C:\Users\allth\AppData\Local\Temp\ipykernel_56232\2445029629.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

Train End Date:   2025-04-22 11:15:00+00:00
Val Start Date:   2025-05-13 11:15:00+00:00
Val End Date:     2025-10-02 11:45:00+00:00
Test Start Date:  2025-10-23 11:45:00+00:00
Running Greta on strictly historical training slice: 6482 rows...
Original rows: 6482 | Subsampled Base Rows (Max possible): 249
Calculating Noise Floor on 250 rows...
['skew_25_BLMN', 'volatility_50_KRUS', 'weekday_adj_vol_50_KRUS', 'bb_width_50_BH', 'change_lag_5050th_ptile_JACK']
Calculating correlation matrix...
Starting greedy reduction with t=0.8, n=40...

Optimization Complete!
Started with: 243 features
Accepted: 40 features
Starting NaN pruning. Target minimum rows: 5106
Data Points: 12766 -> 12083 (Adequate rows secured!)
Data Points: 12083 -> 12083 (Dropped 0 rows due to NaN features)
train rows:  5814
val rows:  2551
test rows:  2940
before while true
2551
before val loop
Iteration 1: Features=40 | Best Val Score=0.4874
   >>> New Champion Selected! (Score: 0.4874 is within 0.01 of Max 0.4874)
Iteration 1: Pruning 29 features.
2551
before val loop
Iteration 2: Features=11 | Best Val Score=0.6479
   >>> New Champion Selected! (Score: 0.6479 is within 0.01 of Max 0.6479)
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 11) with Score: 0.6479

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 1000, 'learning_rate': 0.005, 'max_depth': 2, 'min_samples_leaf': 50, 'subsample': 0.75}

--- Final Test Set Evaluation for STKS ---
              precision    recall  f1-score   support

           0       0.48      0.23      0.31      1427
           1       0.51      0.76      0.61      1513

    accuracy                           0.51      2940
   macro avg       0.50      0.50      0.46      2940
weighted avg       0.50      0.51      0.47      2940


Top 10 Feature Importances (Final Tuned Model):
| Feature                      |   Importance |
|:-----------------------------|-------------:|
| rsi_50_STKS                  |    0.23099   |
| change_lag_5050th_ptile_JACK |    0.225132  |
| bb_width_25_BROS             |    0.0760802 |
| volatility_25_RICK           |    0.0732545 |
| volatility_50_EAT            |    0.0713745 |
| weekday_adj_vol_25_CBRL      |    0.0701212 |
| rolling_avg_vol_10_CNNE      |    0.0688481 |
| bb_width_25_WEN              |    0.0588302 |
| bb_width_25_EAT              |    0.0431647 |
| rolling_avg_vol_25_SBUX      |    0.0426737 |
No existing model found for STKS_85. Saving...
✅ Model saved to: ./models/restaurants/champion_model_STKS_85.pkl
DPZ
15

================ Starting analysis for symbol: DPZ ================

C:\Users\allth\AppData\Local\Temp\ipykernel_56232\2445029629.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

Train End Date:   2025-04-22 11:15:00+00:00
Val Start Date:   2025-05-13 11:15:00+00:00
Val End Date:     2025-10-02 11:45:00+00:00
Test Start Date:  2025-10-23 11:45:00+00:00
Running Greta on strictly historical training slice: 6482 rows...
Original rows: 6482 | Subsampled Base Rows (Max possible): 249
Calculating Noise Floor on 249 rows...
['skew_50_DPZ', 'change_lag_5090th_ptile_ARCO', 'weekday_adj_vol_50_DPZ', 'bb_width_50_ARCO', 'rolling_avg_vol_25_BTBD']
Calculating correlation matrix...
Starting greedy reduction with t=0.8, n=40...

Optimization Complete!
Started with: 243 features
Accepted: 40 features
Starting NaN pruning. Target minimum rows: 5106
Data Points: 12766 -> 12241 (Adequate rows secured!)
Data Points: 12241 -> 12241 (Dropped 0 rows due to NaN features)
train rows:  5972
val rows:  2551
test rows:  2940
before while true
2551
before val loop
Iteration 1: Features=40 | Best Val Score=0.6353
   >>> New Champion Selected! (Score: 0.6353 is within 0.01 of Max 0.6353)
Iteration 1: Pruning 27 features.
2551
before val loop
Iteration 2: Features=13 | Best Val Score=0.8653
   >>> New Champion Selected! (Score: 0.8653 is within 0.01 of Max 0.8653)
Iteration 2: Pruning 1 features.
2551
before val loop
Iteration 3: Features=12 | Best Val Score=0.8653
   >>> New Champion Selected! (Score: 0.8653 is within 0.01 of Max 0.8653)
Iteration 3: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 12) with Score: 0.8653

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 1000, 'learning_rate': 0.005, 'max_depth': 2, 'min_samples_leaf': 75, 'subsample': 1.0}

--- Final Test Set Evaluation for DPZ ---
              precision    recall  f1-score   support

           0       0.54      0.81      0.65      1500
           1       0.59      0.29      0.39      1440

    accuracy                           0.55      2940
   macro avg       0.57      0.55      0.52      2940
weighted avg       0.57      0.55      0.52      2940


Top 10 Feature Importances (Final Tuned Model):
| Feature                      |   Importance |
|:-----------------------------|-------------:|
| weekday_adj_vol_25_SHAK      |    0.250171  |
| rolling_avg_vol_50_NDLS      |    0.171509  |
| rolling_avg_vol_25_BTBD      |    0.123114  |
| skew_25_JACK                 |    0.0798301 |
| weekday_adj_vol_50_DPZ       |    0.0709528 |
| skew_50_HDL                  |    0.0590675 |
| change_lag_5090th_ptile_ARCO |    0.0508972 |
| skew_50_BLMN                 |    0.0414351 |
| weekday_adj_vol_50_PTLO      |    0.0401825 |
| bb_width_50_PZZA             |    0.0396498 |
No existing model found for DPZ_15. Saving...
✅ Model saved to: ./models/restaurants/champion_model_DPZ_15.pkl
85

================ Starting analysis for symbol: DPZ ================

C:\Users\allth\AppData\Local\Temp\ipykernel_56232\2445029629.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

Train End Date:   2025-04-22 11:15:00+00:00
Val Start Date:   2025-05-13 11:15:00+00:00
Val End Date:     2025-10-02 11:45:00+00:00
Test Start Date:  2025-10-23 11:45:00+00:00
Running Greta on strictly historical training slice: 6482 rows...
Original rows: 6482 | Subsampled Base Rows (Max possible): 250
Calculating Noise Floor on 249 rows...
['skew_50_DPZ', 'skew_50_BROS', 'bb_width_50_ARCO', 'skew_50_QSR', 'skew_50_BLMN']
Calculating correlation matrix...
Starting greedy reduction with t=0.8, n=40...

Optimization Complete!
Started with: 243 features
Accepted: 40 features
Starting NaN pruning. Target minimum rows: 5106
Data Points: 12766 -> 11451 (Adequate rows secured!)
Data Points: 11451 -> 11451 (Dropped 0 rows due to NaN features)
train rows:  5182
val rows:  2551
test rows:  2940
before while true
2551
before val loop
Iteration 1: Features=40 | Best Val Score=0.3520
   >>> New Champion Selected! (Score: 0.3520 is within 0.01 of Max 0.3520)
Iteration 1: Pruning 29 features.
2551
before val loop
Iteration 2: Features=11 | Best Val Score=0.3449
   >>> New Champion Selected! (Score: 0.3449 is within 0.01 of Max 0.3520)
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 11) with Score: 0.3449

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 1000, 'learning_rate': 0.005, 'max_depth': 3, 'min_samples_leaf': 75, 'subsample': 0.75}

--- Final Test Set Evaluation for DPZ ---
              precision    recall  f1-score   support

           0       0.54      0.92      0.68      1571
           1       0.50      0.09      0.15      1369

    accuracy                           0.54      2940
   macro avg       0.52      0.51      0.41      2940
weighted avg       0.52      0.54      0.43      2940


Top 10 Feature Importances (Final Tuned Model):
| Feature                 |   Importance |
|:------------------------|-------------:|
| volatility_25_THCH      |    0.228279  |
| skew_25_LOCO            |    0.150089  |
| bb_width_50_NATH        |    0.130427  |
| weekday_adj_vol_50_DPZ  |    0.0942943 |
| skew_50_DPZ             |    0.0733797 |
| skew_25_JACK            |    0.0725242 |
| volatility_50_KRUS      |    0.069294  |
| rolling_avg_vol_25_CAVA |    0.0622081 |
| skew_50_BLMN            |    0.0437244 |
| skew_50_SBUX            |    0.0386319 |
No existing model found for DPZ_85. Saving...
✅ Model saved to: ./models/restaurants/champion_model_DPZ_85.pkl
QSR
15

================ Starting analysis for symbol: QSR ================

C:\Users\allth\AppData\Local\Temp\ipykernel_56232\2445029629.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

Train End Date:   2025-04-22 11:15:00+00:00
Val Start Date:   2025-05-13 11:15:00+00:00
Val End Date:     2025-10-02 11:45:00+00:00
Test Start Date:  2025-10-23 11:45:00+00:00
Running Greta on strictly historical training slice: 6482 rows...
Original rows: 6482 | Subsampled Base Rows (Max possible): 249
Calculating Noise Floor on 250 rows...
['volatility_25_THCH', 'skew_25_GENK', 'volatility_50_RICK', 'bb_width_50_CHSN', 'volatility_50_CMG']
Calculating correlation matrix...
Starting greedy reduction with t=0.8, n=40...

Optimization Complete!
Started with: 243 features
Accepted: 40 features
Starting NaN pruning. Target minimum rows: 5106
Data Points: 12766 -> 12241 (Adequate rows secured!)
Data Points: 12241 -> 12241 (Dropped 0 rows due to NaN features)
train rows:  5972
val rows:  2551
test rows:  2940
before while true
2551
before val loop
Iteration 1: Features=40 | Best Val Score=0.5281
   >>> New Champion Selected! (Score: 0.5281 is within 0.01 of Max 0.5281)
Iteration 1: Pruning 25 features.
2551
before val loop
Iteration 2: Features=15 | Best Val Score=0.6942
   >>> New Champion Selected! (Score: 0.6942 is within 0.01 of Max 0.6942)
Iteration 2: Pruning 3 features.
2551
before val loop
Iteration 3: Features=12 | Best Val Score=0.7155
   >>> New Champion Selected! (Score: 0.7155 is within 0.01 of Max 0.7155)
Iteration 3: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 12) with Score: 0.7155

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 3, 'min_samples_leaf': 50, 'subsample': 0.75}

--- Final Test Set Evaluation for QSR ---
              precision    recall  f1-score   support

           0       0.74      0.56      0.64      1744
           1       0.53      0.72      0.61      1196

    accuracy                           0.63      2940
   macro avg       0.64      0.64      0.62      2940
weighted avg       0.66      0.63      0.63      2940


Top 10 Feature Importances (Final Tuned Model):
| Feature                      |   Importance |
|:-----------------------------|-------------:|
| skew_25_THCH                 |    0.131485  |
| bb_width_25_SHAK             |    0.120453  |
| volatility_10_CMG            |    0.107437  |
| volatility_50_RICK           |    0.0973664 |
| change_lag_5050th_ptile_CHSN |    0.0951633 |
| skew_25_CAVA                 |    0.0924706 |
| rolling_avg_vol_10_YUM       |    0.0796804 |
| bb_width_50_THCH             |    0.0781542 |
| change_lag_5090th_ptile_BH.A |    0.0584046 |
| bb_width_10_BJRI             |    0.0529874 |
No existing model found for QSR_15. Saving...

C:\Users\allth\AppData\Local\Temp\ipykernel_56232\2445029629.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

✅ Model saved to: ./models/restaurants/champion_model_QSR_15.pkl
85

================ Starting analysis for symbol: QSR ================
Train End Date:   2025-04-22 11:15:00+00:00
Val Start Date:   2025-05-13 11:15:00+00:00
Val End Date:     2025-10-02 11:45:00+00:00
Test Start Date:  2025-10-23 11:45:00+00:00
Running Greta on strictly historical training slice: 6482 rows...
Original rows: 6482 | Subsampled Base Rows (Max possible): 250
Calculating Noise Floor on 250 rows...
['volatility_25_THCH', 'efficiency_ratio_50_LOCO', 'skew_50_HDL', 'skew_50_THCH', 'bb_width_50_NATH']
Calculating correlation matrix...
Starting greedy reduction with t=0.8, n=40...

Optimization Complete!
Started with: 243 features
Accepted: 40 features
Starting NaN pruning. Target minimum rows: 5106
Data Points: 12766 -> 11451 (Adequate rows secured!)
Data Points: 11451 -> 11451 (Dropped 0 rows due to NaN features)
train rows:  5182
val rows:  2551
test rows:  2940
before while true
2551
before val loop
Iteration 1: Features=40 | Best Val Score=0.5459
   >>> New Champion Selected! (Score: 0.5459 is within 0.01 of Max 0.5459)
Iteration 1: Pruning 31 features.
2551
before val loop
Iteration 2: Features=9 | Best Val Score=0.7046
   >>> New Champion Selected! (Score: 0.7046 is within 0.01 of Max 0.7046)
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 9) with Score: 0.7046

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 2, 'min_samples_leaf': 75, 'subsample': 0.75}

--- Final Test Set Evaluation for QSR ---
              precision    recall  f1-score   support

           0       0.24      0.40      0.30      1112
           1       0.40      0.24      0.30      1828

    accuracy                           0.30      2940
   macro avg       0.32      0.32      0.30      2940
weighted avg       0.34      0.30      0.30      2940


Top 10 Feature Importances (Final Tuned Model):
| Feature            |   Importance |
|:-------------------|-------------:|
| skew_50_THCH       |    0.259891  |
| skew_50_BJRI       |    0.177013  |
| skew_25_KRUS       |    0.15042   |
| skew_25_CAVA       |    0.114871  |
| skew_25_MCD        |    0.0922588 |
| volatility_50_WING |    0.0635001 |
| skew_50_QSR        |    0.0498639 |
| skew_25_NDLS       |    0.0493027 |
| bb_width_50_THCH   |    0.0428799 |
No existing model found for QSR_85. Saving...
✅ Model saved to: ./models/restaurants/champion_model_QSR_85.pkl
BJRI
15

================ Starting analysis for symbol: BJRI ================

C:\Users\allth\AppData\Local\Temp\ipykernel_56232\2445029629.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

Train End Date:   2025-04-22 11:15:00+00:00
Val Start Date:   2025-05-13 11:15:00+00:00
Val End Date:     2025-10-02 11:45:00+00:00
Test Start Date:  2025-10-23 11:45:00+00:00
Running Greta on strictly historical training slice: 6482 rows...
Original rows: 6482 | Subsampled Base Rows (Max possible): 249
Calculating Noise Floor on 249 rows...
['rsi_50_BJRI', 'change_lag_5070th_ptile_BJRI', 'z_score_25_BJRI', 'change_lag_2530th_ptile_BJRI', 'change_lag_5050th_ptile_BJRI']
Calculating correlation matrix...
Starting greedy reduction with t=0.8, n=40...

Optimization Complete!
Started with: 243 features
Accepted: 40 features
Starting NaN pruning. Target minimum rows: 5106
Data Points: 12766 -> 12733 (Adequate rows secured!)
Data Points: 12733 -> 12733 (Dropped 0 rows due to NaN features)
train rows:  6464
val rows:  2551
test rows:  2940
before while true
2551
before val loop
Iteration 1: Features=40 | Best Val Score=0.6049
   >>> New Champion Selected! (Score: 0.6049 is within 0.01 of Max 0.6049)
Iteration 1: Pruning 32 features.
2551
before val loop
Iteration 2: Features=8 | Best Val Score=0.8624
   >>> New Champion Selected! (Score: 0.8624 is within 0.01 of Max 0.8624)
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 8) with Score: 0.8624

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 1000, 'learning_rate': 0.005, 'max_depth': 3, 'min_samples_leaf': 75, 'subsample': 0.75}

--- Final Test Set Evaluation for BJRI ---
              precision    recall  f1-score   support

           0       0.51      0.17      0.26      1498
           1       0.49      0.83      0.62      1442

    accuracy                           0.49      2940
   macro avg       0.50      0.50      0.44      2940
weighted avg       0.50      0.49      0.43      2940


Top 10 Feature Importances (Final Tuned Model):
| Feature                      |   Importance |
|:-----------------------------|-------------:|
| rolling_avg_vol_50_DIN       |    0.246028  |
| rsi_50_BJRI                  |    0.215015  |
| bb_width_50_WEN              |    0.160819  |
| skew_25_KRUS                 |    0.115264  |
| skew_50_EAT                  |    0.0951561 |
| change_lag_1050th_ptile_BJRI |    0.0733524 |
| skew_10_CNNE                 |    0.0502335 |
| change_lag_2510th_ptile_BJRI |    0.0441323 |
No existing model found for BJRI_15. Saving...

C:\Users\allth\AppData\Local\Temp\ipykernel_56232\2445029629.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

✅ Model saved to: ./models/restaurants/champion_model_BJRI_15.pkl
85

================ Starting analysis for symbol: BJRI ================
Train End Date:   2025-04-22 11:15:00+00:00
Val Start Date:   2025-05-13 11:15:00+00:00
Val End Date:     2025-10-02 11:45:00+00:00
Test Start Date:  2025-10-23 11:45:00+00:00
Running Greta on strictly historical training slice: 6482 rows...
Original rows: 6482 | Subsampled Base Rows (Max possible): 249
Calculating Noise Floor on 249 rows...
['rolling_avg_vol_50_DPZ', 'bb_width_25_CMG', 'rolling_avg_vol_50_REBN', 'volatility_50_TXRH', 'rolling_avg_vol_50_ARCO']
Calculating correlation matrix...
Starting greedy reduction with t=0.8, n=40...

Optimization Complete!
Started with: 226 features
Accepted: 40 features
Starting NaN pruning. Target minimum rows: 5106
Data Points: 12766 -> 11451 (Adequate rows secured!)
Data Points: 11451 -> 11451 (Dropped 0 rows due to NaN features)
train rows:  5182
val rows:  2551
test rows:  2940
before while true
2551
before val loop
Iteration 1: Features=40 | Best Val Score=0.4264
   >>> New Champion Selected! (Score: 0.4264 is within 0.01 of Max 0.4264)
Iteration 1: Pruning 29 features.
2551
before val loop
Iteration 2: Features=11 | Best Val Score=0.4314
   >>> New Champion Selected! (Score: 0.4314 is within 0.01 of Max 0.4314)
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 11) with Score: 0.4314

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 1000, 'learning_rate': 0.005, 'max_depth': 3, 'min_samples_leaf': 50, 'subsample': 0.75}

--- Final Test Set Evaluation for BJRI ---
              precision    recall  f1-score   support

           0       0.31      0.97      0.47       828
           1       0.93      0.14      0.24      2112

    accuracy                           0.37      2940
   macro avg       0.62      0.56      0.35      2940
weighted avg       0.76      0.37      0.30      2940


Top 10 Feature Importances (Final Tuned Model):
| Feature                      |   Importance |
|:-----------------------------|-------------:|
| change_lag_1050th_ptile_BJRI |    0.209004  |
| rolling_avg_vol_50_REBN      |    0.147131  |
| rolling_avg_vol_25_YUMC      |    0.098962  |
| rolling_avg_vol_25_BLMN      |    0.0890809 |
| rsi_50_BJRI                  |    0.0866953 |
| skew_50_LOCO                 |    0.0866293 |
| bb_width_50_BROS             |    0.072188  |
| skew_50_JACK                 |    0.0645075 |
| rolling_avg_vol_10_YUMC      |    0.0525274 |
| weekday_adj_vol_50_RICK      |    0.048697  |
No existing model found for BJRI_85. Saving...

C:\Users\allth\AppData\Local\Temp\ipykernel_56232\2445029629.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

✅ Model saved to: ./models/restaurants/champion_model_BJRI_85.pkl
NDLS
15

================ Starting analysis for symbol: NDLS ================
Train End Date:   2025-04-22 11:15:00+00:00
Val Start Date:   2025-05-13 11:15:00+00:00
Val End Date:     2025-10-02 11:45:00+00:00
Test Start Date:  2025-10-23 11:45:00+00:00
Running Greta on strictly historical training slice: 6482 rows...
Original rows: 6482 | Subsampled Base Rows (Max possible): 249
Calculating Noise Floor on 249 rows...
['rolling_avg_vol_25_BH', 'rolling_avg_vol_50_BH', 'bb_width_50_EAT', 'weekday_adj_vol_25_CBRL', 'skew_50_THCH']
Calculating correlation matrix...
Starting greedy reduction with t=0.8, n=40...

Optimization Complete!
Started with: 243 features
Accepted: 40 features
Starting NaN pruning. Target minimum rows: 5106
Data Points: 12766 -> 12241 (Adequate rows secured!)
Data Points: 12241 -> 12241 (Dropped 0 rows due to NaN features)
train rows:  5972
val rows:  2551
test rows:  2940
before while true
2551
before val loop
Iteration 1: Features=40 | Best Val Score=0.7732
   >>> New Champion Selected! (Score: 0.7732 is within 0.01 of Max 0.7732)
Iteration 1: Pruning 30 features.
2551
before val loop
Iteration 2: Features=10 | Best Val Score=0.8178
   >>> New Champion Selected! (Score: 0.8178 is within 0.01 of Max 0.8178)
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 10) with Score: 0.8178

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 3, 'min_samples_leaf': 50, 'subsample': 0.75}

--- Final Test Set Evaluation for NDLS ---
              precision    recall  f1-score   support

           0       1.00      0.00      0.01      1235
           1       0.58      1.00      0.73      1705

    accuracy                           0.58      2940
   macro avg       0.79      0.50      0.37      2940
weighted avg       0.76      0.58      0.43      2940


Top 10 Feature Importances (Final Tuned Model):
| Feature                      |   Importance |
|:-----------------------------|-------------:|
| rolling_avg_vol_10_STKS      |    0.182461  |
| bb_width_50_PZZA             |    0.17422   |
| bb_width_50_DPZ              |    0.139649  |
| rolling_avg_vol_25_RRGB      |    0.125145  |
| bb_width_50_NATH             |    0.0825652 |
| change_lag_2570th_ptile_RRGB |    0.0727257 |
| skew_50_STKS                 |    0.0648231 |
| change_lag_5070th_ptile_YUMC |    0.0627253 |
| bb_width_50_EAT              |    0.0565733 |
| skew_50_GTIM                 |    0.0391124 |
No existing model found for NDLS_15. Saving...

C:\Users\allth\AppData\Local\Temp\ipykernel_56232\2445029629.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

✅ Model saved to: ./models/restaurants/champion_model_NDLS_15.pkl
85

================ Starting analysis for symbol: NDLS ================
Train End Date:   2025-04-22 11:15:00+00:00
Val Start Date:   2025-05-13 11:15:00+00:00
Val End Date:     2025-10-02 11:45:00+00:00
Test Start Date:  2025-10-23 11:45:00+00:00
Running Greta on strictly historical training slice: 6482 rows...
Original rows: 6482 | Subsampled Base Rows (Max possible): 249
Calculating Noise Floor on 249 rows...
['volatility_50_CMG', 'skew_50_GTIM', 'rolling_avg_vol_25_BH', 'bb_width_25_BJRI', 'change_lag_5070th_ptile_REBN']
Calculating correlation matrix...
Starting greedy reduction with t=0.8, n=40...

Optimization Complete!
Started with: 243 features
Accepted: 40 features
Starting NaN pruning. Target minimum rows: 5106
Data Points: 12766 -> 11451 (Adequate rows secured!)
Data Points: 11451 -> 11451 (Dropped 0 rows due to NaN features)
train rows:  5182
val rows:  2551
test rows:  2940
before while true
2551
before val loop
Iteration 1: Features=40 | Best Val Score=0.6648
   >>> New Champion Selected! (Score: 0.6648 is within 0.01 of Max 0.6648)
Iteration 1: Pruning 28 features.
2551
before val loop
Iteration 2: Features=12 | Best Val Score=0.7491
   >>> New Champion Selected! (Score: 0.7491 is within 0.01 of Max 0.7491)
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 12) with Score: 0.7491

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 3, 'min_samples_leaf': 75, 'subsample': 0.75}

--- Final Test Set Evaluation for NDLS ---
              precision    recall  f1-score   support

           0       0.28      0.66      0.39       894
           1       0.63      0.25      0.36      2046

    accuracy                           0.38      2940
   macro avg       0.46      0.46      0.38      2940
weighted avg       0.53      0.38      0.37      2940


Top 10 Feature Importances (Final Tuned Model):
| Feature                  |   Importance |
|:-------------------------|-------------:|
| bb_width_25_WEN          |    0.16142   |
| bb_width_25_BJRI         |    0.144216  |
| efficiency_ratio_50_JACK |    0.103968  |
| rolling_avg_vol_10_STKS  |    0.0907085 |
| bb_width_50_DPZ          |    0.080722  |
| skew_50_WEN              |    0.0795245 |
| bb_width_25_BROS         |    0.0655923 |
| volatility_10_PETZ       |    0.0640643 |
| rolling_avg_vol_25_SBUX  |    0.0615038 |
| rolling_avg_vol_50_CMG   |    0.0579552 |
No existing model found for NDLS_85. Saving...

C:\Users\allth\AppData\Local\Temp\ipykernel_56232\2445029629.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

✅ Model saved to: ./models/restaurants/champion_model_NDLS_85.pkl
SHAK
15

================ Starting analysis for symbol: SHAK ================
Train End Date:   2025-04-22 11:15:00+00:00
Val Start Date:   2025-05-13 11:15:00+00:00
Val End Date:     2025-10-02 11:45:00+00:00
Test Start Date:  2025-10-23 11:45:00+00:00
Running Greta on strictly historical training slice: 6482 rows...
Original rows: 6482 | Subsampled Base Rows (Max possible): 250
Calculating Noise Floor on 249 rows...
['rolling_avg_vol_50_BH', 'bb_width_50_WING', 'rolling_avg_vol_50_NATH', 'skew_50_SBUX', 'rolling_avg_vol_50_NDLS']
Calculating correlation matrix...
Starting greedy reduction with t=0.8, n=40...

Optimization Complete!
Started with: 243 features
Accepted: 40 features
Starting NaN pruning. Target minimum rows: 5106
Data Points: 12766 -> 12732 (Adequate rows secured!)
Data Points: 12732 -> 12732 (Dropped 0 rows due to NaN features)
train rows:  6463
val rows:  2551
test rows:  2940
before while true
2551
before val loop
Iteration 1: Features=40 | Best Val Score=0.8705
   >>> New Champion Selected! (Score: 0.8705 is within 0.01 of Max 0.8705)
Iteration 1: Pruning 28 features.
2551
before val loop
Iteration 2: Features=12 | Best Val Score=0.8478
   >>> Score drop > 0.01 (Val: 0.8478 vs Max: 0.8705). Keeping previous Champion.
Iteration 2: Pruning 1 features.
2551
before val loop
Iteration 3: Features=11 | Best Val Score=0.8478
   >>> Score drop > 0.01 (Val: 0.8478 vs Max: 0.8705). Keeping previous Champion.
Iteration 3: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 40) with Score: 0.8705

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 2, 'min_samples_leaf': 75, 'subsample': 0.75}

--- Final Test Set Evaluation for SHAK ---
              precision    recall  f1-score   support

           0       0.55      0.07      0.13      1063
           1       0.65      0.97      0.78      1877

    accuracy                           0.64      2940
   macro avg       0.60      0.52      0.45      2940
weighted avg       0.61      0.64      0.54      2940


Top 10 Feature Importances (Final Tuned Model):
| Feature                 |   Importance |
|:------------------------|-------------:|
| rolling_avg_vol_50_NDLS |    0.28622   |
| z_score_50_SHAK         |    0.0976867 |
| z_score_50_BROS         |    0.0612455 |
| rolling_avg_vol_50_STKS |    0.0510009 |
| bb_width_25_CMG         |    0.0472471 |
| rolling_avg_vol_50_BH   |    0.0403539 |
| weekday_adj_vol_25_SHAK |    0.0398921 |
| bb_width_50_BROS        |    0.0384014 |
| bb_width_50_NATH        |    0.0373806 |
| skew_50_BROS            |    0.0360315 |
No existing model found for SHAK_15. Saving...
✅ Model saved to: ./models/restaurants/champion_model_SHAK_15.pkl
85

================ Starting analysis for symbol: SHAK ================

C:\Users\allth\AppData\Local\Temp\ipykernel_56232\2445029629.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

Train End Date:   2025-04-22 11:15:00+00:00
Val Start Date:   2025-05-13 11:15:00+00:00
Val End Date:     2025-10-02 11:45:00+00:00
Test Start Date:  2025-10-23 11:45:00+00:00
Running Greta on strictly historical training slice: 6482 rows...
Original rows: 6482 | Subsampled Base Rows (Max possible): 250
Calculating Noise Floor on 249 rows...
['bb_width_50_WING', 'rolling_avg_vol_50_NATH', 'skew_50_CMG', 'skew_50_FWRG', 'skew_25_TXRH']
Calculating correlation matrix...
Starting greedy reduction with t=0.8, n=40...

Optimization Complete!
Started with: 243 features
Accepted: 40 features
Starting NaN pruning. Target minimum rows: 5106
Data Points: 12766 -> 12241 (Adequate rows secured!)
Data Points: 12241 -> 12241 (Dropped 0 rows due to NaN features)
train rows:  5972
val rows:  2551
test rows:  2940
before while true
2551
before val loop
Iteration 1: Features=40 | Best Val Score=0.2753
   >>> New Champion Selected! (Score: 0.2753 is within 0.01 of Max 0.2753)
Iteration 1: Pruning 29 features.
2551
before val loop
Iteration 2: Features=11 | Best Val Score=0.4032
   >>> New Champion Selected! (Score: 0.4032 is within 0.01 of Max 0.4032)
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 11) with Score: 0.4032

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 1000, 'learning_rate': 0.005, 'max_depth': 2, 'min_samples_leaf': 75, 'subsample': 1.0}

--- Final Test Set Evaluation for SHAK ---
              precision    recall  f1-score   support

           0       0.46      0.95      0.62      1101
           1       0.92      0.34      0.50      1839

    accuracy                           0.57      2940
   macro avg       0.69      0.65      0.56      2940
weighted avg       0.75      0.57      0.54      2940


Top 10 Feature Importances (Final Tuned Model):
| Feature                 |   Importance |
|:------------------------|-------------:|
| rolling_avg_vol_50_NDLS |    0.209795  |
| rolling_avg_vol_50_WING |    0.155029  |
| bb_width_50_PETZ        |    0.129985  |
| bb_width_50_THCH        |    0.098682  |
| rolling_avg_vol_50_STKS |    0.0928575 |
| skew_50_MCD             |    0.0799536 |
| rolling_avg_vol_50_YUM  |    0.0583799 |
| rolling_avg_vol_50_BH   |    0.0532587 |
| volatility_25_PETZ      |    0.0503541 |
| rsi_50_WEN              |    0.0390257 |
No existing model found for SHAK_85. Saving...
✅ Model saved to: ./models/restaurants/champion_model_SHAK_85.pkl
DIN
15

================ Starting analysis for symbol: DIN ================

C:\Users\allth\AppData\Local\Temp\ipykernel_56232\2445029629.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

Train End Date:   2025-04-22 11:15:00+00:00
Val Start Date:   2025-05-13 11:15:00+00:00
Val End Date:     2025-10-02 11:45:00+00:00
Test Start Date:  2025-10-23 11:45:00+00:00
Running Greta on strictly historical training slice: 6482 rows...
Original rows: 6482 | Subsampled Base Rows (Max possible): 249
Calculating Noise Floor on 249 rows...
[]
Calculating correlation matrix...
Starting greedy reduction with t=0.8, n=40...

Optimization Complete!
Started with: 0 features
Accepted: 0 features
Greta found 0 features above noise floor. Skipping DIN_15.
85

================ Starting analysis for symbol: DIN ================
Train End Date:   2025-04-22 11:15:00+00:00
Val Start Date:   2025-05-13 11:15:00+00:00
Val End Date:     2025-10-02 11:45:00+00:00
Test Start Date:  2025-10-23 11:45:00+00:00
Running Greta on strictly historical training slice: 6482 rows...
Original rows: 6482 | Subsampled Base Rows (Max possible): 250
Calculating Noise Floor on 249 rows...
['skew_25_GENK', 'skew_50_DPZ', 'rolling_avg_vol_25_THCH', 'skew_50_GENK', 'volatility_50_KRUS']
Calculating correlation matrix...
Starting greedy reduction with t=0.8, n=40...

Optimization Complete!
Started with: 243 features
Accepted: 40 features
Starting NaN pruning. Target minimum rows: 5106
Data Points: 12766 -> 11451 (Adequate rows secured!)
Data Points: 11451 -> 11451 (Dropped 0 rows due to NaN features)
train rows:  5182
val rows:  2551
test rows:  2940
before while true
2551
before val loop
Iteration 1: Features=40 | Best Val Score=0.6314
   >>> New Champion Selected! (Score: 0.6314 is within 0.01 of Max 0.6314)
Iteration 1: Pruning 30 features.
2551
before val loop
Iteration 2: Features=10 | Best Val Score=0.7365
   >>> New Champion Selected! (Score: 0.7365 is within 0.01 of Max 0.7365)
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 10) with Score: 0.7365

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 1000, 'learning_rate': 0.005, 'max_depth': 2, 'min_samples_leaf': 75, 'subsample': 0.75}

--- Final Test Set Evaluation for DIN ---
              precision    recall  f1-score   support

           0       0.43      0.86      0.57      1289
           1       0.51      0.12      0.19      1651

    accuracy                           0.44      2940
   macro avg       0.47      0.49      0.38      2940
weighted avg       0.47      0.44      0.36      2940


Top 10 Feature Importances (Final Tuned Model):
| Feature                      |   Importance |
|:-----------------------------|-------------:|
| skew_50_GENK                 |    0.172206  |
| volatility_25_CHSN           |    0.1613    |
| skew_50_DIN                  |    0.132345  |
| change_lag_5090th_ptile_PZZA |    0.127973  |
| z_score_50_DIN               |    0.111028  |
| skew_50_MCD                  |    0.0760017 |
| change_lag_1050th_ptile_LOCO |    0.0663446 |
| bb_width_50_CBRL             |    0.0553929 |
| weekday_adj_vol_50_CBRL      |    0.0498219 |
| rolling_avg_vol_25_THCH      |    0.0475877 |
No existing model found for DIN_85. Saving...
✅ Model saved to: ./models/restaurants/champion_model_DIN_85.pkl

================== CONSOLIDATED RESULTS ==================
| Symbol   |   ptile |   Final_Feature_Count | Best_Params                                                                                               |   Test_Precision_Class1 |   Test_Recall_Class1 |   Test_F1_Class1 |   Test_Fbeta_0.5 | Top_Feature_Importances                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |   total_test_rows |   test_class1_pct |   tp_var_days_sq |   tp_range_days |   tp_avg_gap_hours |   n_true_positives |
|:---------|--------:|----------------------:|:----------------------------------------------------------------------------------------------------------|------------------------:|---------------------:|-----------------:|-----------------:|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------:|------------------:|-----------------:|----------------:|-------------------:|-------------------:|
| BTBD     |      15 |                    13 | {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 3, 'min_samples_leaf': 75, 'subsample': 1.0}   |                0.67336  |            0.531151  |         0.593861 |         0.639136 | {'change_lag_1090th_ptile_BTBD': 0.196019849741356, 'weekday_adj_vol_10_MCD': 0.12000392507631615, 'rolling_avg_vol_25_THCH': 0.09718231005193816, 'skew_10_CMG': 0.08177425365464448, 'volatility_10_RICK': 0.07791122602512339, 'volatility_50_PTLO': 0.07369624696766817, 'rolling_avg_vol_25_SBUX': 0.06946592774202871, 'volatility_25_KRUS': 0.06124516377758201, 'weekday_adj_vol_10_CMG': 0.0515256180941675}                                                                                |              2940 |           64.4218 |       2309.89    |        167.938  |            4.01045 |               1006 |
| BTBD     |      85 |                    12 | {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 3, 'min_samples_leaf': 50, 'subsample': 0.75}  |                0.379613 |            0.113386  |         0.174616 |         0.258311 | {'volatility_25_MCD': 0.16296959434462538, 'skew_25_JACK': 0.13386369268611326, 'bb_width_50_BH': 0.10761574013693276, 'weekday_adj_vol_10_DPZ': 0.09600742322443244, 'skew_50_YUM': 0.09215423664965143, 'rolling_avg_vol_25_RICK': 0.07729322176306674, 'volatility_50_PZZA': 0.0649326042019638, 'bb_width_25_CBRL': 0.05843448797970796, 'rolling_avg_vol_25_BH': 0.0549965320094048, 'rolling_avg_vol_25_SHAK': 0.05318162553227354, 'rolling_avg_vol_25_YUM': 0.05270980810869682}             |              2940 |           64.7959 |       1914.7     |        110.906  |           12.3802  |                216 |
| TXRH     |      15 |                    10 | {'n_estimators': 1000, 'learning_rate': 0.005, 'max_depth': 3, 'min_samples_leaf': 75, 'subsample': 1.0}  |                0.635207 |            0.923077  |         0.752552 |         0.677462 | {'bb_width_25_CNNE': 0.21989819688806816, 'volatility_10_RICK': 0.2047160152966545, 'bb_width_25_RAVE': 0.09932195751815542, 'weekday_adj_vol_25_CAVA': 0.08892992179715112, 'change_lag_2590th_ptile_DRI': 0.08298041463273445, 'bb_width_50_CAVA': 0.08235889838919143, 'skew_50_PETZ': 0.07393114770615061, 'rolling_avg_vol_50_THCH': 0.07124266336132691}                                                                                                                                       |              2940 |           57.0408 |       1996.04    |        167.01   |            2.59098 |               1548 |
| TXRH     |      85 |                     8 | {'n_estimators': 1000, 'learning_rate': 0.005, 'max_depth': 3, 'min_samples_leaf': 75, 'subsample': 1.0}  |                0.944099 |            0.114372  |         0.204027 |         0.3852   | {'bb_width_50_PZZA': 0.22203988219728418, 'weekday_adj_vol_50_YUM': 0.16051901236960942, 'skew_25_MCD': 0.15696519725159763, 'z_score_50_TXRH': 0.15679897165307813, 'change_lag_5090th_ptile_GENK': 0.10115488192597132, 'weekday_adj_vol_25_WING': 0.08117796263646634, 'weekday_adj_vol_50_CBRL': 0.06341590808365909, 'bb_width_25_CNNE': 0.05792818388233388}                                                                                                                                   |              2940 |           45.2041 |          9.76031 |         10.0417 |            1.59603 |                152 |
| BLMN     |      15 |                    40 | {'n_estimators': 1000, 'learning_rate': 0.005, 'max_depth': 2, 'min_samples_leaf': 50, 'subsample': 0.75} |                0.734168 |            0.992743  |         0.844097 |         0.774515 | {'efficiency_ratio_50_BLMN': 0.24321068128167703, 'bb_width_50_SG': 0.1797210636647135, 'weekday_adj_vol_50_PTLO': 0.09976807816142788, 'change_lag_5030th_ptile_DIN': 0.09107158445710928, 'change_lag_1090th_ptile_DIN': 0.06057903484091223}                                                                                                                                                                                                                                                      |              2940 |           70.3061 |       2117.47    |        166.917  |            1.95319 |               2052 |
| BLMN     |      85 |                    12 | {'n_estimators': 1000, 'learning_rate': 0.005, 'max_depth': 3, 'min_samples_leaf': 50, 'subsample': 0.75} |                0.810989 |            0.412291  |         0.546667 |         0.679558 | {'change_lag_5070th_ptile_BLMN': 0.18793831966737426, 'efficiency_ratio_50_BLMN': 0.1797145014064875, 'rolling_avg_vol_25_DRI': 0.09957856367625295, 'bb_width_25_BH': 0.09424379778686601, 'skew_10_KRUS': 0.07356199901836406, 'skew_25_PZZA': 0.0732662680843345, 'bb_width_50_SG': 0.06587152733053118, 'bb_width_10_PETZ': 0.0644928937526723, 'volatility_25_CHSN': 0.05937707896131662}                                                                                                       |              2940 |           60.8844 |       1756.63    |        159.927  |            5.20794 |                738 |
| PZZA     |      15 |                    10 | {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 3, 'min_samples_leaf': 50, 'subsample': 0.75}  |                0.779901 |            0.978686  |         0.868058 |         0.812924 | {'volatility_50_KRUS': 0.22287292006350268, 'skew_25_JACK': 0.15733813688561682, 'change_lag_5070th_ptile_BJRI': 0.10956287210302565, 'volatility_10_CHSN': 0.08764384066101102, 'weekday_adj_vol_25_CBRL': 0.0788053522850329, 'volatility_50_RICK': 0.07790363588378904, 'rolling_avg_vol_50_BROS': 0.07732084883759396, 'bb_width_50_PETZ': 0.07175410620753712, 'volatility_25_BJRI': 0.06731129413045114}                                                                                       |              2940 |           76.5986 |       1928.31    |        162.229  |            1.76736 |               2204 |
| PZZA     |      85 |                    14 | {'n_estimators': 1000, 'learning_rate': 0.005, 'max_depth': 3, 'min_samples_leaf': 50, 'subsample': 1.0}  |                0.466789 |            0.73442   |         0.57079  |         0.503484 | {'skew_50_SBUX': 0.16301205335594116, 'volatility_50_RICK': 0.15561072961789457, 'bb_width_50_THCH': 0.08832043527034743, 'weekday_adj_vol_25_CBRL': 0.08086823299169633, 'volatility_10_CHSN': 0.0698153873321142, 'bb_width_50_YUMC': 0.06501293559504069, 'skew_50_BJRI': 0.06177853354440873, 'skew_50_YUM': 0.06069449406856684, 'volatility_25_DPZ': 0.05405285874150335, 'bb_width_50_WING': 0.052225059111739455}                                                                            |              2940 |           35.4762 |        339.858   |         87      |            2.72941 |                766 |
| GENK     |      15 |                    10 | {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 3, 'min_samples_leaf': 75, 'subsample': 0.75}  |                0.827891 |            1         |         0.905843 |         0.857405 | {'bb_width_50_LOCO': 0.19728831909425734, 'skew_50_FWRG': 0.17628157515902665, 'rolling_avg_vol_10_YUMC': 0.1406349349943017, 'bb_width_10_CMG': 0.10781339675734275, 'bb_width_50_BH.A': 0.08712166866764245, 'rolling_avg_vol_25_YUM': 0.075434174420286, 'skew_25_GTIM': 0.06567000303331333, 'weekday_adj_vol_25_CBRL': 0.054839862699125184}                                                                                                                                                    |              2940 |           82.7891 |       2478.97    |        167.146  |            1.64879 |               2434 |
| GENK     |      85 |                    11 | {'n_estimators': 1000, 'learning_rate': 0.005, 'max_depth': 2, 'min_samples_leaf': 50, 'subsample': 1.0}  |                0.567114 |            0.132238  |         0.214467 |         0.342105 | {'rolling_avg_vol_50_WING': 0.14154778919924513, 'bb_width_50_PTLO': 0.12458760102494192, 'bb_width_50_ARCO': 0.11697481577621811, 'rolling_avg_vol_25_YUM': 0.11157316991097409, 'volatility_25_BH.A': 0.09427102941239839, 'volatility_50_RRGB': 0.08118836204685537, 'volatility_50_WING': 0.07669134139011032, 'skew_50_GENK': 0.07181088737822607, 'bb_width_25_DIN': 0.07132440487661183, 'weekday_adj_vol_25_YUM': 0.06825950326877639}                                                       |              2940 |           43.4694 |         99.8237  |         31      |            4.42857 |                169 |
| PTLO     |      15 |                    12 | {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 2, 'min_samples_leaf': 75, 'subsample': 0.75}  |                0.639514 |            0.997214  |         0.779277 |         0.688938 | {'skew_50_RICK': 0.16227568138040485, 'volatility_50_KRUS': 0.14920210700504766, 'rolling_avg_vol_25_RICK': 0.12624939107204625, 'rolling_avg_vol_50_YUMC': 0.11407125921804878, 'rolling_avg_vol_25_CAKE': 0.09683830909335767, 'skew_50_SBUX': 0.06919312188986718, 'weekday_adj_vol_25_DRI': 0.06011061799683433, 'rolling_avg_vol_10_RAVE': 0.05010366048888911}                                                                                                                                 |              2940 |           61.0544 |       2117.53    |        158.167  |            2.12186 |               1790 |
| PTLO     |      85 |                    13 | {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 3, 'min_samples_leaf': 75, 'subsample': 1.0}   |                0.592715 |            0.212842  |         0.313211 |         0.436798 | {'rolling_avg_vol_50_WING': 0.11998741773403061, 'skew_50_RICK': 0.11635533462450635, 'rolling_avg_vol_25_EAT': 0.11355521280265884, 'skew_50_KRUS': 0.1085746975561156, 'rolling_avg_vol_10_NDLS': 0.10380027430403632, 'bb_width_50_SG': 0.0980663824375295, 'bb_width_25_PTLO': 0.07917888537124064, 'rolling_avg_vol_50_DRI': 0.0683911955286667}                                                                                                                                                |              2940 |           57.2109 |       1036.96    |         96.9583 |            6.51821 |                358 |
| WEN      |      15 |                     9 | {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 3, 'min_samples_leaf': 75, 'subsample': 0.75}  |                0.674834 |            0.986694  |         0.801497 |         0.720371 | {'skew_50_SBUX': 0.1994889141112065, 'rolling_avg_vol_50_WING': 0.15883940416297004, 'volatility_50_RRGB': 0.12502231158764895, 'bb_width_50_THCH': 0.11775738588851886, 'skew_25_MCD': 0.104830618429025, 'rolling_avg_vol_50_SBUX': 0.08175480502511787, 'volatility_50_REBN': 0.07715032629745312, 'bb_width_50_PETZ': 0.0728592270013132, 'change_lag_5090th_ptile_BH.A': 0.062297007496746264}                                                                                                  |              2940 |           66.4626 |       2263.28    |        165.99   |            2.06733 |               1928 |
| WEN      |      85 |                    40 | {'n_estimators': 1000, 'learning_rate': 0.005, 'max_depth': 2, 'min_samples_leaf': 75, 'subsample': 0.75} |                0.295876 |            0.286427  |         0.291075 |         0.293937 | {'change_lag_5090th_ptile_BH.A': 0.18431198799281417, 'skew_50_BLMN': 0.15192068345840304, 'skew_50_MCD': 0.08440668407854858, 'volatility_50_CNNE': 0.06927509371765513, 'weekday_adj_vol_50_CAKE': 0.05635086402817203}                                                                                                                                                                                                                                                                            |              2940 |           34.0816 |       1735.34    |        160      |           13.4266  |                287 |
| STKS     |      15 |                    11 | {'n_estimators': 1000, 'learning_rate': 0.01, 'max_depth': 3, 'min_samples_leaf': 50, 'subsample': 1.0}   |                0.770053 |            0.539073  |         0.634187 |         0.709272 | {'change_lag_5050th_ptile_JACK': 0.18988663619641497, 'change_lag_5070th_ptile_STKS': 0.18940894940960934, 'rolling_avg_vol_50_BJRI': 0.10975449229496177, 'skew_25_BLMN': 0.09309240193958324, 'bb_width_50_CHSN': 0.08243329003750537, 'skew_25_STKS': 0.07126862576260028, 'volatility_50_KRUS': 0.06908261986643272, 'skew_50_KRUS': 0.06186260159215008}                                                                                                                                        |              2940 |           72.6871 |       1929.32    |        166.906  |            3.48023 |               1152 |
| STKS     |      85 |                    11 | {'n_estimators': 1000, 'learning_rate': 0.005, 'max_depth': 2, 'min_samples_leaf': 50, 'subsample': 0.75} |                0.513105 |            0.763384  |         0.613709 |         0.549111 | {'rsi_50_STKS': 0.23098974918548962, 'change_lag_5050th_ptile_JACK': 0.22513171783402205, 'bb_width_25_BROS': 0.07608017496210247, 'volatility_25_RICK': 0.07325446765213925, 'volatility_50_EAT': 0.07137452428873024, 'weekday_adj_vol_25_CBRL': 0.07012124467805797, 'rolling_avg_vol_10_CNNE': 0.06884811903653341, 'bb_width_25_WEN': 0.05883023798054795}                                                                                                                                      |              2940 |           51.4626 |       2613.15    |        151.802  |            3.15706 |               1155 |
| DPZ      |      15 |                    12 | {'n_estimators': 1000, 'learning_rate': 0.005, 'max_depth': 2, 'min_samples_leaf': 75, 'subsample': 1.0}  |                0.591231 |            0.290278  |         0.389381 |         0.489691 | {'weekday_adj_vol_25_SHAK': 0.2501709377497651, 'rolling_avg_vol_50_NDLS': 0.17150938387828885, 'rolling_avg_vol_25_BTBD': 0.123114295767302, 'skew_25_JACK': 0.07983010875346115, 'weekday_adj_vol_50_DPZ': 0.07095280932305385, 'skew_50_HDL': 0.05906747597018976, 'change_lag_5090th_ptile_ARCO': 0.05089715611654904}                                                                                                                                                                           |              2940 |           48.9796 |       2177.05    |        166.146  |            9.56235 |                418 |

C:\Users\allth\AppData\Local\Temp\ipykernel_56232\2445029629.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

NameError: name 'stocks' is not defined

In [17]:
results_df.to_csv('results_giant_5_2_rest_.02.csv')

In [9]:
res=pd.read_csv('results_giant_5_2_rest_.02.csv')
res

,Unnamed: 0,Symbol,ptile,Final_Feature_Count,Best_Params,Test_Precision_Class1,Test_Recall_Class1,Test_F1_Class1,Test_Fbeta_0.5,Top_Feature_Importances,total_test_rows,test_class1_pct,tp_var_days_sq,tp_range_days,tp_avg_gap_hours,n_true_positives
0,0,BTBD,15,13,"{'n_estimators': 1000, 'learning_rate': 0.01, ...",0.673360,0.531151,0.593861,0.639136,{'change_lag_1090th_ptile_BTBD': 0.19601984974...,2940,64.421769,2309.894651,167.937500,4.010448,1006
1,1,BTBD,85,12,"{'n_estimators': 1000, 'learning_rate': 0.01, ...",0.379613,0.113386,0.174616,0.258311,"{'volatility_25_MCD': 0.16296959434462538, 'sk...",2940,64.795918,1914.703143,110.906250,12.380233,216
2,2,TXRH,15,10,"{'n_estimators': 1000, 'learning_rate': 0.005,...",0.635207,0.923077,0.752552,0.677462,"{'bb_width_25_CNNE': 0.21989819688806816, 'vol...",2940,57.040816,1996.038956,167.010417,2.590983,1548
3,3,TXRH,85,8,"{'n_estimators': 1000, 'learning_rate': 0.005,...",0.944099,0.114372,0.204027,0.385200,"{'bb_width_50_PZZA': 0.22203988219728418, 'wee...",2940,45.204082,9.760311,10.041667,1.596026,152
4,4,BLMN,15,40,"{'n_estimators': 1000, 'learning_rate': 0.005,...",0.734168,0.992743,0.844097,0.774515,{'efficiency_ratio_50_BLMN': 0.243210681281677...,2940,70.306122,2117.469929,166.916667,1.953194,2052
5,5,BLMN,85,12,"{'n_estimators': 1000, 'learning_rate': 0.005,...",0.810989,0.412291,0.546667,0.679558,{'change_lag_5070th_ptile_BLMN': 0.18793831966...,2940,60.884354,1756.625018,159.927083,5.207938,738
6,6,PZZA,15,10,"{'n_estimators': 1000, 'learning_rate': 0.01, ...",0.779901,0.978686,0.868058,0.812924,"{'volatility_50_KRUS': 0.22287292006350268, 's...",2940,76.598639,1928.309650,162.229167,1.767363,2204
7,7,PZZA,85,14,"{'n_estimators': 1000, 'learning_rate': 0.005,...",0.466789,0.734420,0.570790,0.503484,"{'skew_50_SBUX': 0.16301205335594116, 'volatil...",2940,35.476190,339.858263,87.000000,2.729412,766
8,8,GENK,15,10,"{'n_estimators': 1000, 'learning_rate': 0.01, ...",0.827891,1.000000,0.905843,0.857405,"{'bb_width_50_LOCO': 0.19728831909425734, 'ske...",2940,82.789116,2478.969562,167.145833,1.648788,2434
9,9,GENK,85,11,"{'n_estimators': 1000, 'learning_rate': 0.005,...",0.567114,0.132238,0.214467,0.342105,{'rolling_avg_vol_50_WING': 0.1415477891992451...,2940,43.469388,99.823703,31.000000,4.428571,169
10,10,PTLO,15,12,"{'n_estimators': 1000, 'learning_rate': 0.01, ...",0.639514,0.997214,0.779277,0.688938,"{'skew_50_RICK': 0.16227568138040485, 'volatil...",2940,61.054422,2117.532799,158.166667,2.121856,1790
11,11,PTLO,85,13,"{'n_estimators': 1000, 'learning_rate': 0.01, ...",0.592715,0.212842,0.313211,0.436798,{'rolling_avg_vol_50_WING': 0.1199874177340306...,2940,57.210884,1036.958495,96.958333,6.518207,358
12,12,WEN,15,9,"{'n_estimators': 1000, 'learning_rate': 0.01, ...",0.674834,0.986694,0.801497,0.720371,"{'skew_50_SBUX': 0.1994889141112065, 'rolling_...",2940,66.462585,2263.275030,165.989583,2.067333,1928
13,13,WEN,85,40,"{'n_estimators': 1000, 'learning_rate': 0.005,...",0.295876,0.286427,0.291075,0.293937,{'change_lag_5090th_ptile_BH.A': 0.18431198799...,2940,34.081633,1735.335442,160.000000,13.426573,287
14,14,STKS,15,11,"{'n_estimators': 1000, 'learning_rate': 0.01, ...",0.770053,0.539073,0.634187,0.709272,{'change_lag_5050th_ptile_JACK': 0.18988663619...,2940,72.687075,1929.322934,166.906250,3.480235,1152
15,15,STKS,85,11,"{'n_estimators': 1000, 'learning_rate': 0.005,...",0.513105,0.763384,0.613709,0.549111,"{'rsi_50_STKS': 0.23098974918548962, 'change_l...",2940,51.462585,2613.148440,151.802083,3.157062,1155
16,16,DPZ,15,12,"{'n_estimators': 1000, 'learning_rate': 0.005,...",0.591231,0.290278,0.389381,0.489691,{'weekday_adj_vol_25_SHAK': 0.2501709377497651...,2940,48.979592,2177.053990,166.145833,9.562350,418
17,17,DPZ,85,11,"{'n_estimators': 1000, 'learning_rate': 0.005,...",0.504202,0.087655,0.149347,0.258509,"{'volatility_25_THCH': 0.22827906002838214, 's...",2940,46.564626,1313.479312,93.989583,18.955882,120
18,18,QSR,15,12,"{'n_estimators': 1000, 'learning_rate': 0.01, ...",0.528905,0.719064,0.609497,0.558442,"{'skew_25_THCH': 0.13148485948158734, 'bb_widt...",2940,40.680272,1081.303285,167.916667,4.691502,860
19,19,QSR,85,9,"{'n_estimators': 1000, 'learning_rate': 0.01, ...",0.398740,0.242341,0.301463,0.353157,"{'skew_50_THCH': 0.25989059165477096, 'skew_50...",2940,62.176871,321.252063,104.833333,5.692308,443
20,20,BJRI,15,8,"{'n_estimators': 1000, 'learning_rate': 0.005,...",0.490148,0.828017,0.615781,0.533703,{'rolling_avg_vol_50_DIN': 0.24602802859502762...,2940,49.047619,1648.696728,166.906250,3.357712,1194
21,21,BJRI,85,11,"{'n_estimators': 1000, 'learning_rate': 0.005,...",0.931596,0.135417,0.236461,0.428144,{'change_lag_1050th_ptile_BJRI': 0.20900432625...,2940,71.836735,2492.497364,157.000000,13.221053,286
22,22,NDLS,15,10,"{'n_estimators': 1000, 'learning_rate': 0.01, ...",0.580920,1.000000,0.734914,0.634065,{'rolling_avg_vol_10_STKS': 0.1824611936744286...,2940,57.993197,2304.453676,167.916667,2.365023,1705
23,23,NDLS,85,12,"{'n_estimators': 1000, 'learning_rate': 0.01, ...",0.632927,0.253666,0.362177,0.487232,"{'bb_width_25_WEN': 0.16142005534523307, 'bb_w...",2940,69.591837,3029.396711,163.083333,7.555985,519
24,24,SHAK,15,40,"{'n_estimators': 1000, 'learning_rate': 0.01, ...",0.647731,0.965903,0.775449,0.693414,{'rolling_avg_vol_50_NDLS': 0.2862204271933002...,2940,63.843537,2066.187457,149.052083,1.974200,1813
25,25,SHAK,85,11,"{'n_estimators': 1000, 'learning_rate': 0.005,...",0.921944,0.340402,0.497220,0.687157,{'rolling_avg_vol_50_NDLS': 0.2097945695789974...,2940,62.551020,1889.059100,112.062500,4.303200,626
26,26,DIN,85,10,"{'n_estimators': 1000, 'learning_rate': 0.005,...",0.505319,0.115082,0.187469,0.301109,"{'skew_50_GENK': 0.17220555155715445, 'volatil...",2940,56.156463,2751.459342,154.000000,19.555556,190

In [9]:
import pandas as pd

# Load the testing results
df_results = pd.read_csv('results_giant_5_2_rest_.02.csv')

# Define thresholds
F1_THRESHOLD = 0.5
PRECISION_THRESHOLD = 0.7

# Filter for models with F-score > 0.5 and Precision (Class 1) > 0.7
high_quality_models = df_results[
    (df_results['Test_F1_Class1'] > F1_THRESHOLD) |
    (df_results['Test_Precision_Class1'] > PRECISION_THRESHOLD)
]

# Display the winning tickers and their stats
print(f"✅ Found {len(high_quality_models)} models meeting the criteria.")
print(high_quality_models[['Symbol', 'ptile', 'Test_Precision_Class1', 'Test_F1_Class1']])

high_quality_models.to_csv('sandr_next_top_models_'+industry+'_'+str(mi_cutoff)+'.csv')

import shutil

for i in high_quality_models.index:
    # Use .loc to safely access the row by index
    s = high_quality_models.loc[i, 'Symbol']
    p = high_quality_models.loc[i, 'ptile']
    
    source = f'models/{industry}/champion_model_{s}_{p}.pkl'
    destination = f'top_models/{industry}/'
    
    try:
        # copy2 copies the file AND its metadata (like timestamps)
        shutil.copy2(source, destination)
        print(f"✅ Success: {s}_{p} moved to top_models.")
    except FileNotFoundError:
        print(f"⚠️ Warning: Model file not found for {s}_{p} at {source}")

✅ Found 18 models meeting the criteria.
   Symbol  ptile  Test_Precision_Class1  Test_F1_Class1
0    BTBD     15               0.673360        0.593861
2    TXRH     15               0.635207        0.752552
3    TXRH     85               0.944099        0.204027
4    BLMN     15               0.734168        0.844097
5    BLMN     85               0.810989        0.546667
6    PZZA     15               0.779901        0.868058
7    PZZA     85               0.466789        0.570790
8    GENK     15               0.827891        0.905843
10   PTLO     15               0.639514        0.779277
12    WEN     15               0.674834        0.801497
14   STKS     15               0.770053        0.634187
15   STKS     85               0.513105        0.613709
18    QSR     15               0.528905        0.609497
20   BJRI     15               0.490148        0.615781
21   BJRI     85               0.931596        0.236461
22   NDLS     15               0.580920        0.734914
24   SHAK     15               0.647731        0.775449
25   SHAK     85               0.921944        0.497220

NameError: name 'mi_cutoff' is not defined

In [8]:
import json
from datetime import datetime
import os
from dotenv import load_dotenv
import joblib
import re
import time
from collections import deque
import glob
prefix=''#change to '' if you want all models
MODEL_PATHS = glob.glob(f'{prefix}models/{industry}/*.pkl')
MODEL_PATHS.sort()
print(f"✅ Loaded {len(MODEL_PATHS)} models from directory.")

# --- LIMIT SETTINGS ---
MAX_LIVE_TOTAL = 30 # SPY + 29 others
DYNAMIC_PATTERNS = ["change_lag_", "z_score_", "relative_volume_", "volume_force_", "rsi_", "session_adj_"]

live_watchlist_set = {'SPY'}
prep_watchlist_set = {'SPY'}
VALID_MODEL_PATHS = []

print("--- ANALYZING MODELS & ENFORCING LIMITS ---")

for path in MODEL_PATHS:
    try:
        m_data = joblib.load(path)
        features = m_data['features']
        
        # 1. Identify tickers needed for this specific model
        model_dynamic_tickers = set()
        model_all_tickers = set()
        
        for feat in features:
            ticker = feat.split('_')[-1]
            model_all_tickers.add(ticker)
            if any(p in feat for p in DYNAMIC_PATTERNS):
                model_dynamic_tickers.add(ticker)
        
        # 2. Check if this model's dynamic needs fit within our remaining limit
        potential_new_live = live_watchlist_set.union(model_dynamic_tickers)
        
        if len(potential_new_live) <= MAX_LIVE_TOTAL:
            # IT FITS: Commit these tickers to our global sets
            live_watchlist_set.update(model_dynamic_tickers)
            prep_watchlist_set.update(model_all_tickers)
            VALID_MODEL_PATHS.append(path)
        else:
            print(f"SKIPPING: {path} (Requires too many new live symbols. Current: {len(live_watchlist_set)})")
            
    except Exception as e:
        print(f"ERROR loading {path}: {e}")

LIVE_WATCHLIST = list(live_watchlist_set)
PREP_WATCHLIST = list(prep_watchlist_set)

print(f"\nFinal Live Stream List ({len(LIVE_WATCHLIST)}): {LIVE_WATCHLIST}")
print(f"Final Morning Prep List ({len(PREP_WATCHLIST)}): {PREP_WATCHLIST}")

#2.5. Generate daily FEATURE_PRESENTAION
import os
from datetime import datetime

# 1. Get today's date in YYYY-MM-DD format
today_str = datetime.now().strftime('%Y-%m-%d')

# 2. Construct the full folder path
# This creates a path like ggp_rel_tables/{today_str}_ggps/
folder_path = f'ggp_rel_tables/{today_str}_ggps/'

# 3. Create the directory (including all parent folders) if it doesn't exist
os.makedirs(folder_path, exist_ok=True)
global min_date
min_date=datetime.now().date()+pd.Timedelta(days=-117)
for s in PREP_WATCHLIST:
    if s!='SPY':
        print(s)
        try:
            #pd.read_csv(folder_path+'/ggp_'+s+'.csv')
            buudfoon
            continue
        except:
            ggp=getGalledPrices(s,15,[15],[10,25,50])
            ggp.columns = [col + '_' + str(s) for col in ggp.columns]
            ggp.to_csv(folder_path+'/ggp_'+s+'.csv')
getFeaturePres(industry,folder_path,'daily_feature_pres/')

import json

# Bundle the variables into a dictionary
config_data = {
    "LIVE_WATCHLIST": LIVE_WATCHLIST,
    "PREP_WATCHLIST": PREP_WATCHLIST,
    "VALID_MODEL_PATHS": VALID_MODEL_PATHS
}

# Save it to a file
with open('trading_config.json', 'w') as f:
    json.dump(config_data, f, indent=4)
    
print("✅ Saved watchlists and valid models to trading_config.json")

✅ Loaded 27 models from directory.
--- ANALYZING MODELS & ENFORCING LIMITS ---

Final Live Stream List (26): ['GENK', 'BTBD', 'LOCO', 'PZZA', 'DPZ', 'BJRI', 'DIN', 'SPY', 'REBN', 'BLMN', 'RRGB', 'NDLS', 'BROS', 'CMG', 'HDL', 'DRI', 'BH.A', 'CHSN', 'YUMC', 'SHAK', 'WEN', 'TXRH', 'JACK', 'SBUX', 'STKS', 'ARCO']
Final Morning Prep List (47): ['LOCO', 'DPZ', 'CAKE', 'RICK', 'BROS', 'CHSN', 'NATH', 'BTBD', 'CNNE', 'PETZ', 'WING', 'CBRL', 'EAT', 'SPY', 'NDLS', 'CMG', 'HDL', 'SG', 'GTIM', 'BH', 'KRUS', 'SBUX', 'THCH', 'ARCO', 'GENK', 'PZZA', 'MCD', 'PTLO', 'DIN', 'YUM', 'CAVA', 'WEN', 'FWRG', 'JACK', 'QSR', 'ARKR', 'BJRI', 'REBN', 'BLMN', 'RRGB', 'DRI', 'BH.A', 'YUMC', 'SHAK', 'RAVE', 'TXRH', 'STKS']
LOCO
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
DPZ
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
CAKE
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
RICK
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
BROS
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
CHSN
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop

CHSN: $CHSN: possibly delisted; no earnings dates found
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:287: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_open_30m'] = (pza_agg['minutes_since_open'] <= 30).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:288: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_close_30m'] = (pza_agg['minutes_since_open'] >= 360).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:289: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_mid_day'] = ((pza_agg['minutes_since_open'] > 30) & (pza_agg['minutes_since_open'] < 360)).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']

No earnings data found or processing failed.
NATH
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
BTBD
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop

BTBD: $BTBD: possibly delisted; no earnings dates found
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:287: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_open_30m'] = (pza_agg['minutes_since_open'] <= 30).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:288: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_close_30m'] = (pza_agg['minutes_since_open'] >= 360).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:289: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_mid_day'] = ((pza_agg['minutes_since_open'] > 30) & (pza_agg['minutes_since_open'] < 360)).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']

No earnings data found or processing failed.
CNNE
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
PETZ
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop

PETZ: $PETZ: possibly delisted; no earnings dates found
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:287: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_open_30m'] = (pza_agg['minutes_since_open'] <= 30).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:288: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_close_30m'] = (pza_agg['minutes_since_open'] >= 360).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:289: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_mid_day'] = ((pza_agg['minutes_since_open'] > 30) & (pza_agg['minutes_since_open'] < 360)).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']

No earnings data found or processing failed.
WING
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
CBRL
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
EAT
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
NDLS
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
CMG
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
HDL
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop

HDL: $HDL: possibly delisted; no earnings dates found
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:287: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_open_30m'] = (pza_agg['minutes_since_open'] <= 30).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:288: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_close_30m'] = (pza_agg['minutes_since_open'] >= 360).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:289: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_mid_day'] = ((pza_agg['minutes_since_open'] > 30) & (pza_agg['minutes_since_open'] < 360)).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']

No earnings data found or processing failed.
SG
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
GTIM
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
BH
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
KRUS
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
SBUX
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
THCH
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
ARCO
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
GENK
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
PZZA
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
MCD
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
PTLO
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
DIN
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
YUM
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
CAVA
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
WEN
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
FWRG
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
JACK
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
QSR
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
ARKR
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop

C:\Users\allth\anaconda3\Lib\site-packages\yfinance\base.py:765: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Earnings Date'] = pd.to_datetime(df['Event Start Date'])

BJRI
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
REBN
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
BLMN
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
RRGB
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
DRI
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
BH.A
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop

BH.A: $BH.A: possibly delisted; no earnings dates found
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:287: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_open_30m'] = (pza_agg['minutes_since_open'] <= 30).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:288: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_close_30m'] = (pza_agg['minutes_since_open'] >= 360).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:289: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_mid_day'] = ((pza_agg['minutes_since_open'] > 30) & (pza_agg['minutes_since_open'] < 360)).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_52988\3548428200.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']

No earnings data found or processing failed.
YUMC
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
SHAK
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
RAVE
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
TXRH
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
STKS
got minute-level
after weekends
15
got minute-level
after weekends
15
2054
before loop
Found 46 files: ['ggp_ARCO.csv', 'ggp_ARKR.csv', 'ggp_BH.A.csv', 'ggp_BH.csv', 'ggp_BJRI.csv', 'ggp_BLMN.csv', 'ggp_BROS.csv', 'ggp_BTBD.csv', 'ggp_CAKE.csv', 'ggp_CAVA.csv', 'ggp_CBRL.csv', 'ggp_CHSN.csv', 'ggp_CMG.csv', 'ggp_CNNE.csv', 'ggp_DIN.csv', 'ggp_DPZ.csv', 'ggp_DRI.csv', 'ggp_EAT.csv', 'ggp_FWRG.csv', 'ggp_GENK.csv', 'ggp_GTIM.csv', 'ggp_HDL.csv', 'ggp_JACK.csv', 'ggp_KRUS.csv', 'ggp_LOCO.csv', 'ggp_MCD.csv', 'ggp_NATH.csv', 'ggp_NDLS.csv', 'ggp_PETZ.csv', 'ggp_PTLO.csv', 'ggp_PZZA.csv', 'ggp_QSR.csv', 'ggp_RAVE.csv', 'ggp_REBN.csv', 'ggp_RICK.csv', 'ggp_RRGB.csv', 'ggp_SBUX.csv', 'ggp_SG.csv', 'ggp_SHAK.csv', 'ggp_STKS.csv', 'ggp_THCH.csv', 'ggp_TXRH.csv', 'ggp_WEN.csv', 'ggp_WING.csv', 'ggp_YUM.csv', 'ggp_YUMC.csv']
Base stock: ARCO
Joining ARKR...
2026-05-26 15:30:00
Joining BH.A...
2026-05-26 15:45:00
Joining BH...
2026-05-26 15:45:00
Joining BJRI...
2026-05-26 15:45:00
Joining BLMN...
2026-05-26 15:45:00
Joining BROS...
2026-05-26 15:45:00
Joining BTBD...
2026-05-26 15:45:00
Joining CAKE...
2026-05-26 15:45:00
Joining CAVA...
2026-05-26 15:45:00
Joining CBRL...
2026-05-26 15:45:00
Joining CHSN...
2026-05-26 15:45:00
Joining CMG...
2026-05-26 15:45:00
Joining CNNE...
2026-05-26 15:45:00
Joining DIN...
2026-05-26 15:45:00
Joining DPZ...
2026-05-26 15:45:00
Joining DRI...
2026-05-26 15:45:00
Joining EAT...
2026-05-26 15:45:00
Joining FWRG...
2026-05-26 15:45:00
Joining GENK...
2026-05-26 15:45:00
Joining GTIM...
2026-05-26 15:45:00
Joining HDL...
2026-05-20 12:00:00
Joining JACK...
2026-05-26 15:45:00
Joining KRUS...
2026-05-26 15:45:00
Joining LOCO...
2026-05-26 15:45:00
Joining MCD...
2026-05-26 15:45:00
Joining NATH...
2026-05-26 15:00:00
Joining NDLS...
2026-05-26 15:45:00
Joining PETZ...
2026-05-26 15:45:00
Joining PTLO...
2026-05-26 15:45:00
Joining PZZA...
2026-05-26 15:45:00
Joining QSR...
2026-05-26 15:45:00
Joining RAVE...
2026-05-26 15:45:00
Joining REBN...
2026-05-26 15:45:00
Joining RICK...
2026-05-26 15:45:00
Joining RRGB...
2026-05-26 15:45:00
Joining SBUX...
2026-05-26 15:45:00
Joining SG...
2026-05-26 15:45:00
Joining SHAK...
2026-05-26 15:45:00
Joining STKS...
2026-05-26 15:45:00
Joining THCH...
2026-05-26 12:45:00
Joining TXRH...
2026-05-26 15:45:00
Joining WEN...
2026-05-26 15:45:00
Joining WING...
2026-05-26 15:45:00
Joining YUM...
2026-05-26 15:45:00
Joining YUMC...
2026-05-26 15:45:00

Final joined DataFrame shape: (2054, 6349)
✅ Saved watchlists and valid models to trading_config.json

In [35]:
#getGalledPrices('PBPB',15,[15],[10,25,50])
getMinuteLevel('PBPB')

AttributeError: 'DataFrame' object has no attribute 'timestamp'

In [8]:
getFeaturePres(industry,folder_path,'daily_feature_pres/')

import json

# Bundle the variables into a dictionary
config_data = {
    "LIVE_WATCHLIST": LIVE_WATCHLIST,
    "PREP_WATCHLIST": PREP_WATCHLIST,
    "VALID_MODEL_PATHS": VALID_MODEL_PATHS
}

# Save it to a file
with open('trading_config.json', 'w') as f:
    json.dump(config_data, f, indent=4)
    
print("✅ Saved watchlists and valid models to trading_config.json")

Found 45 files: ['ggp_ARCO.csv', 'ggp_ARKR.csv', 'ggp_BH.A.csv', 'ggp_BH.csv', 'ggp_BJRI.csv', 'ggp_BLMN.csv', 'ggp_BROS.csv', 'ggp_BTBD.csv', 'ggp_CAKE.csv', 'ggp_CAVA.csv', 'ggp_CBRL.csv', 'ggp_CHSN.csv', 'ggp_CMG.csv', 'ggp_CNNE.csv', 'ggp_DIN.csv', 'ggp_DPZ.csv', 'ggp_DRI.csv', 'ggp_EAT.csv', 'ggp_FWRG.csv', 'ggp_GENK.csv', 'ggp_GTIM.csv', 'ggp_HDL.csv', 'ggp_JACK.csv', 'ggp_KRUS.csv', 'ggp_LOCO.csv', 'ggp_MCD.csv', 'ggp_NATH.csv', 'ggp_NDLS.csv', 'ggp_PETZ.csv', 'ggp_PTLO.csv', 'ggp_PZZA.csv', 'ggp_RAVE.csv', 'ggp_REBN.csv', 'ggp_RICK.csv', 'ggp_RRGB.csv', 'ggp_SBUX.csv', 'ggp_SG.csv', 'ggp_SHAK.csv', 'ggp_STKS.csv', 'ggp_THCH.csv', 'ggp_TXRH.csv', 'ggp_WEN.csv', 'ggp_WING.csv', 'ggp_YUM.csv', 'ggp_YUMC.csv']
Base stock: ARCO
Joining ARKR...
2026-05-19 10:00:00
Joining BH.A...
2026-05-19 15:45:00
Joining BH...
2026-05-19 15:45:00
Joining BJRI...
2026-05-19 15:45:00
Joining BLMN...
2026-05-19 15:45:00
Joining BROS...
2026-05-19 15:45:00
Joining BTBD...
2026-05-19 15:45:00
Joining CAKE...
2026-05-19 15:45:00
Joining CAVA...
2026-05-19 15:45:00
Joining CBRL...
2026-05-19 15:45:00
Joining CHSN...
2026-05-19 15:45:00
Joining CMG...
2026-05-19 15:45:00
Joining CNNE...
2026-05-19 15:45:00
Joining DIN...
2026-05-19 15:45:00
Joining DPZ...
2026-05-19 15:45:00
Joining DRI...
2026-05-19 15:45:00
Joining EAT...
2026-05-19 15:45:00
Joining FWRG...
2026-05-19 15:45:00
Joining GENK...
2026-05-19 15:45:00
Joining GTIM...
2026-05-19 15:45:00
Joining HDL...
2026-05-19 15:30:00
Joining JACK...
2026-05-19 15:45:00
Joining KRUS...
2026-05-19 15:45:00
Joining LOCO...
2026-05-19 15:45:00
Joining MCD...
2026-05-19 15:45:00
Joining NATH...
2026-05-19 15:45:00
Joining NDLS...
2026-05-19 15:45:00
Joining PETZ...
2026-05-19 15:45:00
Joining PTLO...
2026-05-19 15:45:00
Joining PZZA...
2026-05-19 15:45:00
Joining RAVE...
2026-05-19 15:45:00
Joining REBN...
2026-05-19 13:30:00
Joining RICK...
2026-05-19 15:45:00
Joining RRGB...
2026-05-19 15:45:00
Joining SBUX...
2026-05-19 15:45:00
Joining SG...
2026-05-19 15:45:00
Joining SHAK...
2026-05-19 15:45:00
Joining STKS...
2026-05-19 15:45:00
Joining THCH...
2026-05-19 15:30:00
Joining TXRH...
2026-05-19 15:45:00
Joining WEN...
2026-05-19 15:45:00
Joining WING...
2026-05-19 15:45:00
Joining YUM...
2026-05-19 15:45:00
Joining YUMC...
2026-05-19 15:45:00

Final joined DataFrame shape: (2080, 6211)
✅ Saved watchlists and valid models to trading_config.json