In [1]:
#PREPROCESS 1
from alpaca.data.requests import StockBarsRequest
from alpaca.data.requests import CryptoBarsRequest
from alpaca.data.timeframe import TimeFrame
from alpaca.data.timeframe import TimeFrameUnit
from datetime import datetime

import pandas as pd
import numpy as np
global min_date
global max_date
import pandas as pd
import alpaca.data.historical as alp
import os
from dotenv import load_dotenv
load_dotenv()

API_KEY = os.getenv("ALPACA_API_KEY")
SECRET_KEY = os.getenv("ALPACA_SECRET_KEY")
#client = alp.StockHistoricalDataClient(api_key="AKH3ZFJ2LWAKH7SSV2AHKD4PK4", secret_key="7gGJDh5UAxh3gg8V21d3AcuPfNJcwtKqukiqMhdhsjrW")
client = alp.StockHistoricalDataClient(api_key=API_KEY, secret_key=SECRET_KEY)

min_date=datetime.now().date()+pd.Timedelta(days=-720)
max_date=datetime.now().date()+pd.Timedelta(days=-1)
def getMinuteLevel(asset):
    global min_date
    global max_date
    request_params = StockBarsRequest(
      symbol_or_symbols=[asset],
      timeframe=TimeFrame(1, TimeFrameUnit.Minute),
      #timeframe=TimeFrame(59, TimeFrameUnit.Minute),
      start=min_date,#dt(2024,1,1,0,0,0),
      end=max_date#dt(2024,11,1,0,0,0)
    )
    btc_bars = client.get_stock_bars(request_params)
    #print('done with call')
    # Convert to dataframe
    bars_df=btc_bars.df
    #print(bars_df)
    bars_df=bars_df.reset_index()
    bars_df['date']=[str(stamp)[:10] for stamp in bars_df.timestamp]
    bars_df['hour']=[int(str(stamp)[11:13]) for stamp in bars_df.timestamp]
    bars_df['minute']=[int(str(stamp)[14:16]) for stamp in bars_df.timestamp]
    bars_df['hour_mins']=[60*hr for hr in bars_df.hour]
    
    bars_df['day_min']=[hr_mins+m for hr_mins,m in zip(list(bars_df.hour_mins),list(bars_df.minute))]
    #bars_df['sum_of_price']=[vol*vwap for vol,vwap in zip(list(bars_df.volume),list(bars_df.vwap))]
    #bars_df['price_set']=[[vwap]*int(vol) for vol,vwap in zip(list(bars_df.volume),list(bars_df.vwap))]
    bars_df=bars_df.drop(columns=['hour','minute','hour_mins'])
    #bars_df['timestamp']=pd.to_datetime(bars_df['timestamp'], errors='coerce')
    return bars_df

getMinuteLevel('BHST')

,symbol,timestamp,open,high,low,close,volume,trade_count,vwap,date,day_min
0,BHST,2024-11-12 14:35:00+00:00,6.00,6.00,6.00,6.00,487.0,2.0,6.000000,2024-11-12,875
1,BHST,2024-11-12 15:13:00+00:00,5.80,5.80,5.80,5.80,100.0,1.0,5.800000,2024-11-12,913
2,BHST,2024-11-12 15:23:00+00:00,5.80,5.80,5.80,5.80,375.0,1.0,5.800000,2024-11-12,923
3,BHST,2024-11-12 15:24:00+00:00,5.61,5.61,5.60,5.60,1392.0,6.0,5.604695,2024-11-12,924
4,BHST,2024-11-12 15:45:00+00:00,5.49,5.49,5.49,5.49,1087.0,5.0,5.490000,2024-11-12,945
...,...,...,...,...,...,...,...,...,...,...,...
10521,BHST,2026-03-13 19:56:00+00:00,4.18,4.18,4.18,4.18,134.0,2.0,4.180000,2026-03-13,1196
10522,BHST,2026-03-13 19:57:00+00:00,4.15,4.18,4.15,4.18,254.0,3.0,4.165437,2026-03-13,1197
10523,BHST,2026-03-13 19:58:00+00:00,4.16,4.16,4.15,4.15,453.0,7.0,4.153817,2026-03-13,1198
10524,BHST,2026-03-13 19:59:00+00:00,4.19,4.20,4.15,4.15,1908.0,25.0,4.183957,2026-03-13,1199
10525,BHST,2026-03-13 20:00:00+00:00,4.15,4.15,4.15,4.15,551.0,2.0,4.150000,2026-03-13,1200

In [2]:
#PREPROCESS 2: 
from holidays import US
import pandas as pd
import numpy as np
import yfinance as yf # Uncommented this so the code runs
from itertools import combinations

global verbose
verbose = False

# --- RSI FUNCTION DEFINITION ---
def calculate_rsi(series, window, min_lag):
    """Calculates the Relative Strength Index (RSI)."""
    delta = series.diff()
    gain = delta.where(delta > 0, 0)
    loss = -delta.where(delta < 0, 0)
    
    # Use min_periods=1 to maximize data availability, span=window for smoothing
    avg_gain = gain.ewm(span=window, min_periods=min_lag).mean()
    avg_loss = loss.ewm(span=window, min_periods=min_lag).mean()
    
    # Handle division by zero
    rs = np.divide(avg_gain, avg_loss, out=np.zeros_like(avg_gain), where=avg_loss!=0)
    rsi = 100 - (100 / (1 + rs))
    return rsi

# --- AGGREGATION FUNCTION ---
def getAggPizza(s, level):
    pza = getMinuteLevel(s)
    print('got minute-level')
   
    pza['current_vwap'] = pza['vwap'].ffill()
    pza['vwap_volume'] = pza['current_vwap'] * pza['volume']
   
    # Filter Holidays and Market Hours
    us_holidays = US(years=range(2023, 2026))
    pza['date'] = pza['timestamp'].dt.date
    pza['is_weekday'] = pza['timestamp'].dt.weekday < 5
    pza['is_not_holiday'] = ~pza['date'].isin([d for d in us_holidays])
   
    # Convert to ET for accurate local market hours (handles DST automatically)
    pza['timestamp_et'] = pza['timestamp'].dt.tz_convert('America/New_York')
    pza['time_et'] = pza['timestamp_et'].dt.time  # Separate column for time comparison
   
    market_hours = (pza['time_et'] >= pd.to_datetime('09:30').time()) & \
                   (pza['time_et'] < pd.to_datetime('16:00').time())
   
    pza = pza[pza['is_weekday'] & pza['is_not_holiday'] & market_hours].drop(
        columns=['date', 'is_weekday', 'is_not_holiday', 'time_et']
    ).reset_index(drop=True)  # Keep timestamp_et for flooring
   
    print('after weekends')
   
    # Floor the full datetime (in ET) to create the aggregation level
    pza['timestamp_level'] = pza['timestamp_et'].dt.floor(f'{level}min')
   
    pza_agg = pza.groupby('timestamp_level').agg({
        'vwap_volume': 'sum',
        'volume': 'sum'
    }).reset_index()
   
    pza_agg['mean_vwap'] = pza_agg['vwap_volume'] / pza_agg['volume']
    pza_agg['mean_vwap'] = pza_agg['mean_vwap'].ffill()
    pza_agg = pza_agg.rename(columns={'mean_vwap': f'mean_vwap_{level}'}).drop(columns=['vwap_volume'])
   
    # Extract hour/minute/day_of_week from the floored ET timestamp
    pza_agg['hour'] = pza_agg['timestamp_level'].dt.hour
    pza_agg['minute'] = pza_agg['timestamp_level'].dt.minute
    pza_agg['day_of_week'] = pza_agg['timestamp_level'].dt.dayofweek
   
    # minutes_since_open: 9:30 ET = 0
    pza_agg['minutes_since_open'] = (pza_agg['hour'] - 9) * 60 + (pza_agg['minute'] - 30)
    pza_agg['session_progress'] = pza_agg['minutes_since_open'] / 390.0
   
    # Optional: drop the helper if not needed downstream
    # pza_agg = pza_agg.drop(columns=['timestamp_et'])  # if you don't need it later
   
    print(level)
    return pza_agg

# --- MAIN FEATURE FUNCTION ---
def getGalledPrices(s, level, leads, lags):
    pza_agg = getAggPizza(s, level)
    
    # Merge with SPY
    spy_agg = getAggPizza('SPY', level)[['timestamp_level', 'mean_vwap_'+str(level)]].rename(
        columns={'timestamp_level': 'timestamp_level_SPY', 'mean_vwap_'+str(level): 'mean_vwap_'+str(level)+'_SPY'}
    )
    
    pza_agg = pd.merge(pza_agg, spy_agg, left_on='timestamp_level', right_on='timestamp_level_SPY', how='right')
    pza_agg['timestamp_level'] = pza_agg['timestamp_level_SPY']
    
    # Calculate Relative Price (Stock / SPY)
    pza_agg['mean_vwap_'+str(level)] = pza_agg['mean_vwap_'+str(level)] / pza_agg['mean_vwap_'+str(level)+'_SPY']
    pza_agg['mean_vwap_'+str(level)] = pza_agg['mean_vwap_'+str(level)].ffill()
    pza_agg['volume'] = pza_agg['volume'].fillna(0)
    pza_agg['pct_change'] = pza_agg['mean_vwap_'+str(level)].pct_change()
    
    lag_ptiles = range(10, 100, 20)
    lead_ptiles = [15, 85]
    
    print(len(pza_agg))
    print('before loop')
    max_lag=max(lags)
    max_lag_rows = max_lag* (6.5 * 60) / level
    if max_lag_rows > len(pza_agg):
        print('not enough past prices')
        return None
        
    min_lag = min(lags)
    
    # --- MAIN LAG LOOP ---
    for lag in lags:
        lag_rows = int(lag * (6.5 * 60 / level))
        
        # Percentiles
        for p in lag_ptiles:
            pza_agg[f'{p}th_ptile_lag_{lag}days'] = (
                pza_agg['mean_vwap_15'].shift(1)
                .rolling(window=lag_rows, min_periods=min_lag)
                .quantile(p/100)
            )
            pza_agg['change_lag_'+str(lag)+str(p)+'th_ptile'] = (
                pza_agg['mean_vwap_'+str(level)] - pza_agg[f'{p}th_ptile_lag_{lag}days']
            ) / pza_agg[f'{p}th_ptile_lag_{lag}days']
            
        # Volatility & Momentum
        pza_agg['rolling_avg_vol_'+str(lag)] = pza_agg['volume'].shift(1).rolling(window=lag_rows, min_periods=min_lag).mean()
        pza_agg['relative_volume_'+str(lag)] = pza_agg['volume'] / pza_agg['rolling_avg_vol_'+str(lag)]
        
        pza_agg['volatility_'+str(lag)] = pza_agg['pct_change'].shift(1).rolling(window=lag_rows, min_periods=min_lag).std()
        
        rolling_mean = pza_agg['mean_vwap_'+str(level)].shift(1).rolling(window=lag_rows, min_periods=min_lag).mean()
        rolling_std = pza_agg['mean_vwap_'+str(level)].shift(1).rolling(window=lag_rows, min_periods=min_lag).std()
        pza_agg[f'rolling_mean_{lag}'] = rolling_mean
        pza_agg[f'rolling_std_{lag}'] = rolling_std
        
        pza_agg[f'z_score_{lag}'] = (pza_agg['mean_vwap_'+str(level)] - rolling_mean) / rolling_std.replace(0, np.nan)
        pza_agg['bb_width_'+str(lag)] = (rolling_std * 2) / rolling_mean
        
        # Efficiency Ratio
        net_change = pza_agg['mean_vwap_15'].shift(1).rolling(lag_rows, min_periods=min_lag).apply(lambda x: abs(x.iloc[-1] - x.iloc[0]) if len(x) > 1 else np.nan)
        sum_of_changes = pza_agg['mean_vwap_' + str(level)].diff().abs().shift(1).rolling(window=lag_rows, min_periods=min_lag).sum()
        pza_agg[f'efficiency_ratio_{lag}'] = net_change / sum_of_changes.replace(0, np.nan)
        
        # Skewness
        pza_agg[f'skew_{lag}'] = pza_agg['pct_change'].shift(1).rolling(window=lag_rows, min_periods=min_lag).skew()
        
        # Volume Force
        pza_agg[f'volume_force_{lag}'] = pza_agg['pct_change'] * pza_agg[f'relative_volume_{lag}']
        
        # RSI
        pza_agg['rsi_'+str(lag)] = calculate_rsi(pza_agg['mean_vwap_'+str(level)], window=lag_rows, min_lag=min_lag)
        pza_agg[f'rsi_divergence_{lag}'] = np.sign(pza_agg[f'rsi_{lag}'].pct_change()) * np.sign(pza_agg['pct_change'])
        
        # Adjustments
        session_adjust = 1 - np.abs(2 * pza_agg['session_progress'] - 1) + 0.5
        pza_agg[f'session_adj_rel_volume_{lag}'] = pza_agg[f'relative_volume_{lag}'] * session_adjust
        
        weekday_avg_vol = pza_agg.groupby('day_of_week')[f'volatility_{lag}'].transform('mean')
        pza_agg[f'weekday_adj_vol_{lag}'] = pza_agg[f'volatility_{lag}'] / weekday_avg_vol.replace(0, np.nan)
        pza_agg[f'weekday_adj_vol_{lag}'] = pza_agg[f'weekday_adj_vol_{lag}'].fillna(1)

    # Momentum Diff (MM Diff)
    for lag1, lag2 in combinations(lags, 2):
        s_lag, l_lag = sorted((lag1, lag2))
        col_short = f'50th_ptile_lag_{s_lag}days'
        col_long = f'50th_ptile_lag_{l_lag}days'
        
        pza_agg[f'mm_diff_{s_lag}_{l_lag}'] = (pza_agg[col_short] - pza_agg[col_long]) / pza_agg[col_long]
        
        mom_col = f'mm_diff_{s_lag}_{l_lag}'
        vol_col = f'volatility_{l_lag}'
        pza_agg[f'risk_adj_{mom_col}'] = pza_agg[mom_col] / pza_agg[vol_col].replace(0, np.nan)
        pza_agg[f'risk_adj_{mom_col}'] = pza_agg[f'risk_adj_{mom_col}'].fillna(0)


    # Lead (Target) Calculation
    min_lead = min(leads)
    for lead in leads:
        lead_rows = int(lead * (6.5 * 60 / level))
        for p in lead_ptiles:
            pza_agg[f'{p}th_ptile_lead_{lead}days'] = (
                pza_agg['mean_vwap_15']
                .iloc[::-1].shift(1)
                .rolling(window=lead_rows, min_periods=min_lead)
                .quantile(p/100)
                .iloc[::-1]
                .values
            )
            pza_agg['change_lead_'+str(lead)+'_'+str(p)+'th_ptile'] = (
                pza_agg[f'{p}th_ptile_lead_{lead}days'] - pza_agg['mean_vwap_'+str(level)]
            ) / pza_agg['mean_vwap_'+str(level)]

    # --- EARNINGS DATE CALCULATION (OPTIMIZED) ---
    t = yf.Ticker(s)
    earnings_df = pd.DataFrame(t.earnings_dates).reset_index()
    
    # Check if we have data
    if 'Earnings Date' in earnings_df.columns:
        earnings_df = earnings_df.rename(columns={'Earnings Date': 'earning_date'})
    
    # Ensure Timestamp compatibility
   # pza_agg['timestamp_level'] = pd.to_datetime(pza_agg['timestamp_level'], utc=True)
    
    has_earnings = False
    if not earnings_df.empty and 'earning_date' in earnings_df.columns:
        try:
            # Convert earnings dates to Eastern Time to match timestamp_level
            earnings_df['earning_date'] = pd.to_datetime(earnings_df['earning_date']).dt.tz_convert('America/New_York')
            earnings_df = earnings_df.sort_values('earning_date').dropna(subset=['earning_date'])
            pza_agg = pza_agg.sort_values('timestamp_level')
            has_earnings = True
        except Exception as e:
            print(f"Earnings date conversion failed: {e}")
    if has_earnings:
        # Backward Search (Days Since)
        pza_agg = pd.merge_asof(
            pza_agg,
            earnings_df[['earning_date']],
            left_on='timestamp_level',
            right_on='earning_date',
            direction='backward'
        ).rename(columns={'earning_date': 'last_earnings_date'})

        # Forward Search (Days Before)
        pza_agg = pd.merge_asof(
            pza_agg,
            earnings_df[['earning_date']],
            left_on='timestamp_level',
            right_on='earning_date',
            direction='forward'
        ).rename(columns={'earning_date': 'next_earnings_date'})

        pza_agg['days_since_earnings'] = ((pza_agg['timestamp_level'] - pza_agg['last_earnings_date']).dt.total_seconds() / 86400).fillna(90.0)
        pza_agg['days_before_earnings'] = ((pza_agg['next_earnings_date'] - pza_agg['timestamp_level']).dt.total_seconds() / 86400).fillna(90.0)
        
        pza_agg = pza_agg.drop(columns=['last_earnings_date', 'next_earnings_date'])
    else:
        print('No earnings data found or processing failed.')
        pza_agg['days_since_earnings'] = 90.0
        pza_agg['days_before_earnings'] = 90.0


    # --- INTERACTIVE FEATURES SECTION ---
    
    # 1. Earnings Interaction
    target_lag = lags[0]
    
    if 'days_before_earnings' in pza_agg.columns:
        days_to_earn = pza_agg['days_before_earnings'].clip(lower=0)
        earnings_proximity = 1 / (days_to_earn + 1)
        
        base_metrics = ['volatility', 'relative_volume', 'z_score', 'bb_width', 'efficiency_ratio', 'rsi']
        
        for metric in base_metrics:
            col_name = f'{metric}_{target_lag}'
            if col_name in pza_agg.columns:
                pza_agg[f'{metric}_{target_lag}_x_earn_prox'] = (
                    pza_agg[col_name] * earnings_proximity
                )

        pct_col_name = f'change_lag_{target_lag}50th_ptile' 
        if pct_col_name in pza_agg.columns:
            pza_agg[f'change_lag_{target_lag}_50th_ptile_x_earn_prox'] = (
                pza_agg[pct_col_name] * earnings_proximity
            )

        # 2. Day of Week Interactions
        # Add the pct change column to the list for this loop
        loop_metrics = base_metrics + [pct_col_name] if pct_col_name in pza_agg.columns else base_metrics

        for metric in loop_metrics:
            if metric == pct_col_name:
                col_name = metric
                short_name = 'pct_chg_50th'
            else:
                col_name = f'{metric}_{target_lag}'
                short_name = metric

            if col_name in pza_agg.columns:
                # Mon = 0, Fri = 4
                pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
                pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)

        # 3. Time of Day Interactions
        pza_agg['is_open_30m'] = (pza_agg['minutes_since_open'] <= 30).astype(int)
        pza_agg['is_close_30m'] = (pza_agg['minutes_since_open'] >= 360).astype(int)
        pza_agg['is_mid_day'] = ((pza_agg['minutes_since_open'] > 30) & (pza_agg['minutes_since_open'] < 360)).astype(int)

        for metric in loop_metrics:
            if metric == pct_col_name:
                col_name = metric
                short_name = 'pct_chg_50th'
            else:
                col_name = f'{metric}_{target_lag}'
                short_name = metric

            if col_name in pza_agg.columns:
                pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
                pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
                pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']

    # At the end of getGalledPrices, just before return pza_agg
    pza_agg['timestamp_level'] = pza_agg['timestamp_level'].dt.tz_localize(None)  # or .dt.tz_convert(None)
    return pza_agg


s='TSM'
# Assuming yf is available, we run the function to test

#ggp=getGalledPrices(s,15,[15],[10,25,50,75]) 
#ggp.columns = [col + '_' + str(s) for col in ggp.columns]
#ggp

In [3]:
all=pd.read_excel('all_stocks_class.xlsx')
swa_stocks=all[all['inds']=='Semiconductors']

In [8]:
#PREPROCESS 3: get ggp table for each stock
import time
start_time = time.time()
global level
industry = 'semiconductors'
level=15
#industry='restaurants'
for s in swa_stocks.stocks:
    #print(s)
    #print(type(s))
    print(s=='nan')
    start_time_loop = time.time()
    try:
        s=s.replace('-', '.')
    except:
        continue
    if isinstance(s, float):
        continue
    try:
        #pd.read_csv('ggp_rel_tables/'+industry+'/ggp_'+s+'.csv')
        buudfoon
        continue
    except:
        print(s)
        ggp=getGalledPrices(s,15,[15],[10,25,50])
        try:
            ggp.columns = [col + '_' + str(s) for col in ggp.columns]
            ggp.to_csv('ggp_rel_tables/'+industry+'/ggp_'+s+'.csv')
        except:
            continue
    end_time_loop = time.time()
    elapsed_time = end_time_loop - start_time_loop
    print(f"Elapsed time: {elapsed_time:.2f} seconds")
end_time = time.time()
elapsed_time = end_time - start_time
print(f"Elapsed time: {elapsed_time:.2f} seconds")

False
WKEY
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 133.09 seconds
False
IMOS
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 140.70 seconds
False
ICG
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 142.15 seconds
False
UMC
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 207.52 seconds
False
MX
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 162.93 seconds
False
NVEC
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 140.27 seconds
False
POWI
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 177.25 seconds
False
SLAB
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 162.24 seconds
False
GCTS
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 159.94 seconds
False
ASX
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 195.12 seconds
False
ADI
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 196.85 seconds
False
AIP
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 168.36 seconds
False
ALAB
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 213.78 seconds
False
ALGM
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 188.51 seconds
False
AMD
got minute-level
after weekends
15
12792
before loop
Elapsed time: 1348.73 seconds
False
AOSL
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 163.52 seconds
False
ARM
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 235.66 seconds
False
AVGO
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 216.56 seconds
False
CEVA
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 144.29 seconds
False
CRDO
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 174.29 seconds
False
CRUS
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 148.26 seconds
False
DIOD
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 144.21 seconds
False
PXLW
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 132.77 seconds
False
GFS
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 163.87 seconds
False
PRSO
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 131.85 seconds
False
GSIT
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 141.82 seconds
False
POET
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 164.46 seconds
False
HIMX
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 170.54 seconds
False
INTC
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 232.97 seconds
False
LASR
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 153.15 seconds
False
LSCC
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 169.38 seconds
False
MCHP
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 167.43 seconds
False
MPWR
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 149.28 seconds
False
MRAM
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 127.93 seconds
False
MRVL
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 189.43 seconds
False
MTSI
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 157.40 seconds
False
MU
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 212.96 seconds
False
MXL
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 157.05 seconds
False
NVDA
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 246.13 seconds
False
NVTS
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 193.47 seconds
False
NXPI
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 177.31 seconds
False
ON
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 171.72 seconds
False
PI
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 141.24 seconds
False
False
QCOM
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 188.01 seconds
False
QRVO
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 166.88 seconds
False
QUIK
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 137.97 seconds
False
RMBS
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 167.31 seconds
False
MOBXW
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop

MOBXW: $MOBXW: possibly delisted; no earnings dates found
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:287: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_open_30m'] = (pza_agg['minutes_since_open'] <= 30).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:288: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_close_30m'] = (pza_agg['minutes_since_open'] >= 360).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:289: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_mid_day'] = ((pza_agg['minutes_since_open'] > 30) & (pza_agg['minutes_since_open'] < 360)).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']

No earnings data found or processing failed.
Elapsed time: 114.74 seconds
False
MOBX
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop

MOBX: $MOBX: possibly delisted; no earnings dates found
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:287: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_open_30m'] = (pza_agg['minutes_since_open'] <= 30).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:288: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_close_30m'] = (pza_agg['minutes_since_open'] >= 360).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:289: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_mid_day'] = ((pza_agg['minutes_since_open'] > 30) & (pza_agg['minutes_since_open'] < 360)).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']

No earnings data found or processing failed.
Elapsed time: 142.42 seconds
False
SIMO
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 148.34 seconds
False
SITM
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 338.46 seconds
False
SKYT
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 198.73 seconds
False
SMTC
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 204.04 seconds
False
STM
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 215.26 seconds
False
SWKS
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 205.43 seconds
False
SYNA
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 183.51 seconds
False
TSEM
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 186.34 seconds
False
TSM
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 260.52 seconds
False
TXN
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 200.87 seconds
False
VLN
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 168.57 seconds
False
LEDS
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 136.32 seconds
False
VSH
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 187.78 seconds
False
LAES
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop

LAES: $LAES: possibly delisted; no earnings dates found
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:287: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_open_30m'] = (pza_agg['minutes_since_open'] <= 30).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:288: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_close_30m'] = (pza_agg['minutes_since_open'] >= 360).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:289: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_mid_day'] = ((pza_agg['minutes_since_open'] > 30) & (pza_agg['minutes_since_open'] < 360)).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_55436\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']

No earnings data found or processing failed.
Elapsed time: 218.57 seconds
False
WOLF
got minute-level
after weekends
15
got minute-level
after weekends
15
12792
before loop
Elapsed time: 236.23 seconds
Elapsed time: 12522.68 seconds

In [7]:
#PREPROCESS 4: get join_df based on ggp tables

import glob
import pandas as pd
import os
industry = 'semiconductors'
# PREPROCESS 4: get join_df based on ggp tables

import glob
import pandas as pd
import os

industry = 'semiconductors'

def getFeaturePres(industry, folder_path, daily_folder=None):
    # Get all CSV files in the folder
    csv_files = glob.glob(os.path.join(folder_path, "*.csv"))
    
    if not csv_files:
        raise FileNotFoundError(f"No CSV files found in {folder_path}")
    
    print(f"Found {len(csv_files)} files: {[os.path.basename(f) for f in csv_files]}")
    
    # Load the first file as the base
    base_file = csv_files[0]
    base_stock = os.path.basename(base_file).replace('ggp_', '').replace('.csv', '')
    base_df = pd.read_csv(base_file).drop(columns=['Unnamed: 0'], errors='ignore')
    print(f"Base stock: {base_stock}")
    
    # Identify and convert timestamp column
    timestamp_col_base = f'timestamp_level_{base_stock}'
    if timestamp_col_base not in base_df.columns:
        raise KeyError(f"Timestamp column {timestamp_col_base} not found in {base_file}")
    
    # --- ADDED: Convert to consistent datetime format ---
    base_df[timestamp_col_base] = pd.to_datetime(base_df[timestamp_col_base])
    
    # Set index (drop=False keeps the column available for your coalesce logic later)
    join_df = base_df.set_index(timestamp_col_base, drop=False)
    
    timestamp_cols = [timestamp_col_base]
    
    # Loop over the remaining files and outer-join them
    for file_path in csv_files[1:]:
        stock = os.path.basename(file_path).replace('ggp_', '').replace('.csv', '')
        print(f"Joining {stock}...")
    
        df = pd.read_csv(file_path).drop(columns=['Unnamed: 0'], errors='ignore')
    
        timestamp_col = f'timestamp_level_{stock}'
        if timestamp_col not in df.columns:
            print(f"Warning: Timestamp column {timestamp_col} missing in {file_path}, skipping")
            continue
        
        # --- ADDED: Convert to consistent datetime format ---
        df[timestamp_col] = pd.to_datetime(df[timestamp_col])
    
        # Set index and align name
        df = df.set_index(timestamp_col, drop=False)
        df.index.name = join_df.index.name 
    
        # Outer join on the datetime index
        join_df = join_df.join(df.drop(columns=[timestamp_col]), how='outer')
    
        timestamp_cols.append(timestamp_col)
    
    # Sort chronologically
    join_df = join_df.sort_index()
    
    # Re-add the individual timestamp columns if they were dropped during join 
    # (Note: Since we joined on index, we use the index to fill the final timestamp)
    join_df['timestamp'] = join_df.index
    
    # Clean up: If you want to drop the specific 'timestamp_level_XXX' columns now:
    cols_to_drop = [c for c in join_df.columns if 'timestamp_level_' in c]
    join_df = join_df.drop(columns=cols_to_drop)
    
    print(f"\nFinal joined DataFrame shape: {join_df.shape}")
    
    save_path = 'feature_presentation_' + industry + '.csv'
    if daily_folder:
        save_path = os.path.join(daily_folder, save_path)
        
    join_df.to_csv(save_path)
    #return join_df

# Run the function
# getFeaturePres(industry, 'ggp_rel_tables/semiconductors')

#getFeaturePres(industry,'ggp_rel_tables/semiconductors')

In [35]:
df2=pd.read_csv('ggp_rel_tables/semiconductors/ggp_TSM.csv')
[c for c in df2.columns if 'rolling_mean_' in c]

['rolling_mean_10_TSM', 'rolling_mean_25_TSM', 'rolling_mean_50_TSM']

In [9]:
jino = pd.read_csv('feature_presentation_' + industry + '.csv')
jino

,timestamp_level_ADI,volume_ADI,mean_vwap_15_ADI,hour_ADI,minute_ADI,day_of_week_ADI,minutes_since_open_ADI,session_progress_ADI,mean_vwap_15_SPY_ADI,pct_change_ADI,...,efficiency_ratio_Open30m_WOLF,efficiency_ratio_Close30m_WOLF,efficiency_ratio_MidDay_WOLF,rsi_Open30m_WOLF,rsi_Close30m_WOLF,rsi_MidDay_WOLF,pct_chg_50th_Open30m_WOLF,pct_chg_50th_Close30m_WOLF,pct_chg_50th_MidDay_WOLF,timestamp
0,2024-02-20 09:30:00,208149.0,0.376170,9.0,30.0,1.0,0.0,0.000000,497.488329,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-02-20 09:30:00
1,2024-02-20 09:45:00,86511.0,0.376508,9.0,45.0,1.0,15.0,0.038462,496.627943,0.000900,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-02-20 09:45:00
2,2024-02-20 10:00:00,112943.0,0.376056,10.0,0.0,1.0,30.0,0.076923,496.343405,-0.001201,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-02-20 10:00:00
3,2024-02-20 10:15:00,101436.0,0.375738,10.0,15.0,1.0,45.0,0.115385,496.244081,-0.000846,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-02-20 10:15:00
4,2024-02-20 10:30:00,126306.0,0.376506,10.0,30.0,1.0,60.0,0.153846,496.018188,0.002044,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-02-20 10:30:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12787,2026-02-06 14:45:00,154549.0,0.466360,14.0,45.0,4.0,315.0,0.807692,689.492519,-0.000693,...,0.0,0.000000,0.057740,0.0,0.000000,47.538668,-0.0,-0.000000,-0.071242,2026-02-06 14:45:00
12788,2026-02-06 15:00:00,183290.0,0.466019,15.0,0.0,4.0,330.0,0.846154,689.542399,-0.000732,...,0.0,0.000000,0.057487,0.0,0.000000,47.350151,-0.0,-0.000000,-0.075635,2026-02-06 15:00:00
12789,2026-02-06 15:15:00,347638.0,0.465622,15.0,15.0,4.0,345.0,0.884615,689.856360,-0.000851,...,0.0,0.000000,0.060906,0.0,0.000000,47.205149,-0.0,-0.000000,-0.078706,2026-02-06 15:15:00
12790,2026-02-06 15:30:00,219289.0,0.464577,15.0,30.0,4.0,360.0,0.923077,690.171379,-0.002245,...,0.0,0.059212,0.000000,0.0,47.407233,0.000000,-0.0,-0.072279,-0.000000,2026-02-06 15:30:00
12791,2026-02-06 15:45:00,1078858.0,0.463142,15.0,45.0,4.0,375.0,0.961538,691.514783,-0.003088,...,0.0,0.060245,0.000000,0.0,47.402017,0.000000,-0.0,-0.069735,-0.000000,2026-02-06 15:45:00

In [37]:
#PREPROCESS 5: get jino and identify featrues/targets
import pandas as pd
import joblib
industry = 'semiconductors'
def get_features(s):
    lags = [10, 25, 50]  # lag days
    ptiles = [10, 30, 50, 70, 90]  # percentiles
    other_lag_metrics = [
        'rolling_avg_vol', 'relative_volume', 'volatility', 'z_score',
        'bb_width', 'efficiency_ratio', 'skew', 'volume_force',
        'rsi', 'rsi_divergence', 'session_adj_rel_volume', 'weekday_adj_vol'
    ]

    lag_features = []

    # 1. Change-from-percentile features: 5 per lag × 4 lags = 20
    for lag in lags:
        for p in ptiles:
            lag_features.append(f'change_lag_{lag}{p}th_ptile_{s}')

    # 2. Other lag metrics: 12 per lag × 4 lags = 48
    for lag in lags:
        for metric in other_lag_metrics:
            lag_features.append(f'{metric}_{lag}_{s}')

    # Total lag features: 20 + 48 = 68
    # (We removed the 20 raw ptile_lag columns as they are time-correlated)

    # Add timestamp column
    #lag_features.append(f'timestamp_level_{s}')

    print(f"Total features generated: {len(lag_features)}")  # Should be 69

    return lag_features

def get_non_feature_vars(s):
    lags = [10, 25, 50]  # lag days
    ptiles = [10, 30, 50, 70, 90]  # percentiles
    lag_ptile_vars=[]
    lag_vars=[]
    for lag in lags:
        for p in ptiles:
            lag_ptile_vars.append(f'lag_{lag}{p}th_ptile_{s}')
    
        lag_vars.append(f'rolling_mean_{lag}_{s}')
        lag_vars.append(f'rolling_std_{lag}_{s}')
    non_feature_vars=lag_ptile_vars+lag_vars
    return non_feature_vars
# Example usage
features = get_features('NVDA')
#non_features=get_non_feature_vars('NVDA')
#LOAD JINO AND ISOLATE TRAINING TIMES
# 1. Load the full wide table
jino = pd.read_csv('feature_presentation_' + industry + '.csv')
ts_cols=[c for c in jino.columns if 'timestamp' in c]
timestamp_col=ts_cols[-1]
jino = jino.sort_values(timestamp_col).reset_index(drop=True)
# 2. Replicate your splitting logic exactly
rows_per_day = 26  
max_lead_days = 15  
buffer_rows = max_lead_days * rows_per_day

total_rows = len(jino)
test_size = int(total_rows * 0.2)
val_size = int(total_rows * 0.2)

# Calculate the end of the training section
idx_test_start = total_rows - test_size - buffer_rows
idx_val_end = idx_test_start - buffer_rows
idx_val_start = idx_val_end - val_size
idx_train_end = idx_val_start - buffer_rows

# 3. Filter jino to only include the Training Range
# This ensures feature selection (correlations) has zero look-ahead bias
jino_train = jino.iloc[:idx_train_end].copy()

print(f"Original rows: {total_rows}")
print(f"Training rows for feature selection: {len(jino_train)}")

#GET FEATURES AND TARGETS
import pandas as pd
jino_cols=jino.columns

stocks=pd.read_excel('all_stocks_class.xlsx')
ind_stocks=stocks[stocks['inds'].str.lower()==industry].stocks
get_rats=jino[[c for c in jino.columns if 'change_lead' in c]].columns
#get_rats
features_giant=[]
for s in ind_stocks:
    print(s)
    features_giant+=get_features(s)

features_giant = [col for col in features_giant if 'nan' not in col]
joblib.dump(features_giant, 'features_giant_list.pkl')

Total features generated: 51
Original rows: 12792
Training rows for feature selection: 6506
WKEY
Total features generated: 51
IMOS
Total features generated: 51
ICG
Total features generated: 51
UMC
Total features generated: 51
MX
Total features generated: 51
NVEC
Total features generated: 51
POWI
Total features generated: 51
SLAB
Total features generated: 51
GCTS
Total features generated: 51
ASX
Total features generated: 51
ADI
Total features generated: 51
AIP
Total features generated: 51
ALAB
Total features generated: 51
ALGM
Total features generated: 51
AMD
Total features generated: 51
AOSL
Total features generated: 51
ARM
Total features generated: 51
AVGO
Total features generated: 51
CEVA
Total features generated: 51
CRDO
Total features generated: 51
CRUS
Total features generated: 51
DIOD
Total features generated: 51
PXLW
Total features generated: 51
GFS
Total features generated: 51
PRSO
Total features generated: 51
GSIT
Total features generated: 51
POET
Total features generated: 51
HIMX
Total features generated: 51
INTC
Total features generated: 51
LASR
Total features generated: 51
LSCC
Total features generated: 51
MCHP
Total features generated: 51
MPWR
Total features generated: 51
MRAM
Total features generated: 51
MRVL
Total features generated: 51
MTSI
Total features generated: 51
MU
Total features generated: 51
MXL
Total features generated: 51
NVDA
Total features generated: 51
NVTS
Total features generated: 51
NXPI
Total features generated: 51
ON
Total features generated: 51
PI
Total features generated: 51
nan
Total features generated: 51
QCOM
Total features generated: 51
QRVO
Total features generated: 51
QUIK
Total features generated: 51
RMBS
Total features generated: 51
MOBXW
Total features generated: 51
MOBX
Total features generated: 51
SIMO
Total features generated: 51
SITM
Total features generated: 51
SKYT
Total features generated: 51
SMTC
Total features generated: 51
STM
Total features generated: 51
SWKS
Total features generated: 51
SYNA
Total features generated: 51
TSEM
Total features generated: 51
TSM
Total features generated: 51
TXN
Total features generated: 51
VLN
Total features generated: 51
LEDS
Total features generated: 51
VSH
Total features generated: 51
LAES
Total features generated: 51
WOLF
Total features generated: 51

['features_giant_list.pkl']

In [39]:
features_giant = joblib.load('features_giant_list.pkl')
len(features_giant)

3264

In [41]:
'''
#FEATURE SELECTION 1: GET SPEARMAN CORRS
import pandas as pd
from scipy.stats import spearmanr
import time

start_time = time.time()
# 1. Initialize empty list to store results (much faster than appending to a DF)
results_list = []
iter=0
for t in get_rats:
    #if 'ADI' in t or 'AIP' in t or 'ALAB' in t or 'ALGM' in t or 'AMD' in t:
        #continue
    if iter>=30:
        break
    start_time_loop=time.time()
    #if iter==0:
    print(t)
    for v in features_giant:
        #if iter==0:
            #print(v)
        # 2. Get spearman corr
        # Assumes 'stocks' is your main DataFrame
        # .dropna() is important as spearmanr can return NaN if data is missing
        if v in jino_cols:
            corr, p_value = spearmanr(jino[t], jino[v], nan_policy='omit')
            results_list.append({'target': t, 'potential_var': v, 'corr': corr})
        # 3. Add [t, v, corr] to the list
        
    end_time_loop = time.time()
    elapsed_time = end_time_loop - start_time_loop
    print(f"Elapsed time: {elapsed_time:.2f} seconds")
    iter+=1
    

# 4. Create the DF from the list
spearman_or_fruit = pd.DataFrame(results_list)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"Elapsed time: {elapsed_time:.2f} seconds")
# 5. Filter for correlations greater than .05 (absolute value is usually better)
# Using .abs() ensures you don't accidentally throw away strong negative correlations
filtered_results = spearman_or_fruit[spearman_or_fruit['corr'].abs() > 0.05]
filtered_results

spearman_or_fruit.to_excel('spearman_or_fruit_'+industry+'.xlsx')
'''

'\n#FEATURE SELECTION 1: GET SPEARMAN CORRS\nimport pandas as pd\nfrom scipy.stats import spearmanr\nimport time\n\nstart_time = time.time()\n# 1. Initialize empty list to store results (much faster than appending to a DF)\nresults_list = []\niter=0\nfor t in get_rats:\n    #if \'ADI\' in t or \'AIP\' in t or \'ALAB\' in t or \'ALGM\' in t or \'AMD\' in t:\n        #continue\n    if iter>=30:\n        break\n    start_time_loop=time.time()\n    #if iter==0:\n    print(t)\n    for v in features_giant:\n        #if iter==0:\n            #print(v)\n        # 2. Get spearman corr\n        # Assumes \'stocks\' is your main DataFrame\n        # .dropna() is important as spearmanr can return NaN if data is missing\n        if v in jino_cols:\n            corr, p_value = spearmanr(jino[t], jino[v], nan_policy=\'omit\')\n            results_list.append({\'target\': t, \'potential_var\': v, \'corr\': corr})\n        # 3. Add [t, v, corr] to the list\n        \n    end_time_loop = time.time()\n    elapsed_time = end_time_loop - start_time_loop\n    print(f"Elapsed time: {elapsed_time:.2f} seconds")\n    iter+=1\n    \n\n# 4. Create the DF from the list\nspearman_or_fruit = pd.DataFrame(results_list)\nend_time = time.time()\nelapsed_time = end_time - start_time\nprint(f"Elapsed time: {elapsed_time:.2f} seconds")\n# 5. Filter for correlations greater than .05 (absolute value is usually better)\n# Using .abs() ensures you don\'t accidentally throw away strong negative correlations\nfiltered_results = spearman_or_fruit[spearman_or_fruit[\'corr\'].abs() > 0.05]\nfiltered_results\n\nspearman_or_fruit.to_excel(\'spearman_or_fruit_\'+industry+\'.xlsx\')\n'

In [45]:
jino[features_giant]

,change_lag_1010th_ptile_WKEY,change_lag_1030th_ptile_WKEY,change_lag_1050th_ptile_WKEY,change_lag_1070th_ptile_WKEY,change_lag_1090th_ptile_WKEY,change_lag_2510th_ptile_WKEY,change_lag_2530th_ptile_WKEY,change_lag_2550th_ptile_WKEY,change_lag_2570th_ptile_WKEY,change_lag_2590th_ptile_WKEY,...,volatility_50_WOLF,z_score_50_WOLF,bb_width_50_WOLF,efficiency_ratio_50_WOLF,skew_50_WOLF,volume_force_50_WOLF,rsi_50_WOLF,rsi_divergence_50_WOLF,session_adj_rel_volume_50_WOLF,weekday_adj_vol_50_WOLF
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12787,0.028860,-0.028706,-0.075622,-0.121953,-0.151714,-0.001851,-0.129487,-0.176296,-0.203739,-0.233595,...,0.010659,-1.748623,0.196200,0.015271,-2.669697,-0.004492,48.406174,1.0,0.808260,0.207775
12788,0.008558,-0.047413,-0.093131,-0.138308,-0.167961,-0.021040,-0.146665,-0.192550,-0.219451,-0.248718,...,0.010660,-1.789798,0.196432,0.017050,-2.667708,-0.004324,48.359144,1.0,0.668786,0.207787
12789,0.025028,-0.030436,-0.077637,-0.124033,-0.153889,-0.004816,-0.132729,-0.179364,-0.206704,-0.236449,...,0.010657,-1.820426,0.196685,0.017100,-2.667438,-0.005461,48.322999,1.0,0.988970,0.207727
12790,0.016407,-0.037693,-0.084110,-0.130438,-0.160876,-0.012305,-0.140024,-0.186266,-0.213376,-0.242871,...,0.010657,-1.775078,0.196944,0.018813,-2.667498,0.013389,48.371121,1.0,1.735192,0.207726
12791,0.025151,-0.029016,-0.074701,-0.122514,-0.152613,-0.003661,-0.132625,-0.179266,-0.206609,-0.236358,...,0.010653,-1.773063,0.197197,0.019054,-2.669384,-0.000621,48.369834,1.0,2.500581,0.207664

In [66]:
# #FEATURE SELECTION 2: SELECT PREDS FOR EACH STOCK
import glob
import pandas as pd
industry = 'semiconductors'
corrs_df=pd.read_excel(f'spearman_or_fruit_{industry}.xlsx')
folder_path = "ggp_rel_tables/"+industry

# Get all CSV files in the folder
csv_files = glob.glob(folder_path + "/*.csv")
stocks=[]
for f in csv_files:
    #print(f)
    filename = f.split('\\')[-1].split('/')[-1]

    # 2. Remove prefix and suffix
    ticker = filename.replace('ggp_', '').replace('.csv', '')
    stocks.append(ticker)

from sklearn.feature_selection import mutual_info_classif

def get_mi_features(df,target_col, top_n=27):
    features_giant = joblib.load('features_giant_list.pkl')
    s=target_col.split('_')[-1]
    p = target_col.split('_')[3][:2]
    # Calculate MI scores (this handles the continuous-to-discrete math for you)
    # discrete_features=False tells sklearn that your X vars are continuous
    if p == '85':
            df['target_class'] = (df[target_col] > 0.03).astype(int) 
    else:
            df['target_class'] = (df[target_col] < -0.03).astype(int)
    
    rel_cols=features_giant+['target_class']
    rel_df=df[rel_cols].dropna()
    
    mi_scores = mutual_info_classif(rel_df[features_giant], rel_df['target_class'], discrete_features=False)
    
    # Pair them up and sort
    feature_info = pd.Series(mi_scores, index=features_giant).sort_values(ascending=False)
    
    return feature_info.head(top_n)#.index.tolist()


'''
def getPredSet(s, ind, tar, cutoff, corrs, top_n=27):
    # 1. Base logic: Right target + High enough correlation
    # 2. Add Filter: Exclude anything containing 'ALAB'
    logic = (
        (corrs['target'] == tar) & 
        (corrs['corr'].abs() > cutoff) & 
        (~corrs['potential_var'].str.contains('ALAB', case=False))
    )
    
    # 3. Sort by strength so we keep the most useful ones
    filtered = corrs[logic].copy()
    filtered['abs_corr'] = filtered['corr'].abs()
    filtered = filtered.sort_values('abs_corr', ascending=False)
    
    # 4. Return as a list, capped at top_n
    pred_set = filtered['potential_var'].head(top_n).tolist()
    
    return pred_set'''


#predictors = getPredSet('ADI', 'semiconductors', 'change_lead_15_85th_ptile_ADI', 0.1,corrs_df)
#print(f"Found {len(predictors)} features for this target.")
#print(predictors)
get_mi_features(jino,'change_lead_15_85th_ptile_ADI')

volatility_50_LAES         0.405045
skew_50_TXN                0.393688
skew_50_LSCC               0.391774
rolling_avg_vol_50_TSEM    0.369174
skew_50_SKYT               0.357414
bb_width_50_PXLW           0.350792
skew_50_AMD                0.348461
weekday_adj_vol_50_LAES    0.337440
volatility_25_LAES         0.330915
volatility_50_TXN          0.330862
skew_50_ADI                0.330850
weekday_adj_vol_50_QUIK    0.330218
skew_25_TXN                0.330204
volatility_50_PXLW         0.329906
skew_50_NVDA               0.328758
rolling_avg_vol_50_WOLF    0.326825
rolling_avg_vol_50_WKEY    0.326270
volatility_50_TSEM         0.324723
weekday_adj_vol_50_CRDO    0.323518
volatility_50_WOLF         0.323106
volatility_50_QUIK         0.322317
skew_25_QUIK               0.319452
volatility_50_CRDO         0.318960
skew_50_VLN                0.318768
volatility_50_QCOM         0.317526
volatility_50_AVGO         0.317441
volatility_50_WKEY         0.317234
dtype: float64

In [74]:
# The "Ghost Buster" Test
df=jino
target_col='change_lead_15_85th_ptile_AMD'
features_giant = joblib.load('features_giant_list.pkl')
s=target_col.split('_')[-1]
p = target_col.split('_')[3][:2]
# Calculate MI scores (this handles the continuous-to-discrete math for you)
# discrete_features=False tells sklearn that your X vars are continuous
if p == '85':
        df['target_class'] = (df[target_col] > 0.03).astype(int) 
else:
        df['target_class'] = (df[target_col] < -0.03).astype(int)

rel_cols=features_giant+['target_class']
rel_df=df[rel_cols].dropna()

temp_df = rel_df.copy()
# Shuffle the target within the dataframe
temp_df['target_class'] = temp_df['target_class'].sample(frac=1).values

# Re-run MI
ghost_mi = mutual_info_classif(temp_df[features_giant], temp_df['target_class'], discrete_features=False)
print(pd.Series(ghost_mi, index=features_giant).sort_values(ascending=False).head(10))

relative_volume_50_VLN            0.133360
session_adj_rel_volume_10_MPWR    0.096403
session_adj_rel_volume_10_TXN     0.095849
relative_volume_50_MPWR           0.093503
relative_volume_50_IMOS           0.092711
rsi_divergence_25_MTSI            0.090135
relative_volume_25_GCTS           0.089531
rsi_divergence_10_NVTS            0.087600
change_lag_5030th_ptile_STM       0.086091
change_lag_2570th_ptile_LSCC      0.086012
dtype: float64

In [12]:
#MODEL TRAINING 1: DEFINE TIME METRICS FXN AND LOAD DATA TO SPLIT
import numpy as np
import pandas as pd

def get_temporal_metrics(y_true, y_pred, timestamps):
    """
    Calculates extended metrics including temporal variance of True Positives.
    timestamps: Must be a pandas Series of datetime objects corresponding to y_true/y_pred
    """
    # 1. Basic Counts
    total_rows = len(y_true)
    class_1_count = np.sum(y_true == 1)
    class_1_pct = (class_1_count / total_rows) * 100 if total_rows > 0 else 0
    
    # 2. Identify True Positives (TP)
    # Ensure inputs are aligned numpy arrays or pandas series
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    timestamps = np.array(timestamps)
    
    tp_mask = (y_true == 1) & (y_pred == 1)
    tp_timestamps = timestamps[tp_mask]
    
    # 3. Calculate Temporal Aggregates for TPs
    if len(tp_timestamps) > 1:
        # Convert to numeric (seconds) to calculate variance
        # Note: timestamps must be datetime64[ns]
        ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')
        
        # Variance (in Days Squared for readability)
        # 86400 seconds in a day
        var_seconds_sq = ts_numeric.var()
        var_days_sq = var_seconds_sq / (86400 ** 2)
        
        # Range (Duration between first and last TP)
        time_range = pd.to_datetime(tp_timestamps.max()) - pd.to_datetime(tp_timestamps.min())
        range_days = time_range.total_seconds() / 86400
        
        # Mean Time Distance (Average gap between consecutive TPs)
        # Sort first to measure gaps
        sorted_ts = np.sort(ts_numeric)
        avg_gap_hours = np.mean(np.diff(sorted_ts)) / 3600
        
    else:
        var_days_sq = 0
        range_days = 0
        avg_gap_hours = 0

    return {
        "total_test_rows": total_rows,
        "test_class1_pct": class_1_pct,
        "tp_var_days_sq": var_days_sq,
        "tp_range_days": range_days,
        "tp_avg_gap_hours": avg_gap_hours,
        "n_true_positives": len(tp_timestamps)
    }
# Load Data
try:
    #df = def getPredSet(s, ind, tar, cutoff,corrs):
    df=pd.read_csv('feature_presentation_'+industry+'.csv')
except FileNotFoundError:
    try:
        df = pd.read_csv(f)
    except FileNotFoundError:
        print(f"File not found for {s}. Skipping.")

In [7]:
import joblib
import os

# --- NEW: SAVE CHAMPION MODEL ---
# Create directory if it doesn't exist
MODEL_DIR = "./models/"
if not os.path.exists(MODEL_DIR):
    os.makedirs(MODEL_DIR)

In [11]:
[c for c in df.columns if '75' in c]

[]

In [18]:
#MODEL TRAINING 2: THOMAS AND HIS FIENDS
# CLASS GRID GIANT PRUNING
import pandas as pd
import numpy as np
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report, precision_score, precision_recall_fscore_support,f1_score
from itertools import product
import matplotlib.pyplot as plt
import seaborn as sns
import time
import os

# Set style
plt.style.use('ggplot')

# -----------------------------------
all_results = []
num = 0
IMPORTANCE_THRESHOLD = 0.025 # Define the pruning threshold

# 5. Define Parameter Grid
param_grid_values = {
    'n_estimators': [100, 300],
    'learning_rate': [0.05, 0.1],
    'max_depth': [3, 5, 7],         # Shallower trees often better for noisy finance data
    'min_samples_leaf': [20],       # Keep this high to avoid fitting to noise
    'subsample': [0.8, 1.0]         # 0.8 reduces variance (like Dropout in Neural Nets)
}

timestamp_col = 'timestamp'
df = df.sort_values(timestamp_col).reset_index(drop=True)
# Assuming csv_files and industry are defined elsewhere in your environment
# for f in csv_files:
# (I am assuming the loop starts here based on your snippet)
train_count=0
for s in stocks:
    if train_count>=30:
            break
    for p in ['15','85']:
        train_count+=1
        if train_count<=10:
            continue
        if train_count>=30:
            break
        save_path= f"{MODEL_DIR}champion_model_{s}_{p}.pkl"
        if os.path.exists(save_path):
            file_mtime = os.path.getmtime(save_path)
            current_time = time.time()
            age_in_seconds = current_time - file_mtime
            age_in_days = age_in_seconds / (24 * 3600)
            if age_in_days < 7:
                print(f"Existing model is only {age_in_days:.1f} days old. Skipping save.")
                continue
        start_time = time.time()
        skip = False
        #if s in ['ADI','B']:
            #continue
        num += 1
        print(s)
        if num >= 12:
            print(num)
            break
        # 1. Setup and Load Data
        
        #if s not in ['ARCO','BH','BJRI','BROS','CAVA','CBRL','CMG','CNNE']:
        #continue
        if '.' in s or not s:
            continue
        
        print(f"\n================ Starting analysis for symbol: {s} ================")
        
        
        # NEW CODE (Uses the master timestamp)
         
        
        # Quick check to handle cases where it might be the index
        if timestamp_col not in df.columns and df.index.name == 'timestamp':
             df = df.reset_index()
             
        if timestamp_col not in df.columns:
            print(f"Master 'timestamp' column not found. Skipping {s}.")
            continue
        

        if not pd.api.types.is_datetime64_any_dtype(df[timestamp_col]):
            print(f"Converting {timestamp_col} to datetime...")
            df[timestamp_col] = pd.to_datetime(df[timestamp_col], utc=True)
        
        
        # 2. Set up Features and Targets
        # Wrapped in parentheses to allow multi-line list addition
        target_col_name = f'change_lead_15_{p}th_ptile_{s}'
        initial_features = getPredSet(s, industry, target_col_name, .05,corrs_df)
        
        feature_cols_all = initial_features + [timestamp_col]
    
        
        if target_col_name not in df.columns:
            print(f"Target column {target_col_name} not found. Skipping {s}.")
            continue
        
        # 3. Create Binary Target and Clean NaNs
        # model_df contains all features + timestamp + target, only non-NaN rows
        model_df = df[feature_cols_all + [target_col_name]].copy()
        model_df[feature_cols_all] = model_df[feature_cols_all].ffill() # Fill features

        if p == '85':
            model_df['target_class'] = (model_df[target_col_name] > 0.03).astype(int) 
        else:
            model_df['target_class'] = (model_df[target_col_name] < -0.03).astype(int)
            
        print(f"Using threshold: 0.03 for {s}")
        model_df = model_df.dropna()
        if len(model_df) < 1000:
            print(f"Not enough data points ({len(model_df)}) after cleanup. Skipping {s}.")
            continue
        # 3. Clean and Safety Check
        initial_len = len(model_df)
        model_df[feature_cols_all] = model_df[feature_cols_all].ffill() 
        
        # Drop NaNs but check how much we lose
        model_df = model_df.dropna()
        final_len = len(model_df)
        
        print(f"Data Points: {initial_len} -> {final_len} (Dropped {initial_len - final_len} rows)")
        
            
        # Check Class Balance
        pos_count = model_df['target_class'].sum()
        if pos_count < 50:
            print(f"❌ Insufficient positive targets ({pos_count}). Skipping {s}.")
            continue
        # 4. Define and Apply 70/15/15 Split with Buffer (Indices remain fixed)
        #print('before splitting')
        rows_per_day = 26  
        max_lead_days = 15  
        buffer_rows = max_lead_days * rows_per_day
        
        total_rows = len(model_df)
        test_size = int(total_rows * 0.2)
        val_size = int(total_rows * 0.2)
        
        idx_test_start = total_rows - test_size - buffer_rows
        idx_val_end = idx_test_start - buffer_rows
        idx_val_start = idx_val_end - val_size
        idx_train_end = idx_val_start - buffer_rows
        
        # Initial X/y split (still contains ALL possible features + timestamp)
        X_pool = model_df[feature_cols_all]
        y_pool = model_df['target_class']
        
        # ---------------------------------------------------------
        # === RECURSIVE FEATURE PRUNING LOOP ===
        # ---------------------------------------------------------
        #print('after splitting')
        current_features = initial_features.copy()
        temp_clf = None 
        best_params = {}
        
        # --- NEW: Track the "Champion" (Best Parsimonious) Set ---
        champion_features = current_features.copy()
        champion_params = {}
        champion_score = -1.0   # The score of the current champion
        global_max_score = -1.0 # The absolute best score seen (to calculate the 0.01 drop)
        # --------------------------------------------------------
        
        iteration = 0
        print('before while true')
        while True:
            iteration += 1
            
            # 4b. Slice data based on CURRENT features
            current_cols = current_features + [timestamp_col]
            X = X_pool[current_cols]
            y = y_pool
            
            X_train = X.iloc[:idx_train_end]
            y_train = y.iloc[:idx_train_end]
            X_val = X.iloc[idx_val_start:idx_val_end]
            y_val = y.iloc[idx_val_start:idx_val_end]
            print(len(X_val))
            X_train_clean = X_train.drop(columns=[timestamp_col])
            X_val_clean = X_val.drop(columns=[timestamp_col])
            
            if len(X_train_clean) <= 0 or len(X_val_clean) <= 0 or len(X_train_clean.columns) <= 0:
                print('train clean: ',len(X_train_clean))
                print('val clean: ',len(X_val_clean))
                print('train clean cols: ',len(X_train_clean.columns))
                print('train cols: ',len(X_train.columns))
                print("ERROR: Training or Validation set is empty after slicing. Breaking.")
                skip = True
                break
            
            # 6. Grid Search (Re-run for current feature set)
            iter_best_score = -1
            iter_best_params = {}
            
            keys, values = zip(*param_grid_values.items())
            print('before val loop')
            for v in product(*values):
                params = dict(zip(keys, v))
                clf = GradientBoostingClassifier(random_state=42, **params)
                clf.fit(X_train_clean, y_train)
                #print('after clf fit')
                preds_val = clf.predict(X_val_clean)
                #print('after clf val predict')
                # Calculate score for this specific param combo
                current_score = f1_score(y_val, preds_val, pos_label=1, zero_division=0)#precision_score(y_val, preds_val, zero_division=0)
               
                if current_score > iter_best_score:
                    iter_best_score = current_score
                    iter_best_params = params
            
            print(f"Iteration {iteration}: Features={len(current_features)} | Best Val Score={iter_best_score:.4f}")
            
            # --- NEW: Check if this feature set is the new "Champion" ---
            # Update the Global Max Score if this iteration beat everything before it
            if iter_best_score > global_max_score:
                global_max_score = iter_best_score
            
            # Parsimony Logic: 
            # We accept this new set if the score hasn't dropped by more than 0.01 compared 
            # to the absolute best score seen so far.
            if iter_best_score >= (global_max_score - 0.01):
                champion_features = current_features.copy()
                champion_params = iter_best_params
                champion_score = iter_best_score
                print(f"   >>> New Champion Selected! (Score: {iter_best_score:.4f} is within 0.01 of Max {global_max_score:.4f})")
            else:
                print(f"   >>> Score drop > 0.01 (Val: {iter_best_score:.4f} vs Max: {global_max_score:.4f}). Keeping previous Champion.")
            # ------------------------------------------------------------
            
            # 7. Train Model for Importance Check (using Train+Val)
            X_train_final = pd.concat([X_train_clean, X_val_clean])
            y_train_final = pd.concat([y_train, y_val])
            
            # We use the params found in THIS iteration to determine importances for pruning
            temp_clf = GradientBoostingClassifier(random_state=42, **iter_best_params)
            temp_clf.fit(X_train_final, y_train_final)
            
            # 8. Check and Prune Features
            importances = temp_clf.feature_importances_
            
            next_features = [
                feat for feat, imp in zip(current_features, importances)
                if imp >= IMPORTANCE_THRESHOLD
            ]
            
            # --- Convergence and Safeguard Checks ---
            if set(next_features) == set(current_features):
                print(f"Iteration {iteration}: Converged (No features dropped).")
                break
               
            if len(next_features) == 0:
                 print(f"Iteration {iteration}: All features below threshold. Breaking.")
                 break
                 
            if iteration > 5:
                print(f"Iteration {iteration}: Max iterations reached.")
                break
            
            print(f"Iteration {iteration}: Pruning {len(current_features) - len(next_features)} features.")
            current_features = next_features
            
        
        if skip == False:
        # ---------------------------------------------------------
        # === RESTORE CHAMPION SET ===
        # ---------------------------------------------------------
            print(f"\nPruning Complete. Reverting to Champion Feature Set (Size: {len(champion_features)}) with Score: {champion_score:.4f}")
            current_features = champion_features
            best_params = champion_params
        
            # Retrain Final Model on the Champion Features + Champion Params
            X_train_final_pool = X_pool[current_features + [timestamp_col]].iloc[:idx_val_end]
            y_train_final_pool = y_pool.iloc[:idx_val_end]
            X_train_final_clean = X_train_final_pool.drop(columns=[timestamp_col])
            
            final_clf = GradientBoostingClassifier(random_state=42, **best_params)
            final_clf.fit(X_train_final_clean, y_train_final_pool)
            
            print(f"\nGrid Search & Selection Complete. Best Parameters: {best_params}")
            
            # 8. Final Evaluation on Hold-out Test Set
            # Slice the test set using the FINAL 'current_features' (which is now the Champion set)
            X_test = X_pool[current_features + [timestamp_col]].iloc[idx_test_start:]
            y_test = y_pool.iloc[idx_test_start:]
            
            X_test_clean = X_test.drop(columns=[timestamp_col])
            preds_test = final_clf.predict(X_test_clean)
            
            print(f"\n--- Final Test Set Evaluation for {s} ---")
            print(classification_report(y_test, preds_test, zero_division=0))
            
            # 9. Extract and Store Results
            prec, r, f1, support = precision_recall_fscore_support(y_test, preds_test, average=None, zero_division=0)
            try:
                class_1_precision = prec[1]
                class_1_recall = r[1]
                class_1_f1 = f1[1]
            except:
                print('no class 1')
                continue
            
            # NOTE: Ensure get_temporal_metrics is defined in your environment
            try:
                timestamps = X_test[timestamp_col] 
                metrics = get_temporal_metrics(y_test, preds_test, timestamps)
            except NameError:
                metrics = {}
                print("Warning: get_temporal_metrics function not found.")
            
            # 10. Feature Importance (Using the final feature set and model)
            importance_df = pd.DataFrame({
                'Feature': current_features, 
                'Importance': final_clf.feature_importances_
            }).sort_values('Importance', ascending=False)
        
            top_importance_df = importance_df[importance_df['Importance'] > 0.05]
            top_importance_dict = top_importance_df.set_index('Feature')['Importance'].to_dict()
            
            print("\nTop 10 Feature Importances (Final Tuned Model):")
            print(importance_df.head(10).to_markdown(index=False))
            
            result_entry = {
                'Symbol': s,
                'Final_Feature_Count': len(current_features),
                'Best_Params': str(best_params),
                'Test_Precision_Class1': class_1_precision,
                'Test_Recall_Class1': class_1_recall,
                'Test_F1_Class1': class_1_f1,
                'Top_Feature_Importances': top_importance_dict
            }
            result_entry = {**result_entry, **metrics}
            all_results.append(result_entry)
    
            # Bundle the model and the specific features used
            model_data = {
                'model': final_clf,
                'features': current_features,  # These are the champion features
                'params': best_params,
                'symbol': s,
                'side': p,  # '15' for downside, '85' for upside
                'trained_at': pd.Timestamp.now().strftime('%Y-%m-%d %H:%M')
            }
            
            # Save the file
            print(f"No existing model found for {s}_{p}. Saving...")
            joblib.dump(model_data, save_path, compress=3)
            print(f"✅ Model saved to: {save_path}")
        else:
            print(f"⏭️ Skipping final fit and save for {s}_{p} due to earlier errors.")

# --- LOOP END: CONSOLIDATE RESULTS ---
results_df = pd.DataFrame(all_results)
print("\n================== CONSOLIDATED RESULTS ==================")
print(results_df.to_markdown(index=False))

AOSL

================ Starting analysis for symbol: AOSL ================
Converting timestamp to datetime...
Using threshold: 0.03 for AOSL
Data Points: 11477 -> 11477 (Dropped 0 rows)
before while true
2295
before val loop
Iteration 1: Features=27 | Best Val Score=0.6625
   >>> New Champion Selected! (Score: 0.6625 is within 0.01 of Max 0.6625)
Iteration 1: Pruning 17 features.
2295
before val loop
Iteration 2: Features=10 | Best Val Score=0.7273
   >>> New Champion Selected! (Score: 0.7273 is within 0.01 of Max 0.7273)
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 10) with Score: 0.7273

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': 7, 'min_samples_leaf': 20, 'subsample': 0.8}

--- Final Test Set Evaluation for AOSL ---
              precision    recall  f1-score   support

           0       0.67      0.79      0.73      1382
           1       0.73      0.59      0.65      1303

    accuracy                           0.69      2685
   macro avg       0.70      0.69      0.69      2685
weighted avg       0.70      0.69      0.69      2685


Top 10 Feature Importances (Final Tuned Model):
| Feature                      |   Importance |
|:-----------------------------|-------------:|
| skew_50_PI                   |    0.315317  |
| efficiency_ratio_50_PXLW     |    0.129241  |
| volatility_25_LAES           |    0.11385   |
| skew_50_INTC                 |    0.0937888 |
| skew_25_MX                   |    0.0937273 |
| change_lag_2530th_ptile_GSIT |    0.0695028 |
| skew_50_VSH                  |    0.0575443 |
| skew_50_SLAB                 |    0.0509507 |
| change_lag_5090th_ptile_CEVA |    0.0509279 |
| change_lag_5070th_ptile_CEVA |    0.02515   |
No existing model found for AOSL_15. Saving...

C:\Users\allth\AppData\Local\Temp\ipykernel_9552\770689073.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

✅ Model saved to: ./models/champion_model_AOSL_15.pkl
AOSL

================ Starting analysis for symbol: AOSL ================
Using threshold: 0.03 for AOSL
Data Points: 11477 -> 11477 (Dropped 0 rows)
before while true
2295
before val loop
Iteration 1: Features=27 | Best Val Score=0.7993
   >>> New Champion Selected! (Score: 0.7993 is within 0.01 of Max 0.7993)
Iteration 1: Pruning 17 features.
2295
before val loop
Iteration 2: Features=10 | Best Val Score=0.8306
   >>> New Champion Selected! (Score: 0.8306 is within 0.01 of Max 0.8306)
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 10) with Score: 0.8306

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': 7, 'min_samples_leaf': 20, 'subsample': 0.8}

--- Final Test Set Evaluation for AOSL ---
              precision    recall  f1-score   support

           0       0.50      0.76      0.60      1280
           1       0.59      0.31      0.41      1405

    accuracy                           0.53      2685
   macro avg       0.54      0.54      0.51      2685
weighted avg       0.55      0.53      0.50      2685


Top 10 Feature Importances (Final Tuned Model):
| Feature                      |   Importance |
|:-----------------------------|-------------:|
| rolling_avg_vol_50_MOBX      |    0.258609  |
| change_lag_2550th_ptile_VSH  |    0.193042  |
| rolling_avg_vol_10_MXL       |    0.090122  |
| skew_50_PI                   |    0.0816378 |
| skew_50_TSEM                 |    0.0796992 |
| change_lag_5030th_ptile_INTC |    0.0794568 |
| change_lag_2570th_ptile_NVEC |    0.0571779 |
| rolling_avg_vol_25_INTC      |    0.0557457 |
| change_lag_2530th_ptile_VSH  |    0.0533829 |
| change_lag_2590th_ptile_LSCC |    0.0511265 |
No existing model found for AOSL_85. Saving...
✅ Model saved to: ./models/champion_model_AOSL_85.pkl
ARM

================ Starting analysis for symbol: ARM ================
Using threshold: 0.03 for ARM
Data Points: 11477 -> 11477 (Dropped 0 rows)
before while true
2295
before val loop

C:\Users\allth\AppData\Local\Temp\ipykernel_9552\770689073.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

Iteration 1: Features=27 | Best Val Score=0.6890
   >>> New Champion Selected! (Score: 0.6890 is within 0.01 of Max 0.6890)
Iteration 1: Pruning 16 features.
2295
before val loop
Iteration 2: Features=11 | Best Val Score=0.8000
   >>> New Champion Selected! (Score: 0.8000 is within 0.01 of Max 0.8000)
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 11) with Score: 0.8000

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': 3, 'min_samples_leaf': 20, 'subsample': 1.0}

--- Final Test Set Evaluation for ARM ---
              precision    recall  f1-score   support

           0       0.11      0.10      0.10       733
           1       0.68      0.72      0.70      1952

    accuracy                           0.55      2685
   macro avg       0.40      0.41      0.40      2685
weighted avg       0.52      0.55      0.54      2685


Top 10 Feature Importances (Final Tuned Model):
| Feature                      |   Importance |
|:-----------------------------|-------------:|
| skew_50_WOLF                 |    0.209012  |
| bb_width_25_CRUS             |    0.155391  |
| bb_width_50_NXPI             |    0.14286   |
| change_lag_5090th_ptile_INTC |    0.0975896 |
| bb_width_25_GCTS             |    0.0850983 |
| skew_50_SLAB                 |    0.0637256 |
| bb_width_50_INTC             |    0.0565764 |
| z_score_50_RMBS              |    0.0535714 |
| change_lag_5050th_ptile_INTC |    0.0494574 |
| bb_width_10_GCTS             |    0.0457928 |
No existing model found for ARM_15. Saving...
✅ Model saved to: ./models/champion_model_ARM_15.pkl
ARM

================ Starting analysis for symbol: ARM ================
Using threshold: 0.03 for ARM
Data Points: 11477 -> 11477 (Dropped 0 rows)
before while true
2295
before val loop

C:\Users\allth\AppData\Local\Temp\ipykernel_9552\770689073.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

Iteration 1: Features=27 | Best Val Score=0.8244
   >>> New Champion Selected! (Score: 0.8244 is within 0.01 of Max 0.8244)
Iteration 1: Pruning 13 features.
2295
before val loop
Iteration 2: Features=14 | Best Val Score=0.8666
   >>> New Champion Selected! (Score: 0.8666 is within 0.01 of Max 0.8666)
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 14) with Score: 0.8666

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 100, 'learning_rate': 0.05, 'max_depth': 5, 'min_samples_leaf': 20, 'subsample': 1.0}

--- Final Test Set Evaluation for ARM ---
              precision    recall  f1-score   support

           0       0.69      0.63      0.66      1540
           1       0.55      0.63      0.59      1145

    accuracy                           0.63      2685
   macro avg       0.62      0.63      0.62      2685
weighted avg       0.63      0.63      0.63      2685


Top 10 Feature Importances (Final Tuned Model):
| Feature                  |   Importance |
|:-------------------------|-------------:|
| bb_width_50_NXPI         |    0.332841  |
| efficiency_ratio_50_INTC |    0.0890138 |
| rolling_avg_vol_50_SLAB  |    0.0744501 |
| bb_width_50_INTC         |    0.0711871 |
| efficiency_ratio_50_CEVA |    0.0657719 |
| bb_width_50_GCTS         |    0.0565379 |
| bb_width_10_GCTS         |    0.0509751 |
| efficiency_ratio_25_HIMX |    0.0493159 |
| efficiency_ratio_50_QCOM |    0.0476194 |
| bb_width_10_AMD          |    0.0453158 |
No existing model found for ARM_85. Saving...
✅ Model saved to: ./models/champion_model_ARM_85.pkl
ASX

================ Starting analysis for symbol: ASX ================
Using threshold: 0.03 for ASX
Data Points: 11477 -> 11477 (Dropped 0 rows)
before while true
2295
before val loop

C:\Users\allth\AppData\Local\Temp\ipykernel_9552\770689073.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

Iteration 1: Features=27 | Best Val Score=0.4997
   >>> New Champion Selected! (Score: 0.4997 is within 0.01 of Max 0.4997)
Iteration 1: Pruning 14 features.
2295
before val loop
Iteration 2: Features=13 | Best Val Score=0.3212
   >>> Score drop > 0.01 (Val: 0.3212 vs Max: 0.4997). Keeping previous Champion.
Iteration 2: Pruning 1 features.
2295
before val loop
Iteration 3: Features=12 | Best Val Score=0.3446
   >>> Score drop > 0.01 (Val: 0.3446 vs Max: 0.4997). Keeping previous Champion.
Iteration 3: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 27) with Score: 0.4997

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': 7, 'min_samples_leaf': 20, 'subsample': 1.0}

--- Final Test Set Evaluation for ASX ---
              precision    recall  f1-score   support

           0       0.87      0.85      0.86      2064
           1       0.53      0.57      0.55       621

    accuracy                           0.78      2685
   macro avg       0.70      0.71      0.70      2685
weighted avg       0.79      0.78      0.79      2685


Top 10 Feature Importances (Final Tuned Model):
| Feature                 |   Importance |
|:------------------------|-------------:|
| skew_50_SLAB            |    0.155418  |
| weekday_adj_vol_25_TSEM |    0.137527  |
| bb_width_50_MX          |    0.1203    |
| volatility_50_TSEM      |    0.0798777 |
| volatility_10_MRAM      |    0.0767547 |
| rolling_avg_vol_25_TSEM |    0.076525  |
| bb_width_50_IMOS        |    0.0468487 |
| volatility_25_LASR      |    0.0449631 |
| bb_width_25_SKYT        |    0.0424244 |
| rolling_avg_vol_25_POWI |    0.0305499 |
No existing model found for ASX_15. Saving...

C:\Users\allth\AppData\Local\Temp\ipykernel_9552\770689073.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

✅ Model saved to: ./models/champion_model_ASX_15.pkl
ASX

================ Starting analysis for symbol: ASX ================
Using threshold: 0.03 for ASX
Data Points: 11477 -> 11477 (Dropped 0 rows)
before while true
2295
before val loop
Iteration 1: Features=27 | Best Val Score=0.4205
   >>> New Champion Selected! (Score: 0.4205 is within 0.01 of Max 0.4205)
Iteration 1: Pruning 15 features.
2295
before val loop
Iteration 2: Features=12 | Best Val Score=0.3993
   >>> Score drop > 0.01 (Val: 0.3993 vs Max: 0.4205). Keeping previous Champion.
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 27) with Score: 0.4205

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 3, 'min_samples_leaf': 20, 'subsample': 0.8}

--- Final Test Set Evaluation for ASX ---
              precision    recall  f1-score   support

           0       0.19      0.47      0.27       707
           1       0.62      0.30      0.41      1978

    accuracy                           0.35      2685
   macro avg       0.40      0.39      0.34      2685
weighted avg       0.50      0.35      0.37      2685


Top 10 Feature Importances (Final Tuned Model):
| Feature                  |   Importance |
|:-------------------------|-------------:|
| bb_width_50_NVDA         |    0.178806  |
| volatility_50_RMBS       |    0.145759  |
| rolling_avg_vol_10_CEVA  |    0.103992  |
| rolling_avg_vol_25_TSEM  |    0.0839807 |
| bb_width_50_IMOS         |    0.0616988 |
| bb_width_50_TSEM         |    0.0564563 |
| rolling_avg_vol_25_SKYT  |    0.047252  |
| efficiency_ratio_50_AVGO |    0.0430733 |
| rolling_avg_vol_25_MTSI  |    0.0402743 |
| weekday_adj_vol_50_RMBS  |    0.0291039 |
No existing model found for ASX_85. Saving...
✅ Model saved to: ./models/champion_model_ASX_85.pkl
AVGO

================ Starting analysis for symbol: AVGO ================
Using threshold: 0.03 for AVGO
Data Points: 12127 -> 12127 (Dropped 0 rows)
before while true
2425
before val loop

C:\Users\allth\AppData\Local\Temp\ipykernel_9552\770689073.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

Iteration 1: Features=27 | Best Val Score=0.2222
   >>> New Champion Selected! (Score: 0.2222 is within 0.01 of Max 0.2222)
Iteration 1: Pruning 13 features.
2425
before val loop
Iteration 2: Features=14 | Best Val Score=0.2358
   >>> New Champion Selected! (Score: 0.2358 is within 0.01 of Max 0.2358)
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 14) with Score: 0.2358

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 100, 'learning_rate': 0.05, 'max_depth': 7, 'min_samples_leaf': 20, 'subsample': 1.0}

--- Final Test Set Evaluation for AVGO ---
              precision    recall  f1-score   support

           0       0.72      0.62      0.67      1298
           1       0.71      0.80      0.75      1517

    accuracy                           0.71      2815
   macro avg       0.72      0.71      0.71      2815
weighted avg       0.71      0.71      0.71      2815


Top 10 Feature Importances (Final Tuned Model):
| Feature                      |   Importance |
|:-----------------------------|-------------:|
| bb_width_50_WOLF             |    0.312116  |
| change_lag_1030th_ptile_RMBS |    0.0930679 |
| volatility_50_SKYT           |    0.0820618 |
| skew_25_PI                   |    0.0760165 |
| skew_25_TSEM                 |    0.0739341 |
| bb_width_10_WOLF             |    0.0581479 |
| change_lag_5070th_ptile_ASX  |    0.0562586 |
| rolling_avg_vol_10_MRVL      |    0.0496384 |
| bb_width_25_WOLF             |    0.0472437 |
| change_lag_1090th_ptile_RMBS |    0.0430847 |
No existing model found for AVGO_15. Saving...
✅ Model saved to: ./models/champion_model_AVGO_15.pkl
AVGO

================ Starting analysis for symbol: AVGO ================
Using threshold: 0.03 for AVGO
Data Points: 12766 -> 12766 (Dropped 0 rows)
before while true
2553
before val loop

C:\Users\allth\AppData\Local\Temp\ipykernel_9552\770689073.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

Iteration 1: Features=27 | Best Val Score=0.7519
   >>> New Champion Selected! (Score: 0.7519 is within 0.01 of Max 0.7519)
Iteration 1: Pruning 19 features.
2553
before val loop
Iteration 2: Features=8 | Best Val Score=0.7291
   >>> Score drop > 0.01 (Val: 0.7291 vs Max: 0.7519). Keeping previous Champion.
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 27) with Score: 0.7519

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 100, 'learning_rate': 0.1, 'max_depth': 3, 'min_samples_leaf': 20, 'subsample': 0.8}

--- Final Test Set Evaluation for AVGO ---
              precision    recall  f1-score   support

           0       0.64      0.79      0.70      1469
           1       0.72      0.55      0.63      1474

    accuracy                           0.67      2943
   macro avg       0.68      0.67      0.67      2943
weighted avg       0.68      0.67      0.67      2943


Top 10 Feature Importances (Final Tuned Model):
| Feature                      |   Importance |
|:-----------------------------|-------------:|
| skew_25_WOLF                 |    0.215234  |
| bb_width_10_LSCC             |    0.152632  |
| rolling_avg_vol_10_ADI       |    0.1224    |
| change_lag_2530th_ptile_RMBS |    0.0867899 |
| z_score_25_INTC              |    0.0655361 |
| change_lag_1010th_ptile_INTC |    0.0515635 |
| change_lag_1070th_ptile_NVDA |    0.0486305 |
| change_lag_1030th_ptile_MU   |    0.0399105 |
| change_lag_1010th_ptile_MU   |    0.0386382 |
| change_lag_5090th_ptile_ASX  |    0.0239556 |
No existing model found for AVGO_85. Saving...
✅ Model saved to: ./models/champion_model_AVGO_85.pkl
CEVA

================ Starting analysis for symbol: CEVA ================
Using threshold: 0.03 for CEVA
Data Points: 11477 -> 11477 (Dropped 0 rows)
before while true
2295
before val loop

C:\Users\allth\AppData\Local\Temp\ipykernel_9552\770689073.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

Iteration 1: Features=27 | Best Val Score=0.7902
   >>> New Champion Selected! (Score: 0.7902 is within 0.01 of Max 0.7902)
Iteration 1: Pruning 16 features.
2295
before val loop
Iteration 2: Features=11 | Best Val Score=0.8076
   >>> New Champion Selected! (Score: 0.8076 is within 0.01 of Max 0.8076)
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 11) with Score: 0.8076

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 5, 'min_samples_leaf': 20, 'subsample': 0.8}

--- Final Test Set Evaluation for CEVA ---
              precision    recall  f1-score   support

           0       0.77      0.23      0.35      1242
           1       0.59      0.94      0.72      1443

    accuracy                           0.61      2685
   macro avg       0.68      0.59      0.54      2685
weighted avg       0.67      0.61      0.55      2685


Top 10 Feature Importances (Final Tuned Model):
| Feature                      |   Importance |
|:-----------------------------|-------------:|
| efficiency_ratio_25_MCHP     |    0.208546  |
| skew_50_MRVL                 |    0.138176  |
| change_lag_5030th_ptile_UMC  |    0.124811  |
| bb_width_25_GSIT             |    0.111555  |
| efficiency_ratio_50_MCHP     |    0.0986854 |
| change_lag_2510th_ptile_GSIT |    0.0778533 |
| rolling_avg_vol_25_SIMO      |    0.0621356 |
| skew_50_ARM                  |    0.0601079 |
| rsi_50_VSH                   |    0.0415158 |
| change_lag_2530th_ptile_GSIT |    0.0393665 |
No existing model found for CEVA_15. Saving...
✅ Model saved to: ./models/champion_model_CEVA_15.pkl
CEVA

================ Starting analysis for symbol: CEVA ================
Using threshold: 0.03 for CEVA
Data Points: 12766 -> 12766 (Dropped 0 rows)
before while true
2553
before val loop

C:\Users\allth\AppData\Local\Temp\ipykernel_9552\770689073.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

Iteration 1: Features=27 | Best Val Score=0.5485
   >>> New Champion Selected! (Score: 0.5485 is within 0.01 of Max 0.5485)
Iteration 1: Pruning 16 features.
2553
before val loop
Iteration 2: Features=11 | Best Val Score=0.4024
   >>> Score drop > 0.01 (Val: 0.4024 vs Max: 0.5485). Keeping previous Champion.
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 27) with Score: 0.5485

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 100, 'learning_rate': 0.05, 'max_depth': 7, 'min_samples_leaf': 20, 'subsample': 0.8}

--- Final Test Set Evaluation for CEVA ---
              precision    recall  f1-score   support

           0       0.54      0.77      0.64      1330
           1       0.71      0.47      0.57      1613

    accuracy                           0.60      2943
   macro avg       0.63      0.62      0.60      2943
weighted avg       0.64      0.60      0.60      2943


Top 10 Feature Importances (Final Tuned Model):
| Feature                      |   Importance |
|:-----------------------------|-------------:|
| change_lag_2570th_ptile_WOLF |    0.259074  |
| bb_width_25_GSIT             |    0.123344  |
| change_lag_5090th_ptile_UMC  |    0.108489  |
| skew_10_ADI                  |    0.10252   |
| skew_50_ARM                  |    0.0642134 |
| skew_10_QCOM                 |    0.0517423 |
| skew_25_POWI                 |    0.0474945 |
| skew_10_ARM                  |    0.0397527 |
| change_lag_5010th_ptile_POWI |    0.0316145 |
| rsi_50_MCHP                  |    0.03051   |
No existing model found for CEVA_85. Saving...
✅ Model saved to: ./models/champion_model_CEVA_85.pkl
CRDO

================ Starting analysis for symbol: CRDO ================
Using threshold: 0.03 for CRDO
Data Points: 11477 -> 11477 (Dropped 0 rows)
before while true
2295

C:\Users\allth\AppData\Local\Temp\ipykernel_9552\770689073.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

before val loop
Iteration 1: Features=27 | Best Val Score=0.4073
   >>> New Champion Selected! (Score: 0.4073 is within 0.01 of Max 0.4073)
Iteration 1: Pruning 14 features.
2295
before val loop
Iteration 2: Features=13 | Best Val Score=0.2404
   >>> Score drop > 0.01 (Val: 0.2404 vs Max: 0.4073). Keeping previous Champion.
Iteration 2: Converged (No features dropped).

Pruning Complete. Reverting to Champion Feature Set (Size: 27) with Score: 0.4073

Grid Search & Selection Complete. Best Parameters: {'n_estimators': 100, 'learning_rate': 0.1, 'max_depth': 3, 'min_samples_leaf': 20, 'subsample': 0.8}

--- Final Test Set Evaluation for CRDO ---
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       538
           1       0.80      1.00      0.89      2147

    accuracy                           0.80      2685
   macro avg       0.40      0.50      0.44      2685
weighted avg       0.64      0.80      0.71      2685


Top 10 Feature Importances (Final Tuned Model):
| Feature                    |   Importance |
|:---------------------------|-------------:|
| rolling_avg_vol_50_LSCC    |    0.119221  |
| volatility_10_PXLW         |    0.117016  |
| rolling_avg_vol_50_VLN     |    0.105573  |
| skew_50_PI                 |    0.0977387 |
| weekday_adj_vol_25_MU      |    0.0765598 |
| change_lag_1010th_ptile_MU |    0.0521456 |
| volatility_25_MU           |    0.0404486 |
| skew_50_QUIK               |    0.0369105 |
| volatility_25_MOBXW        |    0.0363508 |
| volatility_50_SKYT         |    0.0293489 |
No existing model found for CRDO_15. Saving...
✅ Model saved to: ./models/champion_model_CRDO_15.pkl
CRDO
12
CRUS
13
DIOD
14
GCTS
15
GFS
16
GSIT
17
HIMX
18
ICG
19

================== CONSOLIDATED RESULTS ==================
| Symbol   |   Final_Feature_Count | Best_Params                                                                                            |   Test_Precision_Class1 |   Test_Recall_Class1 |   Test_F1_Class1 | Top_Feature_Importances                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |   total_test_rows |   test_class1_pct |   tp_var_days_sq |   tp_range_days |   tp_avg_gap_hours |   n_true_positives |
|:---------|----------------------:|:-------------------------------------------------------------------------------------------------------|------------------------:|---------------------:|-----------------:|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------:|------------------:|-----------------:|----------------:|-------------------:|-------------------:|
| AOSL     |                    10 | {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': 7, 'min_samples_leaf': 20, 'subsample': 0.8}  |                0.726336 |             0.594781 |         0.654008 | {'skew_50_PI': 0.31531680445873694, 'efficiency_ratio_50_PXLW': 0.12924116984440787, 'volatility_25_LAES': 0.1138502990345175, 'skew_50_INTC': 0.09378877975203388, 'skew_25_MX': 0.09372729343949922, 'change_lag_2530th_ptile_GSIT': 0.06950281253858352, 'skew_50_VSH': 0.057544255600147746, 'skew_50_SLAB': 0.050950680683794915, 'change_lag_5090th_ptile_CEVA': 0.0509279294242318}                                                                                                     |              2685 |           48.5289 |          987.128 |        138.979  |            4.30943 |                775 |
| AOSL     |                    10 | {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': 7, 'min_samples_leaf': 20, 'subsample': 0.8}  |                0.588156 |             0.311032 |         0.40689  | {'rolling_avg_vol_50_MOBX': 0.25860941279584676, 'change_lag_2550th_ptile_VSH': 0.193041865532151, 'rolling_avg_vol_10_MXL': 0.09012198748918362, 'skew_50_PI': 0.08163777012961294, 'skew_50_TSEM': 0.07969915825610267, 'change_lag_5030th_ptile_INTC': 0.07945683985420303, 'change_lag_2570th_ptile_NVEC': 0.05717786622823265, 'rolling_avg_vol_25_INTC': 0.05574566031940051, 'change_lag_2530th_ptile_VSH': 0.053382920252893595, 'change_lag_2590th_ptile_LSCC': 0.051126519142373025} |              2685 |           52.3277 |          518.641 |        104.073  |            5.72878 |                437 |
| ARM      |                    11 | {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': 3, 'min_samples_leaf': 20, 'subsample': 1.0}  |                0.67909  |             0.71875  |         0.698357 | {'skew_50_WOLF': 0.20901176843233094, 'bb_width_25_CRUS': 0.15539129858123607, 'bb_width_50_NXPI': 0.1428601003062349, 'change_lag_5090th_ptile_INTC': 0.09758955365424465, 'bb_width_25_GCTS': 0.0850982632205892, 'skew_50_SLAB': 0.06372563932340877, 'bb_width_50_INTC': 0.05657636259646471, 'z_score_50_RMBS': 0.053571395055504054}                                                                                                                                                     |              2685 |           72.7002 |         1490.39  |        138.76   |            2.37536 |               1403 |
| ARM      |                    14 | {'n_estimators': 100, 'learning_rate': 0.05, 'max_depth': 5, 'min_samples_leaf': 20, 'subsample': 1.0} |                0.554954 |             0.626201 |         0.588428 | {'bb_width_50_NXPI': 0.33284095918489265, 'efficiency_ratio_50_INTC': 0.08901378143848926, 'rolling_avg_vol_50_SLAB': 0.07445013739425847, 'bb_width_50_INTC': 0.07118711493141822, 'efficiency_ratio_50_CEVA': 0.06577191540367029, 'bb_width_50_GCTS': 0.05653788811999025, 'bb_width_10_GCTS': 0.05097512993477448}                                                                                                                                                                         |              2685 |           42.6443 |         2792.86  |        133.969  |            4.49057 |                717 |
| ASX      |                    27 | {'n_estimators': 300, 'learning_rate': 0.1, 'max_depth': 7, 'min_samples_leaf': 20, 'subsample': 1.0}  |                0.531343 |             0.573269 |         0.55151  | {'skew_50_SLAB': 0.15541828961186824, 'weekday_adj_vol_25_TSEM': 0.1375274114475179, 'bb_width_50_MX': 0.1203000150781711, 'volatility_50_TSEM': 0.07987772595294301, 'volatility_10_MRAM': 0.07675474704585228, 'rolling_avg_vol_25_TSEM': 0.07652501726010938}                                                                                                                                                                                                                               |              2685 |           23.1285 |          525.769 |         84.1146 |            5.68662 |                356 |
| ASX      |                    27 | {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 3, 'min_samples_leaf': 20, 'subsample': 0.8} |                0.615148 |             0.303842 |         0.406768 | {'bb_width_50_NVDA': 0.17880581406038212, 'volatility_50_RMBS': 0.1457587512244434, 'rolling_avg_vol_10_CEVA': 0.10399236501665049, 'rolling_avg_vol_25_TSEM': 0.08398074980611316, 'bb_width_50_IMOS': 0.061698794738435675, 'bb_width_50_TSEM': 0.056456282228956434}                                                                                                                                                                                                                        |              2685 |           73.6685 |         1360.99  |        141.01   |            5.64042 |                601 |
| AVGO     |                    14 | {'n_estimators': 100, 'learning_rate': 0.05, 'max_depth': 7, 'min_samples_leaf': 20, 'subsample': 1.0} |                0.708504 |             0.796309 |         0.749845 | {'bb_width_50_WOLF': 0.31211582524223175, 'change_lag_1030th_ptile_RMBS': 0.09306787486844958, 'volatility_50_SKYT': 0.08206177677567675, 'skew_25_PI': 0.07601649011359085, 'skew_25_TSEM': 0.07393410851774224, 'bb_width_10_WOLF': 0.05814794029801961, 'change_lag_5070th_ptile_ASX': 0.05625861112352466}                                                                                                                                                                                 |              2815 |           53.8899 |         2410.38  |        152.01   |            3.02258 |               1208 |
| AVGO     |                    27 | {'n_estimators': 100, 'learning_rate': 0.1, 'max_depth': 3, 'min_samples_leaf': 20, 'subsample': 0.8}  |                0.722913 |             0.552239 |         0.626154 | {'skew_25_WOLF': 0.21523411254854846, 'bb_width_10_LSCC': 0.15263173042180203, 'rolling_avg_vol_10_ADI': 0.12239981737772987, 'change_lag_2530th_ptile_RMBS': 0.08678990147357359, 'z_score_25_INTC': 0.06553610017008306, 'change_lag_1010th_ptile_INTC': 0.05156350558113831}                                                                                                                                                                                                                |              2943 |           50.0849 |         1393.12  |        164.115  |            4.84471 |                814 |
| CEVA     |                    11 | {'n_estimators': 300, 'learning_rate': 0.05, 'max_depth': 5, 'min_samples_leaf': 20, 'subsample': 0.8} |                0.586385 |             0.943174 |         0.723167 | {'efficiency_ratio_25_MCHP': 0.2085456073543962, 'skew_50_MRVL': 0.13817631011253984, 'change_lag_5030th_ptile_UMC': 0.1248112229073143, 'bb_width_25_GSIT': 0.11155523451766274, 'efficiency_ratio_50_MCHP': 0.0986853610249805, 'change_lag_2510th_ptile_GSIT': 0.0778532959627686, 'rolling_avg_vol_25_SIMO': 0.062135643359399174, 'skew_50_ARM': 0.06010794410673893}                                                                                                                     |              2685 |           53.743  |         1608.43  |        137.156  |            2.4204  |               1361 |
| CEVA     |                    27 | {'n_estimators': 100, 'learning_rate': 0.05, 'max_depth': 7, 'min_samples_leaf': 20, 'subsample': 0.8} |                0.710009 |             0.470552 |         0.565996 | {'change_lag_2570th_ptile_WOLF': 0.25907359005413333, 'bb_width_25_GSIT': 0.12334358307131, 'change_lag_5090th_ptile_UMC': 0.10848892221733358, 'skew_10_ADI': 0.10251998831770916, 'skew_50_ARM': 0.06421343702368176, 'skew_10_QCOM': 0.051742301425297225}                                                                                                                                                                                                                                  |              2943 |           54.808  |         1845.77  |        163.771  |            5.18536 |                759 |
| CRDO     |                    27 | {'n_estimators': 100, 'learning_rate': 0.1, 'max_depth': 3, 'min_samples_leaf': 20, 'subsample': 0.8}  |                0.799628 |             1        |         0.888659 | {'rolling_avg_vol_50_LSCC': 0.1192207586994189, 'volatility_10_PXLW': 0.11701551888692947, 'rolling_avg_vol_50_VLN': 0.10557312799989425, 'skew_50_PI': 0.09773865415224905, 'weekday_adj_vol_25_MU': 0.07655980388646594, 'change_lag_1010th_ptile_MU': 0.05214559254363092}                                                                                                                                                                                                                  |              2685 |           79.9628 |         2105.22  |        148.01   |            1.65529 |               2147 |

C:\Users\allth\AppData\Local\Temp\ipykernel_9552\770689073.py:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts_numeric = tp_timestamps.astype('datetime64[s]').astype('int64')

In [29]:
for s in stocks:
    print(s)
    predictors = getPredSet(s, 'semiconductors', 'change_lead_15_85th_ptile_'+s, 0.1,corrs_df)
    print(f"Found {len(predictors)} features for this target.")
    #print(predictors)
    #print(len(getPredSet(s, industry, target_col_name, .05,corrs_df)))

ADI
Found 27 features for this target.
AIP
Found 27 features for this target.
ALAB
Found 27 features for this target.
ALGM
Found 27 features for this target.
AMD
Found 27 features for this target.
AOSL
Found 0 features for this target.
ARM
Found 0 features for this target.
ASX
Found 0 features for this target.
AVGO
Found 0 features for this target.
CEVA
Found 0 features for this target.
CRDO
Found 0 features for this target.
CRUS
Found 0 features for this target.
DIOD
Found 0 features for this target.
GCTS
Found 0 features for this target.
GFS
Found 0 features for this target.
GSIT
Found 0 features for this target.
HIMX
Found 0 features for this target.
ICG
Found 0 features for this target.
IMOS
Found 0 features for this target.
INTC
Found 0 features for this target.
LAES
Found 0 features for this target.
LASR
Found 0 features for this target.
LEDS
Found 0 features for this target.
LSCC
Found 0 features for this target.
MCHP
Found 0 features for this target.
MOBX
Found 0 features for this target.
MOBXW
Found 0 features for this target.
MPWR
Found 0 features for this target.
MRAM
Found 0 features for this target.
MRVL
Found 0 features for this target.
MTSI
Found 0 features for this target.
MU
Found 0 features for this target.
MX
Found 0 features for this target.
MXL
Found 0 features for this target.
NVDA
Found 0 features for this target.
NVEC
Found 0 features for this target.
NVTS
Found 0 features for this target.
NXPI
Found 0 features for this target.
ON
Found 0 features for this target.
PI
Found 0 features for this target.
POET
Found 0 features for this target.
POWI
Found 0 features for this target.
PRSO
Found 0 features for this target.
PXLW
Found 0 features for this target.
QCOM
Found 0 features for this target.
QRVO
Found 0 features for this target.
QUIK
Found 0 features for this target.
RMBS
Found 0 features for this target.
SIMO
Found 0 features for this target.
SITM
Found 0 features for this target.
SKYT
Found 0 features for this target.
SLAB
Found 0 features for this target.
SMTC
Found 0 features for this target.
STM
Found 0 features for this target.
SWKS
Found 0 features for this target.
SYNA
Found 0 features for this target.
TSEM
Found 0 features for this target.
TSM
Found 0 features for this target.
TXN
Found 0 features for this target.
UMC
Found 0 features for this target.
VLN
Found 0 features for this target.
VSH
Found 0 features for this target.
WKEY
Found 0 features for this target.
WOLF
Found 0 features for this target.

In [33]:
results_df.to_csv('results_giant_1_3.csv')

In [37]:
import joblib
import pandas as pd

# 1. Load the pickle file
model_data = joblib.load('models/champion_model_ALGM_15.pkl')

# 2. Extract the model and the feature list from the dictionary
model = model_data['model']
features = model_data['features']

# 3. Get importances directly from the model object
importances = model.feature_importances_

# 4. Create the DataFrame
feat_importance_df = pd.DataFrame({'feature': features, 'importance': importances})

# 5. Display the top 20
#print(f"Total Features: {len(features)}")
#print(feat_importance_df.sort_values(by='importance', ascending=False).head(20))
importances

array([0.0759218 , 0.07604737, 0.05546638, 0.05940929, 0.23850988,
       0.1590574 , 0.15850238, 0.09857664, 0.07850886])

In [8]:
import json
from datetime import datetime
import os
from dotenv import load_dotenv
import joblib
import re
import time
from collections import deque

MODEL_PATHS = glob.glob('models/*.pkl')
MODEL_PATHS.sort()
print(f"✅ Loaded {len(MODEL_PATHS)} models from directory.")

# --- LIMIT SETTINGS ---
MAX_LIVE_TOTAL = 30 # SPY + 29 others
DYNAMIC_PATTERNS = ["change_lag_", "z_score_", "relative_volume_", "volume_force_", "rsi_", "session_adj_"]

live_watchlist_set = {'SPY'}
prep_watchlist_set = {'SPY'}
VALID_MODEL_PATHS = []

print("--- ANALYZING MODELS & ENFORCING LIMITS ---")

for path in MODEL_PATHS:
    try:
        m_data = joblib.load(path)
        features = m_data['features']
        
        # 1. Identify tickers needed for this specific model
        model_dynamic_tickers = set()
        model_all_tickers = set()
        
        for feat in features:
            ticker = feat.split('_')[-1]
            model_all_tickers.add(ticker)
            if any(p in feat for p in DYNAMIC_PATTERNS):
                model_dynamic_tickers.add(ticker)
        
        # 2. Check if this model's dynamic needs fit within our remaining limit
        potential_new_live = live_watchlist_set.union(model_dynamic_tickers)
        
        if len(potential_new_live) <= MAX_LIVE_TOTAL:
            # IT FITS: Commit these tickers to our global sets
            live_watchlist_set.update(model_dynamic_tickers)
            prep_watchlist_set.update(model_all_tickers)
            VALID_MODEL_PATHS.append(path)
        else:
            print(f"SKIPPING: {path} (Requires too many new live symbols. Current: {len(live_watchlist_set)})")
            
    except Exception as e:
        print(f"ERROR loading {path}: {e}")

LIVE_WATCHLIST = list(live_watchlist_set)
PREP_WATCHLIST = list(prep_watchlist_set)

print(f"\nFinal Live Stream List ({len(LIVE_WATCHLIST)}): {LIVE_WATCHLIST}")
print(f"Final Morning Prep List ({len(PREP_WATCHLIST)}): {PREP_WATCHLIST}")

#2.5. Generate daily FEATURE_PRESENTAION
import os
from datetime import datetime
industry='semiconductors'
# 1. Get today's date in YYYY-MM-DD format
today_str = datetime.now().strftime('%Y-%m-%d')

# 2. Construct the full folder path
# This creates a path like: ggp_rel_tables/2026-01-24_ggps/semiconductors
folder_path = f'ggp_rel_tables/{today_str}_ggps/'

# 3. Create the directory (including all parent folders) if it doesn't exist
os.makedirs(folder_path, exist_ok=True)
global min_date
min_date=datetime.now().date()+pd.Timedelta(days=-117)
for s in PREP_WATCHLIST:
    if s!='SPY':
        print(s)
        ggp=getGalledPrices(s,15,[15],[10,25,50])
        ggp.columns = [col + '_' + str(s) for col in ggp.columns]
        ggp.to_csv(folder_path+'/ggp_'+s+'.csv')
getFeaturePres(industry,folder_path,'daily_feature_pres/')

import json

# Bundle the variables into a dictionary
config_data = {
    "LIVE_WATCHLIST": LIVE_WATCHLIST,
    "PREP_WATCHLIST": PREP_WATCHLIST,
    "VALID_MODEL_PATHS": VALID_MODEL_PATHS
}

# Save it to a file
with open('trading_config.json', 'w') as f:
    json.dump(config_data, f, indent=4)
    
print("✅ Saved watchlists and valid models to trading_config.json")

✅ Loaded 21 models from directory.
--- ANALYZING MODELS & ENFORCING LIMITS ---
SKIPPING: models\champion_model_CRDO_15.pkl (Requires too many new live symbols. Current: 30)

Final Live Stream List (30): ['SWKS', 'MOBX', 'NVDA', 'AMD', 'POWI', 'LSCC', 'MTSI', 'TXN', 'TSEM', 'RMBS', 'MCHP', 'MPWR', 'ASX', 'CRUS', 'WOLF', 'SYNA', 'WKEY', 'VSH', 'MU', 'SPY', 'CEVA', 'INTC', 'VLN', 'QRVO', 'UMC', 'QCOM', 'GSIT', 'GCTS', 'ADI', 'NVEC']
Final Morning Prep List (61): ['SWKS', 'MRVL', 'NVDA', 'AMD', 'AIP', 'SKYT', 'TXN', 'PRSO', 'IMOS', 'LEDS', 'CRDO', 'NXPI', 'MRAM', 'SYNA', 'TSM', 'ARM', 'ICG', 'PXLW', 'VSH', 'SPY', 'CEVA', 'WKEY', 'INTC', 'GFS', 'PI', 'SMTC', 'MX', 'MOBX', 'POWI', 'LSCC', 'MTSI', 'TSEM', 'RMBS', 'HIMX', 'MCHP', 'MOBXW', 'SIMO', 'LASR', 'AVGO', 'SLAB', 'MPWR', 'ALGM', 'ASX', 'CRUS', 'QUIK', 'WOLF', 'DIOD', 'AOSL', 'POET', 'GSIT', 'MU', 'UMC', 'QRVO', 'LAES', 'VLN', 'QCOM', 'STM', 'MXL', 'GCTS', 'ADI', 'NVEC']
SWKS
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
MRVL
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
NVDA
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
AMD
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
AIP
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
SKYT
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
TXN
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
PRSO
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
IMOS
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
LEDS
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
CRDO
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
NXPI
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
MRAM
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
SYNA
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
TSM
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
ARM
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
ICG
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
PXLW
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
VSH
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
CEVA
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
WKEY
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
INTC
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
GFS
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
PI
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
SMTC
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
MX
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
MOBX
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop

MOBX: $MOBX: possibly delisted; no earnings dates found
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:287: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_open_30m'] = (pza_agg['minutes_since_open'] <= 30).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:288: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_close_30m'] = (pza_agg['minutes_since_open'] >= 360).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:289: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_mid_day'] = ((pza_agg['minutes_since_open'] > 30) & (pza_agg['minutes_since_open'] < 360)).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']

No earnings data found or processing failed.
POWI
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
LSCC
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
MTSI
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
TSEM
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
RMBS
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
HIMX
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
MCHP
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
MOBXW
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop

MOBXW: $MOBXW: possibly delisted; no earnings dates found
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:287: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_open_30m'] = (pza_agg['minutes_since_open'] <= 30).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:288: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_close_30m'] = (pza_agg['minutes_since_open'] >= 360).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:289: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_mid_day'] = ((pza_agg['minutes_since_open'] > 30) & (pza_agg['minutes_since_open'] < 360)).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']

No earnings data found or processing failed.
SIMO
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
LASR
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
AVGO
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
SLAB
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
MPWR
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
ALGM
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
ASX
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
CRUS
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
QUIK
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
WOLF
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
DIOD
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
AOSL
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
POET
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
GSIT
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
MU
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
UMC
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
QRVO
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
LAES
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop

LAES: $LAES: possibly delisted; no earnings dates found
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:283: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Mon_Interact'] = np.where(pza_agg['day_of_week'] == 0, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:284: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Fri_Interact'] = np.where(pza_agg['day_of_week'] == 4, pza_agg[col_name], 0)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:287: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_open_30m'] = (pza_agg['minutes_since_open'] <= 30).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:288: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_close_30m'] = (pza_agg['minutes_since_open'] >= 360).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:289: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg['is_mid_day'] = ((pza_agg['minutes_since_open'] > 30) & (pza_agg['minutes_since_open'] < 360)).astype(int)
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:300: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Open30m'] = pza_agg[col_name] * pza_agg['is_open_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:301: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_Close30m'] = pza_agg[col_name] * pza_agg['is_close_30m']
C:\Users\allth\AppData\Local\Temp\ipykernel_25484\659804526.py:302: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pza_agg[f'{short_name}_MidDay'] = pza_agg[col_name] * pza_agg['is_mid_day']

No earnings data found or processing failed.
VLN
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
QCOM
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
STM
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
MXL
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
GCTS
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
ADI
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop
NVEC
got minute-level
after weekends
15
got minute-level
after weekends
15
2002
before loop

NameError: name 'getFeaturePres' is not defined

In [25]:
'''# Bundle the variables into a dictionary
config_data = {
    "LIVE_WATCHLIST": LIVE_WATCHLIST,
    "PREP_WATCHLIST": PREP_WATCHLIST,
    "VALID_MODEL_PATHS": VALID_MODEL_PATHS
}

# Save it to a file
with open('trading_config.json', 'w') as f:
    json.dump(config_data, f, indent=4)
    
print("✅ Saved watchlists and valid models to trading_config.json")'''

✅ Saved watchlists and valid models to trading_config.json